import { test, expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { PrismaClient } from '../../packages/db/src';
import { account } from '../helpers';

const db = new PrismaClient();
test.afterAll(() => db.$disconnect());

test('register, save preferences, sign out and sign in on desktop/mobile', async ({ page }, testInfo) => {
  const email = `browser-${randomBytes(6).toString('hex')}@example.test`;
  const password = randomBytes(18).toString('base64url');
  await page.goto('/register?utm_source=LP&utm_medium=owned&utm_campaign=e2e-launch&ref=staff_01');
  await page.getByLabel('表示名', { exact: true }).fill('画面検証ユーザー');
  await page.getByLabel('メールアドレス', { exact: true }).fill(email);
  await page.getByLabel('パスワード', { exact: true }).fill(password);
  await page.getByLabel('20歳以上です。').check();
  await page.getByLabel('利用規約（開発用）に同意します。').check();
  await page.getByLabel('プライバシーポリシー（開発用）に同意します。').check();
  await page.getByRole('button', { name: '同意して登録する' }).click();
  await expect(page.getByRole('heading', { name: 'メールアドレスを確認' })).toBeVisible();
  const user = await db.user.findUniqueOrThrow({ where: { email } });
  expect(await db.memberAcquisition.findUnique({ where: { userId: user.id } })).toMatchObject({ source: 'lp', medium: 'owned', campaign: 'e2e-launch', referralCode: 'staff_01', landingPath: '/register' });
  const mail = JSON.parse(await readFile(resolve('.local/mail', `${user.id}-verify.json`), 'utf8')) as { url: string };
  const verification = new URL(mail.url);
  await page.goto(`${verification.pathname}${verification.search}`);
  await expect(page.getByRole('heading', { name: 'マイページ', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '利用準備' })).toBeVisible();
  await expect(page.getByText('2 / 4', { exact: true })).toBeVisible();
  const publisher = await db.user.findFirstOrThrow({ where: { role: 'ADMIN' } }); const raceDate = '2095-05-05'; const suffix = randomBytes(5).toString('hex');
  const dashboardRace = await db.race.create({ data: { raceDate, venue: `ホーム${suffix}`, number: 5, name: `ホーム告知${suffix}`, startsAt: new Date(`${raceDate}T15:00:00+09:00`) } });
  const dashboardAnnouncement = await db.raceAnnouncement.create({ data: { raceId: dashboardRace.id, version: 1, publishedBy: publisher.id, reason: '会員ホームE2E' } });
  await db.notificationEvent.create({ data: { announcementId: dashboardAnnouncement.id, eventType: 'RACE_ANNOUNCED', status: 'SENT', expandedAt: new Date(), payload: { raceId: dashboardRace.id } } });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '会員ステータス' })).toBeVisible();
  await expect(page.locator('.member-status-card').filter({ hasText: '未読のお知らせ' })).toContainText('1件');
  await expect(page.getByText('未読のお知らせを確認', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'お知らせ、未読1件' })).toBeVisible();
  await page.goto('/notifications');
  await expect(page.getByRole('heading', { name: 'お知らせ', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'すべて', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '未読', exact: true }).click();
  await expect(page.getByRole('button', { name: '未読', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.goto('/account');
  await expect(page.getByLabel('メール通知を受け取る', { exact: true })).toBeChecked();
  await page.getByLabel('メール通知を受け取る', { exact: true }).uncheck();
  await page.getByLabel('記事・動画・音声の更新', { exact: false }).check();
  await page.getByRole('button', { name: '設定を保存' }).click();
  await expect(page.getByRole('status')).toContainText('通知設定を保存しました。');
  await page.reload();
  await expect(page.getByLabel('メール通知を受け取る', { exact: true })).not.toBeChecked();
  await expect(page.getByLabel('記事・動画・音声の更新', { exact: false })).toBeChecked();
  await expect(page.getByRole('heading', { name: '同意履歴' })).toBeVisible();
  await page.goto('/admin');
  await expect(page.getByRole('heading', { name: '閲覧権限がありません' })).toBeVisible();
  const forbidden = await page.request.get('/api/v1/admin/users');
  expect(forbidden.status()).toBe(403);
  await page.goto('/account');
  await page.screenshot({ path: testInfo.outputPath('account.png'), fullPage: true });
  await page.getByRole('button', { name: 'ログアウト', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'おかえりなさい' })).toBeVisible();
  await page.getByLabel('メールアドレス', { exact: true }).fill(email);
  await page.getByLabel('パスワード', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'ログイン', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'マイページ', exact: true })).toBeVisible();
  await page.goto('/plans');
  await expect.poll(() => db.memberJourneyEvent.count({ where: { userId: user.id, eventType: 'PLAN_VIEWED' } })).toBe(1);
  const standardPlan = page.locator('.plan-card').filter({ has: page.getByRole('heading', { name: '通常会員', exact: true }) });
  await standardPlan.getByRole('button', { name: /申込内容を確認/ }).click();
  await expect.poll(() => db.memberJourneyEvent.count({ where: { userId: user.id, eventType: 'CHECKOUT_REVIEWED' } })).toBe(1);
  await expect(page.getByRole('heading', { name: '申込内容の確認' })).toBeVisible();
  await expect(page.locator('#plan-review')).toContainText('通常会員');
  await expect(page.locator('#plan-review')).toContainText('外部への請求やカード情報の送信はありません');
  await expect(page.locator('#plan-review').getByRole('button').last()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('homepage navigation and mobile menu remain usable', async ({ page }, testInfo) => {
  const raceDate = new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
  const venue = `一覧画面${randomBytes(4).toString('hex')}`; const raceName = `一覧導線${randomBytes(4).toString('hex')}`;
  await db.race.create({ data: { raceDate, venue, number: 1, name: raceName, startsAt: new Date(`${raceDate}T23:00:00+09:00`) } });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '対象レース', exact: true })).toBeVisible();
  const menu = page.getByRole('button', { name: 'メニューを開く' });
  if (await menu.isVisible()) {
    await expect(page.locator('.sidebar')).toBeHidden();
    await menu.focus(); await page.keyboard.press('Enter');
    await expect(page.getByRole('navigation')).toBeVisible();
    await page.getByRole('navigation').getByRole('link', { name: 'マイページ' }).click();
    await expect(page.locator('.sidebar')).toBeHidden();
  }
  else await page.getByRole('navigation').getByRole('link', { name: 'マイページ' }).click();
  await expect(page.getByRole('heading', { name: 'ログインが必要です' })).toBeVisible();
  await page.goto('/');
  await page.screenshot({ path: testInfo.outputPath('home.png'), fullPage: true });
  await page.goto('/races');
  await expect(page.getByRole('heading', { name: 'レース一覧', exact: true })).toBeVisible();
  await page.getByLabel('競馬場', { exact: true }).selectOption(venue);
  await expect(page.getByRole('heading', { name: raceName, exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/plans');
  await expect(page.getByRole('heading', { name: '料金プラン', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '通常会員', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: /ログインして申し込む/ }).first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('free member can confirm account closure and cannot sign in again', async ({ page }) => {
  const fixture = await account();
  await page.goto('/login');
  await page.getByLabel('メールアドレス', { exact: true }).fill(fixture.user.email);
  await page.getByLabel('パスワード', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'ログイン', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'マイページ', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '退会条件を確認' }).click();
  await page.getByLabel('退会理由').selectOption('OTHER');
  await page.getByLabel('現在のパスワード').fill(fixture.password);
  await page.getByLabel('確認のため「退会する」と入力').fill('退会する');
  await page.getByRole('button', { name: '退会して利用を停止' }).click();
  await expect(page.getByText('退会手続きが完了し、すべての端末からログアウトしました。')).toBeVisible();
  await page.getByLabel('メールアドレス', { exact: true }).fill(fixture.user.email);
  await page.getByLabel('パスワード', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'ログイン', exact: true }).click();
  await expect(page.getByText('メールアドレスまたはパスワードを確認してください。', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
