import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { assessmentFixture } from '../assessment-fixtures';
import { db } from '../helpers';
test.afterAll(() => db.$disconnect());
test('paddock drafts survive offline edits, synchronize, and require explicit conflict resolution', async ({ page, context }, testInfo) => {
  const fixture = await assessmentFixture();
  await context.addCookies([{ name: 'keiba_session', value: fixture.token, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert'); await page.getByRole('button', { name: '評価を入力' }).click();
  await expect(page.getByRole('heading', { name: fixture.race.name, exact: true })).toBeVisible();
  await page.getByRole('button', { name: '事前評価', exact: true }).click();
  await page.getByLabel('事前点数', { exact: true }).fill('85');
  await page.getByLabel('事前順位', { exact: true }).fill('1');
  await page.getByLabel('事前印', { exact: true }).selectOption('HONMEI');
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  await page.getByRole('button', { name: 'パドック評価', exact: true }).click();
  await context.setOffline(true);
  for (const label of ['馬体の張り', '歩様・踏み込み', '毛艶', '気合・集中力', '発汗・落ち着き']) await page.getByRole('button', { name: `${label} 判断不能`, exact: true }).click();
  await page.getByRole('button', { name: '判断不能', exact: true }).click();
  await page.getByLabel('パドック短評', { exact: true }).fill('通信切断中の評価を保持');
  await expect(page.locator('.assessment-progress')).toContainText('パドック入力 1 / 2頭');
  await expect(page.locator('.assessment-progress [role=status]')).toContainText('未送信');
  const local = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '{}'), `keiba:assessment:${fixture.owner.user.id}:${fixture.race.id}`);
  expect(local[fixture.entries[0].id].content.paddockComment).toBe('通信切断中の評価を保持');
  await context.setOffline(false);
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  await page.reload(); await page.getByRole('button', { name: '評価を入力' }).click();
  await expect(page.getByLabel('パドック短評', { exact: true })).toHaveValue('通信切断中の評価を保持');
  const saved = await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[0].id } });
  const changed = { ...(saved.content as Record<string, unknown>), body: 5, paddockComment: '別端末で変更した評価' };
  const path = `expert/races/${fixture.race.id}/entries/${fixture.entries[0].id}/assessment`;
  expect((await fixture.client.call(path, 'POST', { content: changed, revision: saved.revision, horseId: fixture.entries[0].horseId, raceRevision: 1, mutationId: randomUUID(), reason: '別端末の編集試験' })).status).toBe(201);
  await page.getByRole('button', { name: '馬体の張り 4', exact: true }).click();
  await expect(page.getByRole('heading', { name: '競合する入力の確認' })).toBeVisible();
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('競合');
  await page.getByRole('button', { name: '比較した端末の入力を再送' }).click();
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  expect((await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[0].id } })).revision).toBe(saved.revision + 2);
  await page.getByRole('button', { name: '入力状況を確認' }).click();
  await expect(page.getByText('未入力または未送信があります。', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '次の馬', exact: true }).click();
  await expect(page.getByRole('heading', { name: '2番 評価試験馬2' })).toBeVisible();
  await page.getByRole('button', { name: '前の馬', exact: true }).click();
  await page.getByRole('button', { name: 'この馬の変更履歴' }).click();
  await expect(page.getByRole('heading', { name: '評価の変更履歴' })).toBeVisible();
  expect(await page.getByRole('button', { name: '馬体の張り 4', exact: true }).evaluate(e => e.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('assessment.png'), fullPage: true });
});
