import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { blankAssessment } from '../../packages/domain/src';
import { assessmentFixture } from '../assessment-fixtures';
import { db } from '../helpers';
test.afterAll(() => db.$disconnect());
test('keeps Japanese IME composition active until the paddock comment is converted', async ({ page, context }) => {
  const fixture = await assessmentFixture();
  await context.addCookies([{ name: 'keiba_session', value: fixture.token, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert'); await page.getByRole('button', { name: '評価・予想を入力' }).click();
  const comment = page.getByLabel('パドック短評', { exact: true });
  await comment.evaluate(element => {
    element.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true, data: 'に' }));
    const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value')?.set;
    setter?.call(element, 'にほん');
    element.dispatchEvent(new InputEvent('input', { bubbles: true, data: 'にほん', inputType: 'insertCompositionText', isComposing: true }));
  });
  await page.waitForTimeout(900);
  await expect(comment).toBeEnabled();
  await expect(comment).toHaveValue('にほん');
  expect(await db.assessment.findUnique({ where: { entryId: fixture.entries[0].id } })).toBeNull();
  await comment.evaluate(element => {
    const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value')?.set;
    setter?.call(element, '日本');
    element.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true, data: '日本' }));
  });
  await expect(comment).toHaveValue('日本');
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  expect((await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[0].id } })).content).toMatchObject({ paddockComment: '日本' });
});
test('completes the current horse and advances to the next incomplete horse without filling observations automatically', async ({ page, context }) => {
  const fixture = await assessmentFixture('EXPERT', 2, 3);
  await db.assessment.create({ data: { entryId: fixture.entries[1].id, revision: 1, updatedBy: fixture.owner.user.id, content: { ...blankAssessment, body: 3, walk: 3, coat: 3, focus: 3, sweating: 3, calmness: 3, change: 'SAME' } } });
  await context.addCookies([{ name: 'keiba_session', value: fixture.token, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert'); await page.getByRole('button', { name: '評価・予想を入力' }).click();
  await expect(page.getByRole('button', { name: '据え置きで完了→次', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '6項目を3に設定', exact: true }).click();
  await page.getByRole('button', { name: '据え置きで完了→次', exact: true }).click();
  await expect(page.getByRole('heading', { name: '3番 評価試験馬3' })).toBeVisible();
  await expect(page.getByText('3番の未入力馬へ移動しました。', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '6項目を3に設定', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await page.getByRole('button', { name: '6項目を4に設定', exact: true }).click();
  await page.getByRole('button', { name: 'UPで完了→次', exact: true }).click();
  await expect(page.getByText('全頭のパドック評価を入力しました。保存済みを確認して最終評価へ進んでください。', { exact: true })).toBeVisible();
  await expect(page.locator('.assessment-progress')).toContainText('パドック入力 3 / 3頭');
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  expect((await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[0].id } })).content).toMatchObject({ body: 3, change: 'SAME' });
  expect((await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[2].id } })).content).toMatchObject({ body: 4, change: 'UP' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('paddock drafts survive offline edits, synchronize, and require explicit conflict resolution', async ({ page, context }, testInfo) => {
  const fixture = await assessmentFixture();
  await context.addCookies([{ name: 'keiba_session', value: fixture.token, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert'); await page.getByRole('button', { name: '評価・予想を入力' }).click();
  await expect(page.getByRole('heading', { name: fixture.race.name, exact: true })).toBeVisible();
  await page.getByRole('button', { name: '事前評価', exact: true }).click();
  await page.getByLabel('事前点数', { exact: true }).fill('85');
  await page.getByLabel('事前順位', { exact: true }).fill('1');
  await page.getByLabel('事前印', { exact: true }).selectOption('HONMEI');
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  await page.getByRole('button', { name: 'パドック評価', exact: true }).click();
  await context.setOffline(true);
  await page.getByRole('button', { name: '6項目を判断不能に設定', exact: true }).click();
  await expect(page.getByRole('button', { name: '6項目を判断不能に設定', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: '発汗 判断不能', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: '落ち着き 判断不能', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '判断不能', exact: true }).click();
  await page.getByLabel('パドック短評', { exact: true }).fill('通信切断中の評価を保持');
  await expect(page.locator('.assessment-progress')).toContainText('パドック入力 1 / 2頭');
  await expect(page.locator('.assessment-progress [role=status]')).toContainText('未送信');
  await expect(page.getByRole('button', { name: '最終評価・公開へ', exact: true })).toBeDisabled();
  await expect(page.getByText('未送信のパドック評価があります。保存済みになってから最終評価・公開へ進んでください。', { exact: true })).toBeVisible();
  const local = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? '{}'), `keiba:assessment:${fixture.owner.user.id}:${fixture.race.id}`);
  expect(local.version).toBe(1);
  expect(new Date(local.expiresAt).getTime() - new Date(local.updatedAt).getTime()).toBe(24 * 60 * 60 * 1000);
  expect(local.drafts[fixture.entries[0].id].content.paddockComment).toBe('通信切断中の評価を保持');
  expect(local.drafts[fixture.entries[0].id].content).toMatchObject({ calm: null, sweating: 0, calmness: 0 });
  await context.setOffline(false);
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  await expect(page.getByRole('button', { name: '最終評価・公開へ', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '最終評価・公開へ', exact: true }).click();
  await expect(page.locator('.prediction-editor')).toContainText('通信切断中の評価を保持');
  await page.getByRole('button', { name: '評価入力に戻る', exact: true }).click();
  expect(await page.evaluate(key => localStorage.getItem(key), `keiba:assessment:${fixture.owner.user.id}:${fixture.race.id}`)).toBeNull();
  await page.reload(); await page.getByRole('button', { name: '評価・予想を入力' }).click();
  await expect(page.getByLabel('パドック短評', { exact: true })).toHaveValue('通信切断中の評価を保持');
  await expect(page.getByRole('button', { name: '発汗 判断不能', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: '落ち着き 判断不能', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const saved = await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[0].id } });
  const changed = { ...(saved.content as Record<string, unknown>), body: 5, paddockComment: '別端末で変更した評価' };
  const path = `expert/races/${fixture.race.id}/entries/${fixture.entries[0].id}/assessment`;
  expect((await fixture.client.call(path, 'POST', { content: changed, revision: saved.revision, horseId: fixture.entries[0].horseId, raceRevision: 1, mutationId: randomUUID(), reason: '別端末の編集試験' })).status).toBe(201);
  await page.getByRole('button', { name: '馬体の張り 4', exact: true }).click();
  await expect(page.getByRole('heading', { name: '競合する入力の確認' })).toBeVisible();
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('競合');
  await expect(page.getByRole('button', { name: '最終評価・公開へ', exact: true })).toBeDisabled();
  await expect(page.getByText('パドック評価が競合しています。内容を比較して解決し、保存済みを確認してください。', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '比較した端末の入力を再送' }).click();
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  await expect(page.getByRole('button', { name: '最終評価・公開へ', exact: true })).toBeEnabled();
  expect((await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[0].id } })).revision).toBe(saved.revision + 2);
  await page.getByRole('button', { name: '入力状況を確認' }).click();
  await expect(page.getByText('未入力または未送信があります。', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '次の馬', exact: true }).click();
  await expect(page.getByRole('heading', { name: '2番 評価試験馬2' })).toBeVisible();
  await expect(page.getByRole('button', { name: '6項目を判断不能に設定', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await page.getByRole('button', { name: '前の馬', exact: true }).click();
  await page.getByRole('button', { name: 'この馬の変更履歴' }).click();
  await expect(page.getByRole('heading', { name: '評価の変更履歴' })).toBeVisible();
  expect(await page.getByRole('button', { name: '馬体の張り 4', exact: true }).evaluate(e => e.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('assessment.png'), fullPage: true });
});
test('race operator can open an unassigned race after AAL2 without mobile overflow', async ({ page, context }) => {
  const target = await assessmentFixture(); const operator = await assessmentFixture('OPERATOR');
  await context.addCookies([{ name: 'keiba_session', value: operator.token, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto(`/expert?race=${target.race.id}`);
  await expect(page.getByRole('heading', { name: target.race.name, exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '事前評価', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('historical combined condition stays visible until sweating and calmness are explicitly separated', async ({ page, context }) => {
  const fixture = await assessmentFixture();
  const legacyContent = { preScore: null, preRank: null, preMark: null, preComment: '', body: 3, walk: 3, coat: 3, focus: 3, calm: 4, change: 'SAME', paddockComment: '旧形式の評価' };
  await db.assessment.create({ data: { entryId: fixture.entries[0].id, revision: 1, updatedBy: fixture.owner.user.id, content: legacyContent } });
  await context.addCookies([{ name: 'keiba_session', value: fixture.token, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert'); await page.getByRole('button', { name: '評価・予想を入力' }).click();
  await expect(page.getByText('旧形式の「発汗・落ち着き」評価（4）で保存済みです。', { exact: false })).toBeVisible();
  await expect(page.locator('.assessment-progress')).toContainText('パドック入力 1 / 2頭');
  await expect(page.getByRole('button', { name: '発汗 4', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await expect(page.getByRole('button', { name: '落ち着き 4', exact: true })).toHaveAttribute('aria-pressed', 'false');
  await page.getByRole('button', { name: '発汗 4', exact: true }).click();
  await expect(page.locator('.assessment-progress')).toContainText('パドック入力 0 / 2頭');
  await page.getByRole('button', { name: '落ち着き 3', exact: true }).click();
  await expect(page.locator('.assessment-progress')).toContainText('パドック入力 1 / 2頭');
  await expect(page.locator('.assessment-progress [role=status]')).toHaveText('保存済み');
  expect((await db.assessment.findUniqueOrThrow({ where: { entryId: fixture.entries[0].id } })).content).toMatchObject({ calm: null, sweating: 4, calmness: 3 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('expired paddock drafts are removed and active drafts can be explicitly cleared', async ({ page, context }) => {
  const fixture = await assessmentFixture(); const storageKey = `keiba:assessment:${fixture.owner.user.id}:${fixture.race.id}`;
  await context.addCookies([{ name: 'keiba_session', value: fixture.token, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert');
  await page.evaluate(({ key, entryId, horseId, content }) => {
    const draft = { content, revision: 0, raceRevision: 1, horseId, mutationId: crypto.randomUUID(), reason: '期限切れ試験' };
    localStorage.setItem(key, JSON.stringify({ version: 1, updatedAt: '2026-10-05T00:00:00.000Z', expiresAt: '2026-10-06T00:00:00.000Z', drafts: { [entryId]: draft } }));
  }, { key: storageKey, entryId: fixture.entries[0].id, horseId: fixture.entries[0].horseId, content: blankAssessment });
  await page.getByRole('button', { name: '評価・予想を入力' }).click();
  await expect(page.getByText('24時間を過ぎた未送信の評価は、この端末から消去しました。', { exact: true })).toBeVisible();
  expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBeNull();
  await context.setOffline(true);
  await page.getByRole('button', { name: '馬体の張り 4', exact: true }).click();
  await expect(page.getByRole('button', { name: 'この端末の未送信評価を消去', exact: true })).toBeVisible();
  expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).not.toBeNull();
  await page.getByRole('button', { name: 'この端末の未送信評価を消去', exact: true }).click();
  await expect(page.getByText('この端末の未送信評価を消去しました。', { exact: true })).toBeVisible();
  expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBeNull();
  await context.setOffline(false);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
