import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { assessmentFixture } from '../assessment-fixtures';
import { db } from '../helpers';

test.afterAll(() => db.$disconnect());
test('imports and reviews a normal paper, publishes to registered members, and preserves corrected versions', async ({ page, context }, testInfo) => {
  const member = await assessmentFixture('MEMBER'); const admin = await assessmentFixture('ADMIN', 2, 5);
  const targetDate = new Date(Date.UTC(2139, 0, 1) + (parseInt(randomUUID().slice(0, 8), 16) % 10000) * 86400000).toISOString().slice(0, 10);
  await db.race.update({ where: { id: admin.race.id }, data: { venue: '東京', number: 9, name: '八ヶ岳特別', raceDate: targetDate, startsAt: new Date(`${targetDate}T06:00:00Z`) } });
  const cookie = (value: string) => ({ name: 'keiba_session', value, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' as const });
  await context.addCookies([cookie(admin.token)]);
  await page.goto('/admin/papers');
  await expect(page.getByRole('heading', { name: '通常レース紙面を作成', exact: true })).toBeVisible();
  await page.getByLabel('対象日', { exact: true }).fill(targetDate);
  const title = `紙面画面試験 ${randomUUID().slice(0, 8)}`;
  await page.getByLabel('紙面タイトル').fill(title);
  await page.getByLabel('紙面原稿').fill('東京\n９Ｒ 八ヶ岳特別\n◎１・評価試験馬1\n○２・評価試験馬2\n△３・評価試験馬3\n△４・評価試験馬4\n✕５・評価試験馬5');
  await page.getByRole('button', { name: '原稿を読み取り・照合' }).click();
  await expect(page.getByText('原稿と登録済みレース・出走馬が一致しました。内容を確認して下書きを保存してください。')).toBeVisible();
  await expect(page.locator('.paper-marks li')).toHaveCount(5);
  await page.getByLabel('保存理由').fill('配信原稿を登録');
  await page.getByRole('button', { name: '紙面の下書きを保存' }).click();
  await expect(page.getByText('下書きを保存しました。続いて公開前確認へ進んでください。')).toBeVisible();
  await page.getByRole('button', { name: '紙面の公開内容を確認' }).click();
  await expect(page.getByRole('heading', { name: '第1版の公開確認' })).toBeVisible();
  await expect(page.locator('.paper-notice')).toContainText('/papers/');
  await expect(page.locator('.paper-notice')).not.toContainText('評価試験馬');
  expect(await db.racePaperVersion.count({ where: { title } })).toBe(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '紙面を公開する', exact: true }).click();
  await expect(page.getByText('紙面を会員ページへ公開し、公開通知を登録しました。配送可否はサービス設定で決まります。')).toBeVisible();
  const published = await db.racePaperVersion.findFirstOrThrow({ where: { title } });
  expect(await db.notificationEvent.count({ where: { paperVersionId: published.id } })).toBe(1);
  await page.getByLabel('総評（任意）').fill('訂正版の総評です。');
  await expect(page.getByRole('button', { name: '紙面の公開内容を確認' })).toHaveCount(0);
  await page.getByRole('button', { name: '原稿を読み取り・照合' }).click();
  await expect(page.getByRole('button', { name: '紙面の公開内容を確認' })).toBeDisabled();
  await page.getByLabel('保存理由').fill('総評の訂正原稿');
  await page.getByRole('button', { name: '紙面の下書きを保存' }).click();
  await expect(page.getByText('下書きを保存しました。続いて公開前確認へ進んでください。')).toBeVisible();
  await page.getByLabel('訂正理由').fill('総評の表現を追加');
  await page.getByRole('button', { name: '紙面の公開内容を確認' }).click();
  await expect(page.getByRole('heading', { name: '第2版の公開確認' })).toBeVisible();
  await page.getByRole('button', { name: '紙面の訂正版を公開する' }).click();
  await expect(page.getByText('紙面を会員ページへ公開し、公開通知を登録しました。配送可否はサービス設定で決まります。')).toBeVisible();
  await context.clearCookies(); await page.goto(`/papers/${published.paperId}`);
  await expect(page.getByRole('heading', { name: 'ログインが必要です' })).toBeVisible();
  await expect(page.locator('.paper-marks li')).toHaveCount(0);
  await context.addCookies([cookie(member.token)]); await page.reload();
  await expect(page.getByText('訂正版の総評です。', { exact: true })).toBeVisible();
  await expect(page.getByText('訂正理由：総評の表現を追加')).toBeVisible();
  await expect(page.locator('.paper-marks li')).toHaveCount(5);
  await expect(page.locator('.paper-marks li').last()).toHaveText('✕5・評価試験馬5');
  await page.getByRole('button', { name: '第1版', exact: true }).click();
  await expect(page.getByText('訂正版の総評です。', { exact: true })).toHaveCount(0);
  await expect(page.locator('.paper-marks li')).toHaveCount(5);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('regular-race-paper.png'), fullPage: true });
  await page.goto('/notifications');
  const notice = page.locator('article').filter({ hasText: '通常レース紙面を公開しました' }).filter({ hasText: title });
  await expect(notice).toBeVisible();
  await notice.getByRole('button', { name: '詳細を見る' }).click();
  await expect(page).toHaveURL(`/papers/${published.paperId}`);
  await expect(page.getByText('訂正版の総評です。', { exact: true })).toBeVisible();
  await page.goto('/admin/papers');
  await expect(page.getByRole('heading', { name: '閲覧権限がありません' })).toBeVisible();
});
