import { test, expect } from '@playwright/test';
import { createHash, randomUUID } from 'node:crypto';
import { account, Client, db } from '../helpers';
import { entryHeaders, raceHeaders } from '../../packages/domain/src/races';
test.afterAll(() => db.$disconnect());
test('register a race, import entries with preview, and see it as the assigned expert', async ({ page }, testInfo) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const expert = await account('EXPERT');
  let day = `2097-01-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: '東京' } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  const client = new Client(); await client.login(admin); await client.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/admin/races');
  await expect(page.getByRole('heading', { name: 'レース管理', exact: true })).toBeVisible();
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('button', { name: 'レースを追加' }).click();
  const form = page.locator('form').filter({ has: page.getByRole('button', { name: 'レースを保存' }) });
  const name = `画面検証レース-${randomUUID().slice(0, 6)}`;
  await form.getByLabel('レース名', { exact: true }).fill(name);
  await form.getByLabel('クラス', { exact: true }).fill('3歳未勝利');
  await form.getByLabel('担当専門家', { exact: true }).selectOption(expert.user.id);
  await form.getByLabel('レースの登録・変更理由', { exact: true }).fill('ブラウザ試験の作成');
  await form.getByRole('button', { name: 'レースを保存' }).click();
  await expect(page.getByRole('status')).toContainText('レース情報を保存しました。');
  const announcement = page.locator('.announcement-quick-row').filter({ hasText: name });
  await announcement.getByLabel(`${name}の告知理由`).fill('スマートフォン告知の画面試験');
  await announcement.getByRole('button', { name: '配信内容を確認' }).click();
  await expect(announcement.getByRole('heading', { name: '配信前確認' })).toBeVisible();
  await expect(announcement.getByText('送信本文')).toBeVisible();
  await announcement.getByRole('button', { name: 'この内容で告知する' }).click();
  await expect(page.getByRole('status')).toContainText('告知しました');
  const createdRace = await db.race.findFirstOrThrow({ where: { name } });
  expect(await db.raceAnnouncement.count({ where: { raceId: createdRace.id } })).toBe(1);
  const entryForm = page.locator('form').filter({ has: page.getByRole('button', { name: '出走馬を保存' }) });
  await entryForm.getByLabel('馬名', { exact: true }).fill('手動登録の試験馬');
  await entryForm.getByLabel('騎手', { exact: true }).fill('試験騎手');
  await entryForm.getByLabel('調教師', { exact: true }).fill('試験調教師');
  await entryForm.getByLabel('出走馬の登録・変更理由', { exact: true }).fill('手動登録試験');
  await entryForm.getByRole('button', { name: '出走馬を保存' }).click();
  await expect(page.getByRole('cell', { name: '手動登録の試験馬', exact: true })).toBeVisible();
  const horseId = randomUUID();
  const csv = `${entryHeaders.join(',')}\n${horseId},2,2,CSV登録の試験馬,FEMALE,3,55,CSV騎手,CSV調教師,4.2,2,ACTIVE`;
  await page.getByLabel('CSVファイル', { exact: true }).setInputFiles({ name: 'entries.csv', mimeType: 'text/csv', buffer: Buffer.from(csv, 'utf8') });
  await page.getByRole('button', { name: '差分を確認', exact: true }).click();
  await expect(page.getByRole('heading', { name: '取込前の確認', exact: true })).toBeVisible();
  expect(await db.raceEntry.count({ where: { horseId } })).toBe(0);
  await page.getByLabel('CSV取込の理由').fill('プレビュー後の取込試験');
  await page.getByRole('button', { name: '内容を確認して取り込む' }).click();
  await expect(page.getByRole('cell', { name: 'CSV登録の試験馬', exact: true })).toBeVisible();
  await page.getByLabel('CSVの内容', { exact: true }).fill(csv.replace('CSV騎手', '変更後の騎手'));
  await page.getByRole('button', { name: '差分を確認', exact: true }).click();
  await expect(page.getByRole('cell', { name: '変更後の騎手', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '内容を確認して取り込む' }).click();
  await expect(page.locator('.import-preview')).toHaveCount(0);
  const updated = await db.raceEntry.findFirstOrThrow({ where: { horseId } }); expect(updated.jockey).toBe('変更後の騎手');
  expect(await db.raceEntry.count({ where: { raceId: updated.raceId } })).toBe(2);
  await page.screenshot({ path: testInfo.outputPath('race-management.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const expertClient = new Client(); await expertClient.login(expert); await expertClient.mfa();
  await page.context().clearCookies();
  await page.context().addCookies([{ name: 'keiba_session', value: expertClient.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert');
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  expect((await page.request.get('/api/v1/admin/races')).status()).toBe(403);
});

test('selects a verified JRA-VAN bundle and confirms the whole race day', async ({ page }) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const client = new Client(); await client.login(admin); await client.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  let day = `2096-02-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: '東京' } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  const horseId = randomUUID();
  const race = [day, '東京', '9', '一括取込画面試験', '3勝クラス', '1600', 'TURF', 'LEFT', `${day}T15:00:00+09:00`, 'GOOD', '晴', 'SCHEDULED', ''].join(',');
  const racesCsv = `${raceHeaders.join(',')}\n${race}`;
  const entriesCsv = `${entryHeaders.join(',')}\n${horseId},1,1,一括取込試験馬,MALE,3,57,試験騎手,試験調教師,,,ACTIVE`;
  const checksum = (value: string) => createHash('sha256').update(value).digest('hex'), entryPath = `entries/${day}-05-09R.csv`;
  const manifest = JSON.stringify({ formatVersion: 'UMAREAL_JRA_VAN_BUNDLE_V1', targetDate: day, raceCount: 1, entryRaceCount: 1, entryCount: 1, finalizedRaceCount: 0, resultsIncluded: false, source: { raRecordCount: 1, raSha256: 'a'.repeat(64), seRecordCount: 1, seSha256: 'b'.repeat(64) }, files: [{ kind: 'RACES', path: 'races.csv', rowCount: 1, sha256: checksum(racesCsv) }, { kind: 'ENTRIES', path: entryPath, rowCount: 1, sha256: checksum(entriesCsv) }] });
  await page.goto('/admin/races');
  await page.getByLabel('JRA-VAN manifest').setInputFiles({ name: 'manifest.json', mimeType: 'application/json', buffer: Buffer.from(manifest) });
  await page.getByLabel('JRA-VANレースCSV').setInputFiles({ name: 'races.csv', mimeType: 'text/csv', buffer: Buffer.from(racesCsv) });
  await page.getByLabel('JRA-VAN出走馬CSV').setInputFiles({ name: `${day}-05-09R.csv`, mimeType: 'text/csv', buffer: Buffer.from(entriesCsv) });
  await expect(page.getByText('1ファイル選択済み')).toBeVisible();
  await page.getByRole('button', { name: '一括差分を確認' }).click();
  await expect(page.getByRole('heading', { name: '一括取込前の確認' })).toBeVisible();
  expect(await db.race.count({ where: { raceDate: day, venue: '東京', number: 9 } })).toBe(0);
  await page.getByLabel('開催日一括取込の理由').fill('画面から開催日一括取込');
  await page.getByRole('button', { name: '確認した開催日データを取り込む' }).click();
  await expect(page.getByRole('status')).toContainText('1レース・1頭を取り込みました');
  const imported = await db.race.findUniqueOrThrow({ where: { raceDate_venue_number: { raceDate: day, venue: '東京', number: 9 } }, include: { entries: true } });
  expect(imported.entries[0]).toMatchObject({ horseId, horseName: '一括取込試験馬' });
});
