import { test, expect } from '@playwright/test';
import { createHash, randomUUID } from 'node:crypto';
import { account, Client, db } from '../helpers';
import { entryHeaders, raceHeaders } from '../../packages/domain/src/races';
test.afterAll(() => db.$disconnect());
test('register a race, import entries with preview, and see it as the assigned expert', async ({ page }, testInfo) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const expert = await account('EXPERT');
  expert.user = await db.user.update({ where: { id: expert.user.id }, data: { displayName: `画面検証担当-${randomUUID().slice(0, 8)}` } });
  let day = `2097-01-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: '東京' } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  const client = new Client(); await client.login(admin); await client.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/admin/races');
  await expect(page.getByRole('heading', { name: 'レース管理', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'データ取得方式', exact: true })).toBeVisible();
  await expect(page.getByText('手動運用', { exact: true })).toBeVisible();
  await expect(page.getByText('外部データ連携は使用していません。', { exact: false })).toBeVisible();
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('button', { name: 'レースを追加' }).click();
  const form = page.locator('form').filter({ has: page.getByRole('button', { name: 'レースを保存' }) });
  const name = `画面検証レース-${randomUUID().slice(0, 6)}`;
  await form.getByLabel('レース名', { exact: true }).fill(name);
  await form.getByLabel('クラス', { exact: true }).fill('3歳未勝利');
  await form.getByLabel('レースの登録・変更理由', { exact: true }).fill('ブラウザ試験の作成');
  const raceDraftKey = `keiba:race-manager:${admin.user.id}:race-detail:new-${day}`;
  await expect.poll(() => page.evaluate(key => sessionStorage.getItem(key), raceDraftKey)).toContain(name);
  await page.reload();
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('button', { name: 'レースを追加' }).click();
  const restoredForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'レースを保存' }) });
  await expect(restoredForm.getByText('未送信のレース詳細を復元しました。', { exact: false })).toBeVisible();
  await expect(restoredForm.getByLabel('レース名', { exact: true })).toHaveValue(name);
  await expect(restoredForm.getByLabel('クラス', { exact: true })).toHaveValue('3歳未勝利');
  await expect(restoredForm.getByLabel('レースの登録・変更理由', { exact: true })).toHaveValue('ブラウザ試験の作成');
  await restoredForm.getByRole('button', { name: '詳細下書きを破棄', exact: true }).click();
  await expect(restoredForm.getByLabel('レース名', { exact: true })).toHaveValue('');
  expect(await page.evaluate(key => sessionStorage.getItem(key), raceDraftKey)).toBeNull();
  await restoredForm.getByLabel('レース名', { exact: true }).fill(name);
  await restoredForm.getByLabel('クラス', { exact: true }).fill('3歳未勝利');
  await restoredForm.getByLabel('レースの登録・変更理由', { exact: true }).fill('ブラウザ試験の作成');
  await restoredForm.getByLabel('予想担当者名', { exact: true }).fill(expert.user.displayName);
  await restoredForm.getByRole('button', { name: '検索', exact: true }).click();
  await expect(restoredForm.getByText('1件見つかりました', { exact: true })).toBeVisible();
  await restoredForm.getByLabel('予想担当', { exact: true }).selectOption(expert.user.id);
  await restoredForm.getByRole('button', { name: 'レースを保存' }).click();
  await expect(page.getByRole('status')).toContainText('レース情報を保存しました。');
  expect(await page.evaluate(key => sessionStorage.getItem(key), raceDraftKey)).toBeNull();
  const announcement = page.locator('.announcement-quick-row').filter({ hasText: name });
  await announcement.getByLabel(`${name}の告知理由`).fill('スマートフォン告知の画面試験');
  await announcement.getByRole('button', { name: '配信内容を確認' }).click();
  await expect(announcement.getByRole('heading', { name: '配信前確認' })).toBeVisible();
  await expect(announcement.getByText('送信本文')).toBeVisible();
  await announcement.getByRole('button', { name: 'この内容で告知する' }).click();
  await expect(page.getByRole('status')).toContainText('告知しました');
  const createdRace = await db.race.findFirstOrThrow({ where: { name } });
  expect(await db.raceAnnouncement.count({ where: { raceId: createdRace.id } })).toBe(1);
  const quickEntryForm = page.locator('form').filter({ has: page.getByRole('button', { name: '出走馬を簡易登録' }) });
  await quickEntryForm.getByLabel('馬名', { exact: true }).fill('簡易登録の試験馬');
  await quickEntryForm.getByLabel('簡易登録の理由', { exact: true }).fill('馬番と馬名のみで登録');
  await quickEntryForm.getByRole('button', { name: '出走馬を簡易登録' }).click();
  await expect(page.getByRole('cell', { name: '簡易登録の試験馬', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: '未確認', exact: true }).first()).toBeVisible();
  let entryForm = page.locator('form').filter({ has: page.getByRole('button', { name: '出走馬を保存' }) });
  await expect(entryForm.getByLabel('馬ID', { exact: true })).toHaveCount(0);
  await expect(entryForm.locator('input[name="horseId"][type="hidden"]')).toHaveCount(1);
  await entryForm.getByLabel('馬名', { exact: true }).fill('手動登録の試験馬');
  await entryForm.getByLabel('騎手', { exact: true }).fill('試験騎手');
  await entryForm.getByLabel('調教師', { exact: true }).fill('試験調教師');
  await entryForm.getByLabel('出走馬の登録・変更理由', { exact: true }).fill('手動登録試験');
  const entryDraftKey = `keiba:race-manager:${admin.user.id}:entry-detail:${createdRace.id}:new`;
  await expect.poll(() => page.evaluate(key => sessionStorage.getItem(key), entryDraftKey)).toContain('手動登録の試験馬');
  await page.reload();
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('row').filter({ hasText: name }).getByRole('button', { name: '編集・出走馬' }).click();
  entryForm = page.locator('form').filter({ has: page.getByRole('button', { name: '出走馬を保存' }) });
  await expect(entryForm.getByText('未送信の出走馬詳細を復元しました。', { exact: false })).toBeVisible();
  await expect(entryForm.getByLabel('馬名', { exact: true })).toHaveValue('手動登録の試験馬');
  await expect(entryForm.getByLabel('騎手', { exact: true })).toHaveValue('試験騎手');
  await expect(entryForm.getByLabel('調教師', { exact: true })).toHaveValue('試験調教師');
  await entryForm.getByRole('button', { name: '出走馬を保存' }).click();
  await expect(page.getByRole('cell', { name: '手動登録の試験馬', exact: true })).toBeVisible();
  expect(await page.evaluate(key => sessionStorage.getItem(key), entryDraftKey)).toBeNull();
  const manuallyCreatedEntry = await db.raceEntry.findFirstOrThrow({ where: { raceId: createdRace.id, horseName: '手動登録の試験馬' } });
  expect(manuallyCreatedEntry.horseId).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);
  const horseId = randomUUID();
  const csv = `${entryHeaders.join(',')}\n${horseId},3,2,CSV登録の試験馬,FEMALE,3,55,CSV騎手,CSV調教師,4.2,2,ACTIVE`;
  await page.getByLabel('CSVファイル', { exact: true }).setInputFiles({ name: 'entries.csv', mimeType: 'text/csv', buffer: Buffer.from(csv, 'utf8') });
  await page.getByRole('button', { name: '差分を確認', exact: true }).click();
  await expect(page.getByRole('heading', { name: '取込前の確認', exact: true })).toBeVisible();
  expect(await db.raceEntry.count({ where: { horseId } })).toBe(0);
  await page.getByLabel('CSV取込の理由').fill('プレビュー後の取込試験');
  await page.getByRole('button', { name: '内容を確認して取り込む' }).click();
  await expect(page.getByRole('cell', { name: 'CSV登録の試験馬', exact: true })).toBeVisible();
  await page.getByLabel('CSVの内容', { exact: true }).fill(csv.replace('CSV騎手', '変更後の騎手'));
  await page.getByRole('button', { name: '差分を確認', exact: true }).click();
  await expect(page.getByRole('cell', { name: '変更後の騎手', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '内容を確認して取り込む' }).click();
  await expect(page.locator('.import-preview')).toHaveCount(0);
  const updated = await db.raceEntry.findFirstOrThrow({ where: { horseId } }); expect(updated.jockey).toBe('変更後の騎手');
  expect(await db.raceEntry.count({ where: { raceId: updated.raceId } })).toBe(3);
  await page.screenshot({ path: testInfo.outputPath('race-management.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const expertClient = new Client(); await expertClient.login(expert); await expertClient.mfa();
  await page.context().clearCookies();
  await page.context().addCookies([{ name: 'keiba_session', value: expertClient.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert');
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  expect((await page.request.get('/api/v1/admin/races')).status()).toBe(403);
});

test('pastes multiple races, previews them, and confirms once on mobile', async ({ page }) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const client = new Client(); await client.login(admin); await client.mfa();
  const otherAdmin = await account('ADMIN'); const otherClient = new Client(); await otherClient.login(otherAdmin); await otherClient.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.setViewportSize({ width: 390, height: 844 });
  let day = `2096-03-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: { in: ['東京', '京都'] } } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  await page.goto('/admin/races');
  await page.getByLabel('かんたん登録の開催日').fill(day);
  await page.getByLabel('かんたん登録のクラス').fill('特別競走');
  await page.getByLabel('かんたん登録のレース一覧').fill('東京\n9R 八ヶ岳特別 14:35 芝1800 左\n10R 白秋ステークス 15:10 芝1400 左\n\n京都\n10R 大山崎ステークス 15:00 ダ1200 右');
  const storageKey = `keiba:race-manager:${admin.user.id}:quick-races`;
  await expect.poll(() => page.evaluate(key => sessionStorage.getItem(key), storageKey)).not.toBeNull();
  await page.reload();
  await expect(page.getByText('この利用者の未送信下書きを復元しました。', { exact: false })).toBeVisible();
  await expect(page.getByLabel('かんたん登録のレース一覧')).toHaveValue(/八ヶ岳特別/);
  await page.getByRole('button', { name: '下書きを破棄', exact: true }).click();
  await expect(page.getByLabel('かんたん登録のレース一覧')).toHaveValue('');
  expect(await page.evaluate(key => sessionStorage.getItem(key), storageKey)).toBeNull();
  await page.getByLabel('かんたん登録の開催日').fill(day);
  await page.getByLabel('かんたん登録のクラス').fill('特別競走');
  await page.getByLabel('かんたん登録のレース一覧').fill('東京\n9R 八ヶ岳特別 14:35 芝1800 左\n10R 白秋ステークス 15:10 芝1400 左\n\n京都\n10R 大山崎ステークス 15:00 ダ1200 右');
  await expect.poll(() => page.evaluate(key => sessionStorage.getItem(key), storageKey)).not.toBeNull();
  await page.context().clearCookies();
  await page.context().addCookies([{ name: 'keiba_session', value: otherClient.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.reload();
  await expect(page.getByLabel('かんたん登録のレース一覧')).toHaveValue('');
  await expect(page.getByText('この利用者の未送信下書きを復元しました。', { exact: false })).toHaveCount(0);
  await page.context().clearCookies();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.reload();
  await expect(page.getByText('この利用者の未送信下書きを復元しました。', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: '内容を確認', exact: true }).click();
  await expect(page.getByRole('heading', { name: '登録前の確認', exact: true })).toBeVisible();
  expect(await db.race.count({ where: { raceDate: day, venue: { in: ['東京', '京都'] } } })).toBe(0);
  await page.getByLabel('かんたん一括登録の理由').fill('翌日対象レースの一括登録');
  await expect.poll(() => page.evaluate(key => sessionStorage.getItem(key), storageKey)).toContain('翌日対象レースの一括登録');
  await page.reload();
  await page.getByRole('button', { name: '内容を確認', exact: true }).click();
  await expect(page.getByLabel('かんたん一括登録の理由')).toHaveValue('翌日対象レースの一括登録');
  await page.getByRole('button', { name: '確認した内容を登録', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('3レースを登録しました。');
  expect(await db.race.count({ where: { raceDate: day, venue: { in: ['東京', '京都'] } } })).toBe(3);
  expect(await page.evaluate(key => sessionStorage.getItem(key), storageKey)).toBeNull();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('pastes and confirms an 18-horse card without entering technical IDs', async ({ page }) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const client = new Client(); await client.login(admin); await client.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.setViewportSize({ width: 390, height: 844 });
  let day = `2095-04-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: '東京' } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  const suffix = randomUUID().slice(0, 8), raceName = `18頭一括登録-${suffix}`;
  const created = await client.call('admin/races', 'POST', { race: { raceDate: day, venue: '東京', number: 12, name: raceName, raceClass: '3歳以上1勝クラス', distance: 1800, surface: 'TURF', direction: 'LEFT', startsAt: `${day}T16:30:00+09:00`, going: 'UNKNOWN', weather: '未確認', status: 'SCHEDULED', expertId: null }, reason: '18頭一括登録の画面試験' }, undefined, { 'Idempotency-Key': randomUUID() });
  expect(created.status).toBe(201);
  const horseNames = Array.from({ length: 18 }, (_, index) => `一括画面試験馬${index + 1}-${suffix}`);
  await page.goto('/admin/races');
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  const row = page.getByRole('row').filter({ hasText: raceName });
  await row.getByRole('button', { name: '編集・出走馬' }).click();
  await page.getByLabel('出走馬一括入力').fill(horseNames.map((name, index) => `${index + 1},${name}`).join('\n'));
  const storageKey = `keiba:race-manager:${admin.user.id}:quick-entries:${created.body.id}`;
  await expect.poll(() => page.evaluate(key => sessionStorage.getItem(key), storageKey)).not.toBeNull();
  await page.reload();
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('row').filter({ hasText: raceName }).getByRole('button', { name: '編集・出走馬' }).click();
  await expect(page.getByText('このレースの未送信下書きを復元しました。', { exact: false })).toBeVisible();
  await expect(page.getByLabel('出走馬一括入力')).toHaveValue(new RegExp(horseNames[17]));
  await page.getByRole('button', { name: '登録内容を確認' }).click();
  await expect(page.getByRole('heading', { name: '一括登録前の確認', exact: true })).toBeVisible();
  expect(await db.raceEntry.count({ where: { raceId: created.body.id } })).toBe(0);
  await page.getByLabel('出走馬一括登録の理由').fill('出馬表18頭を画面で確認');
  await expect.poll(() => page.evaluate(key => sessionStorage.getItem(key), storageKey)).toContain('出馬表18頭を画面で確認');
  await page.reload();
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('row').filter({ hasText: raceName }).getByRole('button', { name: '編集・出走馬' }).click();
  await page.getByRole('button', { name: '登録内容を確認' }).click();
  await expect(page.getByLabel('出走馬一括登録の理由')).toHaveValue('出馬表18頭を画面で確認');
  await page.getByRole('button', { name: '確認した18頭を一括登録' }).click();
  await expect(page.getByRole('status')).toContainText('18頭をまとめて登録しました。');
  expect(await db.raceEntry.count({ where: { raceId: created.body.id } })).toBe(18);
  expect(await db.horseExternalIdentity.count({ where: { observedName: { in: horseNames }, provider: 'MANUAL' } })).toBe(18);
  expect(await page.evaluate(key => sessionStorage.getItem(key), storageKey)).toBeNull();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('resolves and reviews a provisional horse without displaying raw UUIDs', async ({ page }) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const client = new Client(); await client.login(admin); await client.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  let day = `2094-05-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: '東京' } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  const suffix = randomUUID().slice(0, 8), raceName = `Identity表示試験-${suffix}`, horseName = `同名表示試験馬-${suffix}`;
  const existingHorse = await db.horse.create({ data: { id: randomUUID(), name: horseName } });
  const created = await client.call('admin/races', 'POST', { race: { raceDate: day, venue: '東京', number: 8, name: raceName, raceClass: '表示試験', distance: 1600, surface: 'TURF', direction: 'LEFT', startsAt: `${day}T14:00:00+09:00`, going: 'UNKNOWN', weather: '未確認', status: 'SCHEDULED', expertId: null }, reason: 'Horse UUID非表示の画面試験' }, undefined, { 'Idempotency-Key': randomUUID() });
  expect(created.status).toBe(201);
  await page.goto('/admin/races');
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('row').filter({ hasText: raceName }).getByRole('button', { name: '編集・出走馬' }).click();
  const quickEntryForm = page.locator('form').filter({ has: page.getByRole('button', { name: '出走馬を簡易登録' }) });
  await quickEntryForm.getByLabel('馬名', { exact: true }).fill(horseName);
  await quickEntryForm.getByLabel('簡易登録の理由', { exact: true }).fill('同名候補の表示を確認');
  await quickEntryForm.getByRole('button', { name: '出走馬を簡易登録' }).click();
  await expect(page.getByRole('status')).toContainText('正式IDとの統合は保留されています。');
  const identity = await db.horseExternalIdentity.findFirstOrThrow({ where: { observedName: horseName, provider: 'MANUAL' } });
  const target = page.getByLabel(`${horseName}の紐付け先`);
  await expect(target).toBeVisible();
  await expect(target.locator('option:checked')).toHaveText(`候補1 · ${horseName} · 使用レース0件`);
  expect(await page.locator('body').innerText()).not.toContain(existingHorse.id);
  expect(await page.locator('body').innerText()).not.toContain(identity.horseId!);
  await page.getByLabel(`${horseName}のIdentity確認理由`).fill('同名候補を登録履歴と照合');
  await page.getByRole('button', { name: '既存馬へ紐付け' }).click();
  await expect(page.getByText(`${horseName}を既存馬へ紐付けました。`, { exact: true })).toBeVisible();
  await page.reload();
  await page.getByText('確認済みIdentityと訂正', { exact: true }).click();
  await expect(page.getByText(`現在の紐付け: ${horseName} · 使用レース 0件`, { exact: true })).toBeVisible();
  expect(await page.locator('body').innerText()).not.toContain(existingHorse.id);
  expect(await page.locator('body').innerText()).not.toContain(identity.horseId!);
});

test('selects a verified JRA-VAN bundle and confirms the whole race day', async ({ page }) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const client = new Client(); await client.login(admin); await client.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  let day = `2096-02-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: '東京' } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  const horseId = randomUUID();
  const race = [day, '東京', '9', '一括取込画面試験', '3勝クラス', '1600', 'TURF', 'LEFT', `${day}T15:00:00+09:00`, 'GOOD', '晴', 'SCHEDULED', ''].join(',');
  const racesCsv = `${raceHeaders.join(',')}\n${race}`;
  const entriesCsv = `${entryHeaders.join(',')}\n${horseId},1,1,一括取込試験馬,MALE,3,57,試験騎手,試験調教師,,,ACTIVE`;
  const checksum = (value: string) => createHash('sha256').update(value).digest('hex'), entryPath = `entries/${day}-05-09R.csv`;
  const manifest = JSON.stringify({ formatVersion: 'UMAREAL_JRA_VAN_BUNDLE_V1', targetDate: day, raceCount: 1, entryRaceCount: 1, entryCount: 1, finalizedRaceCount: 0, resultsIncluded: false, source: { raRecordCount: 1, raSha256: 'a'.repeat(64), seRecordCount: 1, seSha256: 'b'.repeat(64) }, files: [{ kind: 'RACES', path: 'races.csv', rowCount: 1, sha256: checksum(racesCsv) }, { kind: 'ENTRIES', path: entryPath, rowCount: 1, sha256: checksum(entriesCsv) }] });
  await page.goto('/admin/races');
  await page.getByLabel('JRA-VAN manifest').setInputFiles({ name: 'manifest.json', mimeType: 'application/json', buffer: Buffer.from(manifest) });
  await page.getByLabel('JRA-VANレースCSV').setInputFiles({ name: 'races.csv', mimeType: 'text/csv', buffer: Buffer.from(racesCsv) });
  await page.getByLabel('JRA-VAN出走馬CSV').setInputFiles({ name: `${day}-05-09R.csv`, mimeType: 'text/csv', buffer: Buffer.from(entriesCsv) });
  await expect(page.getByText('1ファイル選択済み')).toBeVisible();
  await page.getByRole('button', { name: '一括差分を確認' }).click();
  await expect(page.getByRole('heading', { name: '一括取込前の確認' })).toBeVisible();
  expect(await db.race.count({ where: { raceDate: day, venue: '東京', number: 9 } })).toBe(0);
  await page.getByLabel('開催日一括取込の理由').fill('画面から開催日一括取込');
  await page.getByRole('button', { name: '確認した開催日データを取り込む' }).click();
  await expect(page.getByRole('status')).toContainText('1レース・1頭を取り込みました');
  const imported = await db.race.findUniqueOrThrow({ where: { raceDate_venue_number: { raceDate: day, venue: '東京', number: 9 } }, include: { entries: true } });
  expect(imported.entries[0]).toMatchObject({ horseId, horseName: '一括取込試験馬' });
});
