import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { account, Client, db } from '../helpers';
import { entryHeaders } from '../../packages/domain/src/races';
test.afterAll(() => db.$disconnect());
test('register a race, import entries with preview, and see it as the assigned expert', async ({ page }, testInfo) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['localhost', '127.0.0.1'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Local database required');
  const admin = await account('ADMIN'); const expert = await account('EXPERT');
  let day = `2097-01-${String(Math.floor(Math.random() * 25) + 1).padStart(2, '0')}`;
  while (await db.race.count({ where: { raceDate: day, venue: '東京' } })) day = new Date(new Date(`${day}T00:00:00Z`).getTime() + 86400000).toISOString().slice(0, 10);
  const client = new Client(); await client.login(admin); await client.mfa();
  await page.context().addCookies([{ name: 'keiba_session', value: client.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/admin/races');
  await expect(page.getByRole('heading', { name: 'レース管理', exact: true })).toBeVisible();
  await page.getByLabel('表示する開催日', { exact: true }).fill(day);
  await page.getByRole('button', { name: 'レースを追加' }).click();
  const form = page.locator('form').filter({ has: page.getByRole('button', { name: 'レースを保存' }) });
  const name = `画面検証レース-${randomUUID().slice(0, 6)}`;
  await form.getByLabel('レース名', { exact: true }).fill(name);
  await form.getByLabel('クラス', { exact: true }).fill('3歳未勝利');
  await form.getByLabel('担当専門家', { exact: true }).selectOption(expert.user.id);
  await form.getByLabel('レースの登録・変更理由', { exact: true }).fill('ブラウザ試験の作成');
  await form.getByRole('button', { name: 'レースを保存' }).click();
  await expect(page.getByRole('status')).toContainText('レース情報を保存しました。');
  const announcement = page.locator('.announcement-quick-row').filter({ hasText: name });
  await announcement.getByLabel(`${name}の告知理由`).fill('スマートフォン告知の画面試験');
  await announcement.getByRole('button', { name: '告知する' }).click();
  await expect(page.getByRole('status')).toContainText('告知しました');
  const createdRace = await db.race.findFirstOrThrow({ where: { name } });
  expect(await db.raceAnnouncement.count({ where: { raceId: createdRace.id } })).toBe(1);
  const entryForm = page.locator('form').filter({ has: page.getByRole('button', { name: '出走馬を保存' }) });
  await entryForm.getByLabel('馬名', { exact: true }).fill('手動登録の試験馬');
  await entryForm.getByLabel('騎手', { exact: true }).fill('試験騎手');
  await entryForm.getByLabel('調教師', { exact: true }).fill('試験調教師');
  await entryForm.getByLabel('出走馬の登録・変更理由', { exact: true }).fill('手動登録試験');
  await entryForm.getByRole('button', { name: '出走馬を保存' }).click();
  await expect(page.getByRole('cell', { name: '手動登録の試験馬', exact: true })).toBeVisible();
  const horseId = randomUUID();
  const csv = `${entryHeaders.join(',')}\n${horseId},2,2,CSV登録の試験馬,FEMALE,3,55,CSV騎手,CSV調教師,4.2,2,ACTIVE`;
  await page.getByLabel('CSVファイル', { exact: true }).setInputFiles({ name: 'entries.csv', mimeType: 'text/csv', buffer: Buffer.from(csv, 'utf8') });
  await page.getByRole('button', { name: '差分を確認', exact: true }).click();
  await expect(page.getByRole('heading', { name: '取込前の確認', exact: true })).toBeVisible();
  expect(await db.raceEntry.count({ where: { horseId } })).toBe(0);
  await page.getByLabel('CSV取込の理由').fill('プレビュー後の取込試験');
  await page.getByRole('button', { name: '内容を確認して取り込む' }).click();
  await expect(page.getByRole('cell', { name: 'CSV登録の試験馬', exact: true })).toBeVisible();
  await page.getByLabel('CSVの内容', { exact: true }).fill(csv.replace('CSV騎手', '変更後の騎手'));
  await page.getByRole('button', { name: '差分を確認', exact: true }).click();
  await expect(page.getByRole('cell', { name: '変更後の騎手', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '内容を確認して取り込む' }).click();
  await expect(page.locator('.import-preview')).toHaveCount(0);
  const updated = await db.raceEntry.findFirstOrThrow({ where: { horseId } }); expect(updated.jockey).toBe('変更後の騎手');
  expect(await db.raceEntry.count({ where: { raceId: updated.raceId } })).toBe(2);
  await page.screenshot({ path: testInfo.outputPath('race-management.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const expertClient = new Client(); await expertClient.login(expert); await expertClient.mfa();
  await page.context().clearCookies();
  await page.context().addCookies([{ name: 'keiba_session', value: expertClient.cookie.split('=')[1], domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
  await page.goto('/expert');
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  expect((await page.request.get('/api/v1/admin/races')).status()).toBe(403);
});
