import { test, expect } from '@playwright/test';
import { randomBytes, randomUUID } from 'node:crypto';
import { account, db, totp } from '../helpers';
test.afterAll(async () => {
  await db.systemSetting.update({ where: { id: 'global' }, data: { stripeSecretKeyEncrypted: null, stripeWebhookSecretEncrypted: null, stripeLiveMode: false, stripePriceFounder: null, stripePriceStandard: null, stripePriceDayPass: null } });
  await db.$disconnect();
});
test('operator and expert see their management entry after login', async ({ page }, testInfo) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['127.0.0.1', 'localhost'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Staff browser test requires local development database');
  const cases = [
    { fixture: await account('OPERATOR'), href: '/admin', heading: 'レース担当用の管理画面' },
    { fixture: await account('EXPERT'), href: '/expert', heading: '予想担当用の管理画面' }
  ];
  for (const item of cases) {
    await page.goto('/login');
    await page.getByLabel('メールアドレス', { exact: true }).fill(item.fixture.user.email!);
    await page.getByLabel('パスワード', { exact: true }).fill(item.fixture.password);
    await page.getByRole('button', { name: 'ログイン', exact: true }).click();
    await expect(page.getByRole('heading', { name: item.heading, exact: true })).toBeVisible();
    const managementLink = page.getByRole('link', { name: '管理画面へ', exact: true });
    await expect(managementLink).toHaveAttribute('href', item.href);
    if (testInfo.project.name.includes('mobile')) {
      await page.getByRole('button', { name: 'メニューを開く' }).click();
    }
    const menuManagementLink = page.getByRole('navigation', { name: 'メインメニュー' }).getByRole('link', { name: '管理画面', exact: true });
    await expect(menuManagementLink).toHaveAttribute('href', item.href);
    await expect(menuManagementLink).toBeVisible();
    if (testInfo.project.name.includes('mobile')) await page.locator('.close-menu').click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    if (item.fixture.user.role === 'OPERATOR') {
      await page.goto('/admin');
      await expect(page.getByRole('heading', { name: '管理ダッシュボード', exact: true })).toBeVisible();
      if (testInfo.project.name.includes('mobile')) await page.getByRole('button', { name: 'メニューを開く' }).click();
      await expect(page.getByRole('navigation', { name: '管理メニュー' }).getByRole('link', { name: '馬を評価・公開', exact: true })).toHaveAttribute('href', '/expert');
      await page.goto('/expert');
      await expect(page.getByRole('heading', { name: '二段階認証を完了してください', exact: true })).toBeVisible();
    }
    await page.getByRole('button', { name: 'ログアウト', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'おかえりなさい', exact: true })).toBeVisible();
  }
});
test('administrator must complete MFA before viewing member management', async ({ page }) => {
  if (process.env.AUTH_PROVIDER !== 'local' || !['127.0.0.1', 'localhost'].includes(new URL(process.env.DATABASE_URL ?? '').hostname)) throw new Error('Staff browser test requires local development database');
  const fixture = await account('ADMIN');
  const attributedMember = await account();
  await db.memberAcquisition.create({ data: { userId: attributedMember.user.id, source: 'staff-e2e', medium: 'browser', campaign: 'dashboard' } });
  const raceDate = new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
  const operationsRace = await db.race.create({ data: { raceDate, venue: `運用画面-${randomUUID().slice(0, 6)}`, number: 9, name: `開催日運用-${randomUUID().slice(0, 6)}`, startsAt: new Date(Date.now() + 3600000), assignments: { create: { userId: fixture.user.id } } } });
  await db.raceEntry.create({ data: { race: { connect: { id: operationsRace.id } }, horse: { create: { id: randomUUID(), name: '運用画面試験馬' } }, number: 1, gate: 1, horseName: '運用画面試験馬', sex: 'MALE', age: 3, carriedWeight: 57, jockey: '試験騎手', trainer: '試験調教師' } });
  await page.goto('/login');
  await page.getByLabel('メールアドレス', { exact: true }).fill(fixture.user.email);
  await page.getByLabel('パスワード', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'ログイン', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'マイページ', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '管理者用の管理画面', exact: true })).toBeVisible();
  const managementLink = page.getByRole('link', { name: '管理画面へ', exact: true });
  await expect(managementLink).toHaveAttribute('href', '/admin');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await managementLink.click();
  await expect(page.getByRole('heading', { name: '二段階認証を完了してください' })).toBeVisible();
  await page.getByRole('link', { name: '二段階認証へ' }).click();
  await page.getByRole('button', { name: '設定を始める' }).click();
  const secret = await page.locator('.setup-secret code').innerText();
  await page.getByLabel('認証コード').fill(totp(secret));
  await page.getByRole('button', { name: 'コードを確認' }).click();
  await expect(page.getByRole('heading', { name: '二段階認証が完了しています' })).toBeVisible();
  await page.getByRole('link', { name: '管理画面へ', exact: true }).click();
  await expect(page.getByRole('heading', { name: '管理ダッシュボード', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '開催日運用ボード', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '今すぐ確認すること', exact: true })).toBeVisible();
  await expect(page.getByLabel('今すぐ確認すること')).toContainText('対象レース未告知');
  await expect(page.getByRole('heading', { name: '開催日リハーサル', exact: true })).toBeVisible();
  const lineAvailable = await page.evaluate(async () => {
    const response = await fetch('/api/v1/auth/config');
    const config = await response.json() as { capabilities: { lineNotifications: boolean } };
    return config.capabilities.lineNotifications;
  });
  await expect(page.getByLabel('運用機能の事前確認')).toContainText('予想公開');
  await expect(page.getByLabel('運用機能の事前確認')).toContainText(lineAvailable ? 'LINE設定' : 'LINE通知（対象外）');
  await expect(page.getByText('自動更新中', { exact: true })).toBeVisible();
  await expect(page.getByText(/最終更新 .* JST/)).toBeVisible();
  const operationCard = page.locator('.operation-race').filter({ hasText: operationsRace.name });
  await expect(operationCard.getByLabel(`${operationsRace.name}のリハーサル手順`)).toContainText('レース準備');
  await expect(operationCard.getByLabel(`${operationsRace.name}のリハーサル手順`)).toContainText('結果確定');
  await expect(operationCard).toContainText('パドック未着手');
  await expect(operationCard).toContainText('最終予想未公開');
  await db.raceAnnouncement.create({ data: { raceId: operationsRace.id, version: 1, publishedBy: fixture.user.id, reason: 'ライブ更新E2E' } });
  await page.getByRole('button', { name: '今すぐ更新' }).click();
  await expect(operationCard).toContainText('公開済み v1');
  await operationCard.getByRole('link', { name: '評価・公開' }).click();
  await expect(page.getByRole('heading', { name: operationsRace.name, exact: true })).toBeVisible();
  await page.goto('/admin');
  await expect(page.getByRole('heading', { name: '会員転換ファネル', exact: true })).toBeVisible();
  await expect(page.locator('.funnel-list')).toContainText('無料登録');
  await expect(page.locator('.funnel-list')).toContainText('料金閲覧');
  await expect(page.locator('.funnel-list')).toContainText('有料化');
  await expect(page.getByRole('heading', { name: '登録流入別の有料化', exact: true })).toBeVisible();
  await expect(page.locator('.acquisition-panel')).toContainText('staff-e2e');
  const campaignCode = `browser_${randomUUID().slice(0, 8)}`;
  await page.goto('/admin/acquisition');
  await expect(page.getByRole('heading', { name: 'キャンペーン・流入管理', exact: true })).toBeVisible();
  await page.getByLabel('管理用の名前').fill('画面試験LP');
  await page.getByLabel('キャンペーンコード').fill(campaignCode);
  await page.getByLabel('コンテンツ識別（任意）').fill('hero');
  await page.getByLabel('発行理由').fill('スマートフォンを含むURL発行試験');
  await page.getByRole('button', { name: '登録URLを発行', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('登録URLを発行しました。');
  const issuedCampaign = page.locator('.campaign-row').filter({ hasText: campaignCode });
  await expect(issuedCampaign.getByLabel('画面試験LPの登録URL')).toHaveValue(new RegExp(`utm_campaign=${campaignCode}`));
  await page.getByLabel('集計期間').selectOption('90');
  await expect(page.getByRole('link', { name: 'CSV出力' })).toHaveAttribute('href', '/api/v1/admin/acquisition/export.csv?days=90');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/onboarding-funnel');
  await expect(page.getByRole('heading', { name: '無料会員 登録ファネル', exact: true })).toBeVisible();
  await page.getByLabel('集計期間').selectOption('90');
  await page.getByLabel('流入元').selectOption('staff-e2e');
  await expect(page.getByRole('heading', { name: '90日以内に登録した会員', exact: true })).toBeVisible();
  await expect(page.locator('.onboarding-funnel-list')).toContainText('初回ログイン');
  await expect(page.locator('.onboarding-funnel-list')).toContainText('LINE案内到達');
  await expect(page.locator('.onboarding-funnel-list')).toContainText('未到達');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/settings');
  await expect(page.getByRole('heading', { name: '運用・連携設定', exact: true })).toBeVisible();
  await page.getByLabel('LINE Channel ID').fill('1234567890');
  await page.getByLabel('LINE Channel secret').fill('0123456789abcdef0123456789abcdef');
  await page.getByLabel('LINE Channel access token').fill(`e2e-token-${'x'.repeat(40)}`);
  await page.getByLabel('LINE Login Channel ID').fill('9876543210');
  await page.getByLabel('LINE Login Channel secret').fill('abcdef0123456789abcdef0123456789');
  await page.getByLabel('LINE Login Callback URL').fill('https://example.test/api/v1/auth/line/callback');
  await page.getByLabel('Stripe Secret key').fill(`sk_test_${'x'.repeat(32)}`);
  await page.getByLabel('Stripe Webhook secret').fill(`whsec_${'y'.repeat(32)}`);
  await page.getByLabel('Stripe 創設会員 Price ID').fill('price_FounderE2E');
  await page.getByLabel('Stripe 通常会員 Price ID').fill('price_StandardE2E');
  await page.getByLabel('Stripe 1日利用 Price ID').fill('price_DayPassE2E');
  await page.getByLabel('Resend API key', { exact: true }).fill(`re_${'m'.repeat(32)}`);
  await page.getByLabel('Resend Webhook signing secret').fill(`whsec_${'w'.repeat(32)}`);
  await page.getByLabel('メール送信元').fill('ウマリアル <notice@example.test>');
  await page.getByLabel('通知の最大試行回数').fill('4');
  await page.getByLabel('管理設定の変更理由').fill('管理画面のE2E確認');
  await page.getByRole('button', { name: '管理設定を保存' }).click();
  await expect(page.getByText('管理設定を保存しました。', { exact: true })).toBeVisible();
  await expect(page.getByText('設定済み・未疎通', { exact: true })).toHaveCount(4);
  await expect(page.getByLabel('LINE Messaging API接続準備').getByText('暗号化データの検証')).toHaveClass(/ready/);
  await expect(page.getByLabel('LINE Messaging API接続準備').getByText('Webhook署名検証')).toHaveClass(/ready/);
  await expect(page.getByLabel('LINE Login接続準備').getByText('OAuth Callback', { exact: true })).toHaveClass(/ready/);
  await expect(page.getByLabel('LINE Login接続準備').getByText('テストtransport')).toBeVisible();
  await expect(page.getByLabel('Stripe接続準備').getByText('資格情報の保存')).toHaveClass(/ready/);
  await expect(page.getByLabel('Stripe接続準備').getByText('暗号化データの検証')).toHaveClass(/ready/);
  await expect(page.getByLabel('Stripe接続準備').getByText('Price ID')).toHaveClass(/ready/);
  await expect(page.getByLabel('Stripe接続準備').getByText('モード整合')).toHaveClass(/ready/);
  await expect(page.getByLabel('メール配信接続準備').getByText('API keyの保存')).toHaveClass(/ready/);
  await expect(page.getByLabel('メール配信接続準備').getByText('API keyの復号')).toHaveClass(/ready/);
  await expect(page.getByLabel('メール配信接続準備').getByText('Webhook署名鍵')).toHaveClass(/ready/);
  await expect(page.getByLabel('メール配信接続準備').getByText('Webhook受信処理')).toHaveClass(/ready/);
  await expect(page.getByLabel('メール配信接続準備').getByText('送信元')).toHaveClass(/ready/);
  await page.goto('/admin/notifications');
  await expect(page.getByRole('heading', { name: '通知運用', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '配送一覧', exact: true })).toBeVisible();
  await expect(page.getByLabel('通知種別')).toHaveValue('CONNECTION_CHECK');
  await expect(page.getByText('管理者本人（対象データ不要）', { exact: true })).toBeVisible();
  await expect(page.getByLabel('テスト理由')).toHaveAttribute('placeholder', 'LINE接続を確認するため');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/incidents');
  await expect(page.getByRole('heading', { name: '障害対応チェック', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '運営向け外部通知', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '運用アラート履歴', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '対応手順', exact: true })).toBeVisible();
  await expect(page.getByLabel('障害監視指標')).toContainText('60秒超の待機');
  await expect(page.getByLabel('会員向け案内文案')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/backups');
  await expect(page.getByRole('heading', { name: 'バックアップ・復元確認', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '検証内容', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '開発端末の復元結果を記録', exact: true })).toBeVisible();
  await expect(page.getByLabel('復元確認結果（JSON）')).toBeVisible();
  await expect(page.getByLabel('記録理由', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '監査履歴へ記録', exact: true })).toBeDisabled();
  await expect(page.getByRole('heading', { name: '本番バックアップ運用を記録', exact: true })).toBeVisible();
  await expect(page.getByLabel('バックアップ提供元')).toBeVisible();
  await expect(page.getByLabel('証跡参照番号')).toBeVisible();
  await expect(page.getByLabel('運用確認の記録理由')).toBeVisible();
  await expect(page.getByRole('button', { name: '運用確認を記録', exact: true })).toBeDisabled();
  await expect(page.locator('section').filter({ has: page.getByRole('heading', { name: '検証内容', exact: true }) }).getByText('pnpm db:backup:verify', { exact: true })).toBeVisible();
  await expect(page.getByLabel('バックアップ検証結果')).toContainText(/復元確認済み|復元確認に失敗|復元確認は未実施/);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/account-closures');
  await expect(page.getByRole('heading', { name: '退会・保持記録', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '正式方針の記録', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '匿名化対象プレビュー', exact: true })).toBeVisible();
  await expect(page.getByLabel('方針version')).toBeVisible();
  await expect(page.getByRole('button', { name: '正式方針を承認記録', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '処理済み一覧', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/billing');
  await expect(page.getByRole('heading', { name: '契約・請求管理', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'クーポン発行・利用状況', exact: true })).toBeVisible();
  const couponCode = `ADMIN_${randomBytes(5).toString('hex').toUpperCase()}`;
  await page.getByLabel('クーポンコード').fill(couponCode);
  await page.getByLabel('管理用名称').fill('管理画面E2E割引');
  await page.getByLabel('発行・停止理由').fill('管理画面の発行操作確認');
  await page.getByRole('button', { name: 'クーポンを発行', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('クーポンを発行しました');
  await expect(page.getByRole('cell', { name: new RegExp(couponCode) })).toBeVisible();
  await expect(page.getByRole('heading', { name: '公開待ち期限切れの一日券', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '請求問い合わせ', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '支払試行履歴', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/readiness');
  await expect(page.getByRole('heading', { name: '本番準備チェック', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '基盤・認証', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '外部接続', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '法務・データ', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '運用・復旧', exact: true })).toBeVisible();
  await expect(page.getByText('この自動判定だけで本番公開を承認しません。', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/continuity');
  await expect(page.getByRole('heading', { name: '管理者の継続運用', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: '管理者と認証準備', exact: true })).toBeVisible({ timeout: 15_000 });
  await expect(page.getByRole('heading', { name: '管理者を追加', exact: true })).toBeVisible();
  await expect(page.getByText('現在は開発用認証です。予備認証アプリはSupabase本番認証へ接続した後に登録できます。', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/admin/users');
  await expect(page.getByRole('heading', { name: '会員管理', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: new RegExp(`^${fixture.user.email}確認済み$`) })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
