import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { account, base, Client, db } from './helpers';

beforeAll(() => {
  const url = new URL(process.env.DATABASE_URL ?? '');
  if (!['localhost', '127.0.0.1'].includes(url.hostname) || process.env.AUTH_PROVIDER !== 'local') throw new Error('Integration suite is limited to a local development database');
  if (!base.startsWith('http://127.0.0.1:')) throw new Error('API must be local');
});
afterAll(() => db.$disconnect());
describe('registration, account and session lifecycle', () => {
  it('requires all consent, fixes role to MEMBER, saves preferences and invalidates logout', async () => {
    const client = new Client();
    const input = { email: `registered-${randomBytes(5).toString('hex')}@example.test`, displayName: '登録テスト', password: 'integration-password-123', adult: true, terms: true, privacy: true, termsVersion: 'draft-v1', privacyVersion: 'draft-v1', acquisition: { source: ' LP ', medium: ' Owned ', campaign: 'integration-email', content: 'hero', landingPath: '/register', referralCode: 'staff_01' } };
    expect((await client.call('auth/register', 'POST', { ...input, adult: false })).status).toBe(400);
    expect((await client.call('auth/register', 'POST', { ...input, role: 'ADMIN' })).status).toBe(400);
    const registered = await client.call('auth/register', 'POST', input);
    expect(registered.status).toBe(201);
    const acquisition = await db.memberAcquisition.findUniqueOrThrow({ where: { userId: registered.body.user.id } });
    expect(acquisition).toMatchObject({ source: 'lp', medium: 'owned', campaign: 'integration-email', content: 'hero', landingPath: '/register', referralCode: 'staff_01' });
    await expect(db.memberAcquisition.update({ where: { id: acquisition.id }, data: { source: 'overwrite' } })).rejects.toThrow();
    await expect(db.memberAcquisition.delete({ where: { id: acquisition.id } })).rejects.toThrow();
    expect(registered.body.requiresEmailVerification).toBe(true);
    expect((await client.call('me')).status).toBe(401);
    expect((await client.call('auth/login', 'POST', { email: input.email, password: input.password })).status).toBe(403);
    const mail = JSON.parse(await readFile(resolve('.local/mail', `${registered.body.user.id}-verify.json`), 'utf8')) as { url: string };
    const token = new URL(mail.url).searchParams.get('token');
    const verified = await client.call('auth/email/verify', 'POST', { token });
    expect(verified.status).toBe(201);
    expect(verified.headers.get('set-cookie')).toContain('HttpOnly');
    expect((await client.call('auth/email/verify', 'POST', { token })).status).toBe(400);
    const me = await client.call('me');
    expect(me.body.role).toBe('MEMBER');
    expect(me.body.emailVerified).toBe(true);
    expect(me.body.registrationMethod).toBe('EMAIL');
    expect(me.body).toMatchObject({ lineLinked: false, lineNotificationReady: false, lineNotificationState: 'NOT_LINKED' });
    expect(me.body.consents).toHaveLength(3);
    expect(me.body.preferences).toEqual({ emailEnabled: true, predictions: true, changes: true, articles: false, billing: true });
    expect(JSON.stringify(me.body)).not.toMatch(/passwordHash|mfaSecret|tokenHash/);
    expect((await client.call('admin/users')).status).toBe(403);
    const preferences = { predictions: false, changes: true, articles: true, billing: false };
    expect((await client.call('me/preferences', 'PATCH', preferences)).status).toBe(200);
    const updatedMe = (await client.call('me')).body;
    expect(updatedMe.preferences).toMatchObject(preferences);
    expect(updatedMe.lineNotificationState).toBe('NOT_LINKED');
    expect((await client.call('me/preferences', 'PATCH', preferences, 'https://invalid.example')).status).toBe(403);
    const old = client.cookie;
    expect((await client.call('auth/logout', 'POST')).status).toBe(201);
    client.cookie = old;
    expect((await client.call('me')).status).toBe(401);
    expect((await db.auditLog.count({ where: { targetId: registered.body.user.id } }))).toBeGreaterThanOrEqual(3);
  });
  it('rejects unbounded or URL-shaped acquisition data', async () => {
    const client = new Client(); const baseInput = { email: `invalid-acquisition-${randomBytes(5).toString('hex')}@example.test`, displayName: '流入検証', password: 'integration-password-123', adult: true, terms: true, privacy: true, termsVersion: 'draft-v1', privacyVersion: 'draft-v1' };
    expect((await client.call('auth/register', 'POST', { ...baseInput, acquisition: { source: 'lp', landingPath: 'https://tracker.example/register?secret=1' } })).status).toBe(400);
    expect((await client.call('auth/register', 'POST', { ...baseInput, acquisition: { source: 'x'.repeat(101) } })).status).toBe(400);
  });
  it('makes reset tokens one-use and revokes all prior sessions', async () => {
    const fixture = await account(); const client = new Client(); await client.login(fixture);
    const oldCookie = client.cookie;
    const requested = await client.call('auth/password/request', 'POST', { email: fixture.user.email });
    const unknown = await client.call('auth/password/request', 'POST', { email: 'nonexistent@example.test' });
    expect(requested.body).toEqual(unknown.body);
    const mail = JSON.parse(await readFile(resolve('.local/mail', `${fixture.user.id}.json`), 'utf8')) as { url: string };
    const token = new URL(mail.url).searchParams.get('token');
    const reset = { token, password: 'new-integration-password-123' };
    expect((await client.call('auth/password/reset', 'POST', reset)).status).toBe(201);
    expect((await client.call('auth/password/reset', 'POST', reset)).status).toBe(400);
    client.cookie = oldCookie;
    expect((await client.call('me')).status).toBe(401);
    expect((await client.call('auth/login', 'POST', { email: fixture.user.email, password: reset.password })).status).toBe(201);
  });
});
describe('server enforced staff authorization', () => {
  it('requires MFA and rotates sessions; rejects replay and unbounded entitlements', async () => {
    const fixture = await account('ADMIN'); const client = new Client(); await client.login(fixture);
    const first = client.cookie;
    expect((await client.call('admin/summary')).status).toBe(403);
    const { code } = await client.mfa();
    expect(client.cookie).not.toBe(first);
    expect((await client.call('admin/summary')).status).toBe(200);
    expect((await client.call('auth/mfa/verify', 'POST', { code })).status).toBe(401);
    const user = await account();
    expect((await client.call(`admin/users/${user.user.id}/entitlements`, 'POST', { startsAt: '2026-01-01T00:00:00Z', reason: 'テスト', planCode: 'MANUAL' })).status).toBe(400);
    const grant = { startsAt: new Date().toISOString(), endsAt: new Date(Date.now() + 86400000).toISOString(), reason: '結合試験の有限期間付与', planCode: 'MANUAL' };
    const headers = { 'Idempotency-Key': crypto.randomUUID() };
    const firstGrant = await client.call(`admin/users/${user.user.id}/entitlements`, 'POST', grant, undefined, headers);
    expect(firstGrant.status).toBe(201);
    const repeated = await client.call(`admin/users/${user.user.id}/entitlements`, 'POST', grant, undefined, headers);
    expect(repeated.body).toEqual(firstGrant.body);
    expect((await client.call(`admin/users/${user.user.id}/entitlements`, 'POST', { ...grant, reason: 'different' }, undefined, headers)).status).toBe(409);
    expect(await db.entitlement.count({ where: { userId: user.user.id, grantedBy: fixture.user.id } })).toBe(1);
    expect(await db.auditLog.count({ where: { targetId: user.user.id, action: 'ENTITLEMENT_GRANT' } })).toBe(1);
    const stolen = new Client(); stolen.cookie = first;
    expect((await stolen.call('admin/summary')).status).toBe(401);
  });
  it('restricts expert workspace to assigned races', async () => {
    const fixture = await account('EXPERT'); const client = new Client(); await client.login(fixture);
    const venue = `TEST-${randomBytes(4).toString('hex')}`;
    const race = await db.race.create({ data: { raceDate: '2099-01-01', venue, number: 1, name: '権限検証専用レース', startsAt: new Date('2099-01-01T06:00:00Z'), assignments: { create: { userId: fixture.user.id } } } });
    const other = await db.race.create({ data: { raceDate: '2099-01-01', venue, number: 2, name: '担当外の検証専用レース', startsAt: new Date('2099-01-01T07:00:00Z') } });
    expect((await client.call(`expert/races/${race.id}/workspace`)).status).toBe(403);
    await client.mfa();
    expect((await client.call(`expert/races/${race.id}/workspace`)).status).toBe(200);
    expect((await client.call(`expert/races/${other.id}/workspace`)).status).toBe(403);
    expect((await client.call('admin/users')).status).toBe(403);
    const list = await client.call('expert/races');
    expect(list.body.items.map((r: { id: string }) => r.id)).toContain(race.id);
    expect(list.body.items.map((r: { id: string }) => r.id)).not.toContain(other.id);
  });
  it('rejects database audit mutations and inconsistent periods', async () => {
    const user = await account();
    const log = await db.auditLog.create({ data: { actorId: user.user.id, action: 'TEST_APPEND_ONLY', targetType: 'USER', targetId: user.user.id, reason: 'DB保護試験', details: {}, requestId: crypto.randomUUID() } });
    await expect(db.auditLog.update({ where: { id: log.id }, data: { reason: 'overwrite' } })).rejects.toThrow();
    await expect(db.auditLog.delete({ where: { id: log.id } })).rejects.toThrow();
    expect(await db.auditLog.findUnique({ where: { id: log.id } })).toMatchObject({ reason: 'DB保護試験' });
    await expect(db.entitlement.create({ data: { userId: user.user.id, grantedBy: user.user.id, planCode: 'MANUAL', startsAt: new Date('2026-02-01'), endsAt: new Date('2026-01-01'), reason: 'invalid' } })).rejects.toThrow();
  });
});
