'use client';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { ShieldAlert } from 'lucide-react';

type Eligibility = { eligible: boolean; passwordRequired: boolean; blockers: { code: string; message: string; href: string; endsAt: string }[]; retentionPolicyVersion: string; retained: string[] };

export function AccountClosure({ onClosed }: { onClosed: () => Promise<void> }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [eligibility, setEligibility] = useState<Eligibility | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function begin() { setBusy(true); setError(''); try { const response = await fetch('/api/v1/me/closure', { cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '退会条件を確認できませんでした。'); setEligibility(result); setOpen(true); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function close(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); try { const response = await fetch('/api/v1/me/close', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reasonCode: form.get('reasonCode'), confirmation: form.get('confirmation'), ...(eligibility?.passwordRequired ? { currentPassword: form.get('currentPassword') } : {}) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '退会手続きを完了できませんでした。'); await onClosed(); router.replace('/login?closed=1'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section className="panel account-closure"><div className="panel-heading"><div><span className="eyebrow">ACCOUNT CLOSURE</span><h2>退会</h2></div><ShieldAlert size={20} /></div><div className="panel-body"><p>退会すると、すべての端末からログアウトし、LINE通知と有料情報の閲覧を停止します。</p>{error && <div className="notice error" role="alert">{error}</div>}{!open ? <button className="button secondary" disabled={busy} onClick={() => void begin()}>{busy ? '確認中…' : '退会条件を確認'}</button> : eligibility && !eligibility.eligible ? <div className="closure-blockers"><strong>現在は退会できません</strong>{eligibility.blockers.map(item => <p key={item.code}>{item.message}</p>)}</div> : eligibility ? <form className="closure-form" onSubmit={close}><div className="notice">公開・評価、支払・契約、同意、監査の履歴は保持されます。個人情報の匿名化時期は正式な保持方針の決定後に扱います。</div><label className="field">退会理由<select name="reasonCode" required defaultValue="SERVICE_NO_LONGER_NEEDED"><option value="SERVICE_NO_LONGER_NEEDED">利用しなくなった</option><option value="PRICE">料金</option><option value="CONTENT">内容</option><option value="OTHER">その他</option></select></label>{eligibility.passwordRequired && <label className="field">現在のパスワード<input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128} /></label>}<label className="field">確認のため「退会する」と入力<input name="confirmation" required autoComplete="off" /></label><div className="closure-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => setOpen(false)}>戻る</button><button className="button danger" disabled={busy}>{busy ? '処理中…' : '退会して利用を停止'}</button></div></form> : null}</div></section>;
}
