'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { Check, Copy, Download, Link2, Plus } from 'lucide-react';

type Campaign = { id: string; name: string; code: string; source: string; medium: string; content: string | null; landingPath: string; referralCode: string | null; registrationUrl: string; createdAt: string };
type Breakdown = { source: string; medium: string | null; campaign: string | null; registered: number; paid: number };
type Report = { days: number; since: string; legacyMembers: number; campaigns: Campaign[]; breakdown: Breakdown[] };
async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> { const response = await fetch(`/api/v1/${path}`, { method, headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' }); const value = await response.json(); if (!response.ok) throw new Error(value.message ?? '処理に失敗しました。'); return value as T; }

export function AcquisitionManager() {
  const [report, setReport] = useState<Report | null>(null); const [days, setDays] = useState(30); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [copied, setCopied] = useState('');
  async function load(nextDays = days) { setError(''); try { setReport(await api<Report>(`admin/acquisition?days=${nextDays}`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); const formElement = event.currentTarget; const form = new FormData(formElement); try { const campaign = await api<Campaign>('admin/acquisition/campaigns', 'POST', { name: form.get('name'), code: form.get('code'), source: form.get('source'), medium: form.get('medium'), content: form.get('content') || undefined, landingPath: form.get('landingPath'), referralCode: form.get('referralCode') || undefined, reason: form.get('reason') }); setMessage(`「${campaign.name}」の登録URLを発行しました。`); formElement.reset(); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function copy(campaign: Campaign) { try { await navigator.clipboard.writeText(campaign.registrationUrl); setCopied(campaign.id); window.setTimeout(() => setCopied(''), 2000); } catch { setError('URLをコピーできませんでした。URL欄を長押ししてコピーしてください。'); } }
  const rate = (row: Breakdown) => row.registered ? Math.round(row.paid / row.registered * 100) : 0;
  return <><div className="page-heading"><span className="eyebrow">ACQUISITION</span><h1>キャンペーン・流入管理</h1><p>LPや広告ごとの無料登録URLを発行し、有料化までの結果を確認します。</p></div>{error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <section className="panel campaign-create"><div className="panel-heading"><div><span className="eyebrow">NEW LINK</span><h2>登録URLを発行</h2></div></div><form className="panel-body" onSubmit={create}><div className="campaign-form-grid"><label className="field">管理用の名前<input name="name" maxLength={120} required placeholder="例：秋開催LP メイン導線" /></label><label className="field">キャンペーンコード<input name="code" maxLength={64} pattern="[A-Za-z0-9_-]+" required placeholder="例：autumn_launch" /></label><label className="field">流入元<input name="source" maxLength={100} required defaultValue="lp" placeholder="例：lp" /></label><label className="field">媒体<input name="medium" maxLength={100} required defaultValue="owned" placeholder="例：owned、line、instagram" /></label><label className="field">コンテンツ識別（任意）<input name="content" maxLength={160} placeholder="例：hero_button" /></label><label className="field">紹介コード（任意）<input name="referralCode" maxLength={64} pattern="[A-Za-z0-9_-]+" placeholder="例：staff_01" /></label><label className="field">登録先パス<input name="landingPath" maxLength={500} pattern="/[^?#]*" required defaultValue="/register" /></label><label className="field campaign-reason">発行理由<textarea name="reason" maxLength={500} required placeholder="掲載場所と目的を記録してください。" /></label></div><button className="button" disabled={busy}><Plus size={17} />{busy ? '発行中…' : '登録URLを発行'}</button></form></section>
    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">ISSUED LINKS</span><h2>発行済みURL</h2></div><span className="count-tag">{report?.campaigns.length ?? 0}件</span></div>{report?.campaigns.length ? <div className="campaign-list">{report.campaigns.map(campaign => <article className="campaign-row" key={campaign.id}><div><strong>{campaign.name}</strong><small>{campaign.source} / {campaign.medium} / {campaign.code} · {new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', dateStyle: 'short', timeStyle: 'short' }).format(new Date(campaign.createdAt))} JST</small><input aria-label={`${campaign.name}の登録URL`} readOnly value={campaign.registrationUrl} onFocus={event => event.currentTarget.select()} /></div><button className="button secondary small" onClick={() => void copy(campaign)}>{copied === campaign.id ? <Check size={16} /> : <Copy size={16} />}{copied === campaign.id ? 'コピー済み' : 'コピー'}</button></article>)}</div> : <div className="panel-body"><p className="muted">発行済みのキャンペーンURLはありません。</p></div>}</section>
    <section className="panel"><div className="panel-heading acquisition-report-heading"><div><span className="eyebrow">REPORT</span><h2>流入別レポート</h2></div><div><label>集計期間<select aria-label="集計期間" value={days} onChange={event => { const next = Number(event.target.value); setDays(next); void load(next); }}><option value={7}>7日</option><option value={30}>30日</option><option value={90}>90日</option><option value={365}>365日</option></select></label><a className="button secondary small" href={`/api/v1/admin/acquisition/export.csv?days=${days}`} download><Download size={16} />CSV出力</a></div></div>{report?.breakdown.length ? <div className="table-scroll"><table><thead><tr><th>流入元</th><th>キャンペーン</th><th>無料登録</th><th>有料化</th><th>率</th></tr></thead><tbody>{report.breakdown.map(row => <tr key={`${row.source}:${row.medium ?? ''}:${row.campaign ?? ''}`}><td><strong>{row.source}</strong><small>{row.medium ?? '未設定'}</small></td><td>{row.campaign ?? '未設定'}</td><td>{row.registered}人</td><td>{row.paid}人</td><td>{rate(row)}%</td></tr>)}</tbody></table></div> : <div className="panel-body"><p className="muted">この期間の流入データはありません。</p></div>}<div className="panel-foot"><Link2 size={16} />CSVには個人情報を含めず、流入別の集計値だけを出力します。{report?.legacyMembers ? ` 計測開始前の会員 ${report.legacyMembers}人。` : ''}</div></section></>;
}
