'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, BellRing, Check, ClipboardCopy, Mail, RefreshCw, ShieldAlert } from 'lucide-react';

type Issue = { code: string; severity: 'CRITICAL' | 'WARNING' | 'INFO'; title: string; detail: string; action: string; href: string };
type IncidentResponse = { generatedAt: string; status: 'NORMAL' | 'DEGRADED' | 'INCIDENT'; counts: { critical: number; warning: number; total: number }; issues: Issue[]; publicMessage: string; monitoring: { failedDeliveries: number; delayedDeliveries: number; stuckDeliveries: number; unmatchedWebhooks24h: number } };
type Delivery = { id: string; recipient: string; status: string; attemptCount: number; lastErrorCode: string | null };
type Alert = { id: string; code: string; severity: 'CRITICAL' | 'WARNING'; title: string; summary: string; status: 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED'; detectedAt: string; acknowledgeReason: string | null; resolutionReason: string | null; deliveries: Delivery[] };
type AlertResponse = { items: Alert[]; counts: { open: number; acknowledged: number; resolved: number } };
type AlertSettings = { revision: number; enabled: boolean; minimumSeverity: 'CRITICAL' | 'WARNING'; destinationEmails: string[]; updatedAt: string };
const stateLabel = { NORMAL: '正常', DEGRADED: '要確認', INCIDENT: '障害対応中' } as const;
const severityLabel = { CRITICAL: '重大', WARNING: '警告', INFO: '案内中' } as const;
const alertStateLabel = { OPEN: '未確認', ACKNOWLEDGED: '確認済み', RESOLVED: '解決済み' } as const;
const formatDate = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date(value));
async function api<T>(url: string, init?: RequestInit) { const response = await fetch(url, { cache: 'no-store', headers: { 'Content-Type': 'application/json' }, ...init }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? '処理を完了できませんでした。'); return body as T; }

export function AdminIncidents({ role }: { role: string }) {
  const [data, setData] = useState<IncidentResponse | null>(null); const [alerts, setAlerts] = useState<AlertResponse | null>(null); const [settings, setSettings] = useState<AlertSettings | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [copied, setCopied] = useState(false); const [busy, setBusy] = useState('');
  const [filter, setFilter] = useState<'ALL' | 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED'>('ALL'); const [emails, setEmails] = useState(''); const [settingReason, setSettingReason] = useState(''); const [reasons, setReasons] = useState<Record<string, string>>({});
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [incident, alertList, alertSettings] = await Promise.all([api<IncidentResponse>('/api/v1/admin/incidents'), api<AlertResponse>(`/api/v1/admin/operational-alerts?status=${filter}`), api<AlertSettings>('/api/v1/admin/operational-alerts/settings')]);
      setData(incident); setAlerts(alertList); setSettings(alertSettings); setEmails(alertSettings.destinationEmails.join('\n')); setError('');
    } catch (e) { setError((e as Error).message); } finally { setLoading(false); }
  }, [filter]);
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (document.visibilityState === 'visible') void load(); }, 30000); return () => window.clearInterval(timer); }, [load]);
  async function copyMessage() { if (!data) return; try { await navigator.clipboard.writeText(data.publicMessage); setCopied(true); window.setTimeout(() => setCopied(false), 2000); } catch { setError('案内文をコピーできませんでした。'); } }
  async function saveSettings() {
    if (!settings) return; setBusy('settings'); setError('');
    try { const destinationEmails = emails.split(/[\n,]/).map(value => value.trim()).filter(Boolean); const next = await api<AlertSettings>('/api/v1/admin/operational-alerts/settings', { method: 'PATCH', body: JSON.stringify({ revision: settings.revision, enabled: settings.enabled, minimumSeverity: settings.minimumSeverity, destinationEmails, reason: settingReason }) }); setSettings(next); setEmails(next.destinationEmails.join('\n')); setSettingReason(''); setMessage('外部アラート設定を保存しました。'); }
    catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  async function act(alert: Alert, action: 'acknowledge' | 'resolve') {
    const reason = reasons[alert.id]?.trim(); if (!reason) return; setBusy(`${action}-${alert.id}`); setError('');
    try { await api(`/api/v1/admin/operational-alerts/${alert.id}/${action}`, { method: 'POST', body: JSON.stringify({ reason }) }); setReasons({ ...reasons, [alert.id]: '' }); setMessage(action === 'acknowledge' ? 'アラートを確認済みにしました。' : 'アラートを解決済みにしました。'); await load(); }
    catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  async function retry(delivery: Delivery, alertId: string) { const reason = reasons[alertId]?.trim(); if (!reason) return; setBusy(`retry-${delivery.id}`); try { await api(`/api/v1/admin/operational-alerts/deliveries/${delivery.id}/retry`, { method: 'POST', body: JSON.stringify({ reason }) }); setMessage('外部通知を再送待ちに戻しました。'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  const runbook = [['1', '検知内容を確認', '件数、発生範囲、直近の設定変更を確認します。'], ['2', '会員向けWeb公開を確認', '通知障害中もWeb上の公開情報を維持します。'], ['3', '影響を抑える', '必要な機能だけを理由付きで停止します。'], ['4', '原因を解消して復旧', '失敗理由を確認し、復旧後に再送します。'], ['5', '復旧を記録', '確認済み・解決済みと対応理由を残します。']];
  return <><div className="page-heading"><span className="eyebrow">INCIDENT RESPONSE</span><h1>障害対応チェック</h1><p>現在の停止・遅延を検知し、外部通知から復旧記録までを管理します。</p></div>
    {error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    {loading && !data ? <div className="panel loading" role="status">障害状態を確認中…</div> : data && <>
      <section className={`incident-hero ${data.status.toLowerCase()}`} aria-label={`システム状態 ${stateLabel[data.status]}`}><div className="incident-hero-icon">{data.status === 'NORMAL' ? <Check /> : <ShieldAlert />}</div><div><span>現在のシステム状態</span><h2>{stateLabel[data.status]}</h2><small>最終確認 {formatDate(data.generatedAt)} JST</small></div><div className="incident-totals"><strong>{data.counts.critical}<small>重大</small></strong><strong>{data.counts.warning}<small>警告</small></strong><strong>{data.counts.total}<small>全検知</small></strong></div><button className="button secondary small" onClick={() => void load()} disabled={loading}><RefreshCw size={16} className={loading ? 'spin' : ''} />再確認</button></section>
      <section className="incident-metrics" aria-label="障害監視指標">{[['通知失敗', data.monitoring.failedDeliveries], ['60秒超の待機', data.monitoring.delayedDeliveries], ['5分超の送信中', data.monitoring.stuckDeliveries], ['未照合Webhook', data.monitoring.unmatchedWebhooks24h]].map(([label, value]) => <div className="stat" key={label}><span>{label}</span><strong>{value}<small>件</small></strong></div>)}</section>
      <section className="panel"><div className="panel-heading"><div><h2>検知内容</h2><span className="muted">自動判定 · 秘密情報は表示しません</span></div></div>{data.issues.length ? <div className="incident-list">{data.issues.map(issue => <article className={`incident-item ${issue.severity.toLowerCase()}`} key={issue.code}><AlertTriangle size={20} /><div><span>{severityLabel[issue.severity]}</span><h3>{issue.title}</h3><p>{issue.detail}</p><small>{issue.action}</small></div>{issue.href === '/admin/settings' && role !== 'ADMIN' ? <b>管理者へ連絡</b> : <Link className="button secondary small" href={issue.href}>確認する</Link>}</article>)}</div> : <div className="empty incident-clear"><Check size={34} /><h3>対応が必要な障害はありません</h3><p>公開・通知・取込と通知キューに異常は検知されていません。</p></div>}</section>
      {settings && <section className="panel operational-alert-settings"><div className="panel-heading"><div><span className="eyebrow">EXTERNAL ALERTS</span><h2>運営向け外部通知</h2></div><span className={`status-tag ${settings.enabled ? '' : 'warning'}`}>{settings.enabled ? '有効' : '無効'}</span></div><div className="panel-body"><p className="muted">配信失敗、予約公開失敗、公開期限超過をメール通知します。会員情報や予想本文は含みません。</p>{role === 'ADMIN' ? <><label className="setting-row"><span><strong>外部アラートを送信</strong><small>Resendの送信設定を利用します。</small></span><input aria-label="外部アラートを送信する" type="checkbox" checked={settings.enabled} onChange={event => setSettings({ ...settings, enabled: event.target.checked })} /></label><div className="two-columns"><label className="field">通知する最低重大度<select aria-label="外部アラートの最低重大度" value={settings.minimumSeverity} onChange={event => setSettings({ ...settings, minimumSeverity: event.target.value as AlertSettings['minimumSeverity'] })}><option value="CRITICAL">重大のみ</option><option value="WARNING">重大と警告</option></select></label><label className="field">通知先メールアドレス<textarea aria-label="外部アラートの通知先" rows={3} value={emails} onChange={event => setEmails(event.target.value)} placeholder={'ops@example.com\nowner@example.com'} /><small>1行に1件、最大10件</small></label></div><label className="field">設定変更理由<input aria-label="外部アラート設定の変更理由" maxLength={500} value={settingReason} onChange={event => setSettingReason(event.target.value)} /></label><button className="button" disabled={busy === 'settings' || !settingReason.trim()} onClick={() => void saveSettings()}><Mail size={17} />{busy === 'settings' ? '保存中…' : '外部通知設定を保存'}</button></> : <p>最低重大度: {severityLabel[settings.minimumSeverity]} · 通知先 {settings.destinationEmails.length}件</p>}</div></section>}
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">ALERT HISTORY</span><h2>運用アラート履歴</h2></div><label className="date-filter">状態<select aria-label="運用アラートの状態" value={filter} onChange={event => setFilter(event.target.value as typeof filter)}><option value="ALL">すべて</option><option value="OPEN">未確認</option><option value="ACKNOWLEDGED">確認済み</option><option value="RESOLVED">解決済み</option></select></label></div><div className="alert-counts" aria-label="運用アラート件数"><span>未確認 <strong>{alerts?.counts.open ?? 0}</strong></span><span>確認済み <strong>{alerts?.counts.acknowledged ?? 0}</strong></span><span>解決済み <strong>{alerts?.counts.resolved ?? 0}</strong></span></div>{alerts?.items.length ? <div className="operational-alert-list">{alerts.items.map(alert => <article className={`operational-alert-item ${alert.severity.toLowerCase()}`} key={alert.id}><div className="operational-alert-title"><BellRing size={20} /><div><span>{severityLabel[alert.severity]} · {alert.code}</span><h3>{alert.title}</h3><small>{formatDate(alert.detectedAt)} JST · {alertStateLabel[alert.status]}</small></div></div><p>{alert.summary}</p>{alert.deliveries.length > 0 && <div className="alert-deliveries">{alert.deliveries.map(delivery => <div key={delivery.id}><span>{delivery.recipient}</span><b>{delivery.status === 'SENT' ? '送信済み' : delivery.status === 'FAILED' ? '送信失敗' : '送信待ち'}</b>{delivery.status === 'FAILED' && alert.status !== 'RESOLVED' && <button className="text-link" disabled={!reasons[alert.id]?.trim() || busy === `retry-${delivery.id}`} onClick={() => void retry(delivery, alert.id)}>再送</button>}</div>)}</div>}{alert.status !== 'RESOLVED' && <div className="alert-actions"><input aria-label={`${alert.title}の対応理由`} maxLength={500} value={reasons[alert.id] ?? ''} onChange={event => setReasons({ ...reasons, [alert.id]: event.target.value })} placeholder="確認内容または解決理由" />{alert.status === 'OPEN' && <button className="button secondary small" disabled={!reasons[alert.id]?.trim()} onClick={() => void act(alert, 'acknowledge')}>確認済み</button>}<button className="button small" disabled={!reasons[alert.id]?.trim()} onClick={() => void act(alert, 'resolve')}>解決済み</button></div>}{alert.acknowledgeReason && <small>確認記録: {alert.acknowledgeReason}</small>}{alert.resolutionReason && <small>解決記録: {alert.resolutionReason}</small>}</article>)}</div> : <div className="empty incident-clear"><Check size={34} /><h3>該当するアラート履歴はありません</h3></div>}</section>
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">RUNBOOK</span><h2>対応手順</h2></div></div><ol className="incident-runbook">{runbook.map(([number, title, detail]) => <li key={number}><b>{number}</b><div><strong>{title}</strong><small>{detail}</small></div></li>)}</ol><div className="incident-links"><Link className="button secondary small" href="/admin">運用ボード</Link><Link className="button secondary small" href="/admin/notifications">通知履歴</Link>{role === 'ADMIN' && <Link className="button secondary small" href="/admin/settings">緊急停止設定</Link>}{role === 'ADMIN' && <Link className="button secondary small" href="/admin/audit">監査ログ</Link>}</div></section>
      <section className="panel incident-message"><div className="panel-heading"><div><h2>会員向け案内文案</h2><span className="muted">内容を確認してから既存の案内手段で使用してください</span></div></div><div className="panel-body"><textarea aria-label="会員向け案内文案" readOnly value={data.publicMessage} rows={4} /><button className="button secondary small" onClick={() => void copyMessage()}><ClipboardCopy size={16} />{copied ? 'コピーしました' : '案内文をコピー'}</button></div></section>
    </>}
  </>;
}
