'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Gift, ShieldAlert, Users } from 'lucide-react';
import type { AdminReferralBenefitGrantsResponse, AdminReferralBenefitsResponse, AdminReferralDetailResponse, AdminReferralInvalidateResponse, AdminReferralListResponse, ReferralBenefitConfig, ReferralBenefitType } from '@keiba/domain';

async function request<T>(path: string, method = 'GET', body?: unknown, idempotent = false): Promise<T> {
  const headers: Record<string, string> = body ? { 'Content-Type': 'application/json' } : {};
  if (idempotent) headers['Idempotency-Key'] = crypto.randomUUID();
  const response = await fetch(`/api/v1/${path}`, { method, headers, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' });
  const result = await response.json();
  if (!response.ok) throw new Error(result.message ?? '処理に失敗しました。');
  return result as T;
}
const format = (value: string | null) => value ? new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const labels: Record<string, string> = { PENDING: '本人確認待ち', QUALIFIED: '成立', INVALIDATED: '無効', AVAILABLE: '未使用', REDEEMED: '使用済み', EXPIRED: '期限切れ' };
const rewardLabels: Record<ReferralBenefitType, string> = { DAY_PASS: '1日利用券', MONTHLY_ACCESS: '期間限定の月額相当閲覧', LIMITED_CONTENT: '限定コンテンツ' };
const emptyConfig: ReferralBenefitConfig = { name: '', description: '', requiredReferralCount: 1, rewardType: 'DAY_PASS', quantity: 1, claimValidityDays: 60, accessDays: null, distributionStartsAt: null, distributionEndsAt: null, published: false, grantEnabled: false, sortOrder: 0, memberGuidance: '', usageTerms: '', contentItemIds: [] };

export function AdminReferrals() {
  const [data, setData] = useState<AdminReferralListResponse | null>(null); const [status, setStatus] = useState('ALL'); const [page, setPage] = useState(1); const [detail, setDetail] = useState<AdminReferralDetailResponse | null>(null); const [reason, setReason] = useState('');
  const [benefits, setBenefits] = useState<AdminReferralBenefitsResponse | null>(null); const [grants, setGrants] = useState<AdminReferralBenefitGrantsResponse | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [config, setConfig] = useState<ReferralBenefitConfig>(emptyConfig); const [benefitReason, setBenefitReason] = useState('');
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(''); try { const [summary, benefitRows, grantRows] = await Promise.all([request<AdminReferralListResponse>(`admin/referrals?page=${page}&status=${status}`), request<AdminReferralBenefitsResponse>('admin/referrals/benefits'), request<AdminReferralBenefitGrantsResponse>('admin/referrals/benefit-grants?page=1&status=ALL')]); setData(summary); setBenefits(benefitRows); setGrants(grantRows); } catch (e) { setError((e as Error).message); } }, [page, status]);
  useEffect(() => { void load(); }, [load]);
  async function open(id: string) { setError(''); try { setDetail(await request<AdminReferralDetailResponse>(`admin/referrals/${id}`)); setReason(''); } catch (e) { setError((e as Error).message); } }
  async function invalidate(event: FormEvent) { event.preventDefault(); if (!detail) return; setBusy(true); setError(''); setMessage(''); try { await request<AdminReferralInvalidateResponse>(`admin/referrals/${detail.id}/invalidate`, 'POST', { reason }); setMessage('紹介を無効化し、未使用特典を安全に再計算しました。'); setDetail(await request<AdminReferralDetailResponse>(`admin/referrals/${detail.id}`)); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function edit(id: string) { const row = benefits?.items.find(item => item.id === id); if (!row) return; const latest = row.latest; setEditingId(id); setConfig({ name: latest.name, description: latest.description, requiredReferralCount: latest.requiredReferralCount, rewardType: latest.rewardType, quantity: latest.quantity, claimValidityDays: latest.claimValidityDays, accessDays: latest.accessDays, distributionStartsAt: latest.distributionStartsAt, distributionEndsAt: latest.distributionEndsAt, published: latest.published, grantEnabled: latest.grantEnabled, sortOrder: latest.sortOrder, memberGuidance: latest.memberGuidance, usageTerms: latest.usageTerms, contentItemIds: latest.contents.map(item => item.id) }); setBenefitReason(''); }
  function resetBenefit() { setEditingId(null); setConfig(emptyConfig); setBenefitReason(''); }
  async function saveBenefit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const current = benefits?.items.find(item => item.id === editingId); const path = current ? `admin/referrals/benefits/${current.id}/versions` : 'admin/referrals/benefits'; await request(path, 'POST', { expectedRevision: current?.revision ?? 0, reason: benefitReason, config }, true); setMessage(current ? '紹介特典の新しい設定版を保存しました。既得特典は変更されません。' : '紹介特典を作成しました。公開・新規付与は設定値に従います。'); resetBenefit(); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const setRewardType = (rewardType: ReferralBenefitType) => setConfig({ ...config, rewardType, quantity: rewardType === 'LIMITED_CONTENT' ? 1 : config.quantity, accessDays: rewardType === 'MONTHLY_ACCESS' ? (config.accessDays ?? 30) : null, contentItemIds: rewardType === 'LIMITED_CONTENT' ? config.contentItemIds : [] });

  return <><div className="page-heading"><span className="eyebrow">REFERRAL OPERATIONS</span><h1>紹介管理</h1><p>紹介成立、特典設定、付与・利用状況を管理します。設定変更は新しい版として保存されます。</p></div>{error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">BENEFIT SETTINGS</span><h2>紹介特典設定</h2></div><button className="button secondary small" type="button" onClick={resetBenefit}>新規特典</button></div><div className="panel-body"><div className="notice">新しい特典は既定で非公開・付与停止です。条件変更は過去の獲得特典へ遡及せず、次の紹介成立から適用されます。</div>
      {benefits?.items.length ? <div className="table-scroll"><table><thead><tr><th>特典</th><th>条件</th><th>種別</th><th>状態</th><th>版</th><th></th></tr></thead><tbody>{benefits.items.map(item => <tr key={item.id}><td><strong>{item.latest.name}</strong></td><td>{item.latest.requiredReferralCount}人</td><td>{rewardLabels[item.latest.rewardType]}</td><td>{item.latest.published ? item.latest.grantEnabled ? '公開・付与中' : '公開・付与停止' : '非公開'}</td><td>v{item.latest.version}</td><td><button type="button" className="text-link" onClick={() => edit(item.id)}>変更</button></td></tr>)}</tbody></table></div> : <p className="muted">可変特典は未設定です。既存の紹介特典V1は引き続き動作します。</p>}
      <form className="settings-stack" onSubmit={saveBenefit}><h3>{editingId ? '設定の新しい版を作成' : '特典を追加'}</h3><div className="two-columns"><label className="field">特典名称<input required maxLength={100} value={config.name} onChange={e => setConfig({ ...config, name: e.target.value })} /></label><label className="field">特典種別<select value={config.rewardType} onChange={e => setRewardType(e.target.value as ReferralBenefitType)}><option value="DAY_PASS">1日利用券</option><option value="MONTHLY_ACCESS">期間限定の月額相当閲覧</option><option value="LIMITED_CONTENT">限定コンテンツ</option></select></label></div><label className="field">説明<textarea required maxLength={1000} value={config.description} onChange={e => setConfig({ ...config, description: e.target.value })} /></label>
        <div className="race-form-grid"><label className="field">必要紹介人数<input type="number" min={1} required value={config.requiredReferralCount} onChange={e => setConfig({ ...config, requiredReferralCount: Number(e.target.value) })} /></label><label className="field">数量<input type="number" min={1} max={100} disabled={config.rewardType === 'LIMITED_CONTENT'} required value={config.quantity} onChange={e => setConfig({ ...config, quantity: Number(e.target.value) })} /></label><label className="field">受取期限（日）<input type="number" min={1} max={3650} required value={config.claimValidityDays} onChange={e => setConfig({ ...config, claimValidityDays: Number(e.target.value) })} /></label>{config.rewardType === 'MONTHLY_ACCESS' && <label className="field">閲覧日数<input type="number" min={1} max={3650} required value={config.accessDays ?? 30} onChange={e => setConfig({ ...config, accessDays: Number(e.target.value) })} /></label>}<label className="field">表示順<input type="number" min={0} value={config.sortOrder} onChange={e => setConfig({ ...config, sortOrder: Number(e.target.value) })} /></label></div>
        {config.rewardType === 'LIMITED_CONTENT' && <fieldset className="field"><legend>対象コンテンツ</legend>{benefits?.contentOptions.map(item => <label key={item.id}><input type="checkbox" checked={config.contentItemIds.includes(item.id)} onChange={e => setConfig({ ...config, contentItemIds: e.target.checked ? [...config.contentItemIds, item.id] : config.contentItemIds.filter(id => id !== item.id) })} />{item.title}（{item.kind}）</label>)}</fieldset>}
        <label className="field">会員向け案内文<textarea required maxLength={1000} value={config.memberGuidance} onChange={e => setConfig({ ...config, memberGuidance: e.target.value })} /></label><label className="field">利用条件<textarea required maxLength={2000} value={config.usageTerms} onChange={e => setConfig({ ...config, usageTerms: e.target.value })} /></label><div className="credential-actions"><label><input type="checkbox" checked={config.published} onChange={e => setConfig({ ...config, published: e.target.checked, grantEnabled: e.target.checked ? config.grantEnabled : false })} />会員向け条件を公開</label><label><input type="checkbox" checked={config.grantEnabled} disabled={!config.published} onChange={e => setConfig({ ...config, grantEnabled: e.target.checked })} />新規付与を有効化</label></div><label className="field">変更理由<input required maxLength={500} value={benefitReason} onChange={e => setBenefitReason(e.target.value)} /></label><button className="button" disabled={busy}>{busy ? '保存中…' : '設定版を保存'}</button></form>
    </div></section>
    {grants && <section className="panel"><div className="panel-heading"><div><span className="eyebrow">BENEFIT GRANTS</span><h2>新特典の付与状況</h2></div><Gift size={21} /></div>{grants.items.length ? <div className="table-scroll"><table><thead><tr><th>会員</th><th>特典</th><th>状態</th><th>付与</th><th>期限</th></tr></thead><tbody>{grants.items.map(item => <tr key={item.id}><td>{item.member?.displayName ?? '—'}</td><td>{item.benefit.name}</td><td>{labels[item.status] ?? item.status}</td><td>{format(item.grantedAt)}</td><td>{format(item.expiresAt)}</td></tr>)}</tbody></table></div> : <div className="panel-body"><p className="muted">新特典の付与はまだありません。</p></div>}</section>}
    {!data ? <p role="status">紹介状況を読み込み中…</p> : <><div className="stats-grid referral-admin-stats">{[['紹介経由登録', data.summary.qualifiedReferrals, '人'], ['紹介者', data.summary.referrers, '人'], ...data.summary.milestoneAchievements.map(item => [`${item.requiredReferralCount}人達成`, item.users, '人']), ['特典付与', data.summary.rewardsGranted, '枚'], ['特典使用', data.summary.rewardsUsed, '枚']].map(([label, count, unit]) => <section className="stat" key={String(label)}><span>{label}</span><strong>{count}<small>{unit}</small></strong></section>)}</div>
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">REFERRERS</span><h2>紹介者別</h2></div><Gift size={21} /></div>{data.items.length ? <div className="table-scroll"><table><thead><tr><th>会員</th><th>紹介コード</th><th>成立人数</th><th>達成</th><th>付与特典</th></tr></thead><tbody>{data.items.map(item => <tr key={item.user.id}><td>{item.user.displayName}</td><td className="mono">{item.user.referralCode}</td><td>{item.referralCount}人</td><td>{item.achievedMilestones.length ? item.achievedMilestones.sort((a,b) => a-b).map(value => `${value}人`).join('・') : '—'}</td><td>{item.rewardsGranted}枚</td></tr>)}</tbody></table></div> : <div className="panel-body"><p className="muted">紹介者はまだいません。</p></div>}<div className="pagination"><span>全{data.total}人 · {page}ページ</span><button className="button secondary small" disabled={page <= 1} onClick={() => setPage(page - 1)}>前へ</button><button className="button secondary small" disabled={page * 20 >= data.total} onClick={() => setPage(page + 1)}>次へ</button></div></section>
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">REFERRALS</span><h2>紹介記録</h2></div><label className="compact-filter">状態<select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="ALL">すべて</option><option value="PENDING">本人確認待ち</option><option value="QUALIFIED">成立</option><option value="INVALIDATED">無効</option></select></label></div>{data.recentReferrals.length ? <div className="referral-admin-list">{data.recentReferrals.map(row => <button type="button" key={row.id} onClick={() => void open(row.id)}><Users size={19} /><span><strong>{row.referrer.displayName} → {row.referred.displayName}</strong><small>{row.referred.registrationMethod}登録 · {format(row.qualifiedAt ?? row.createdAt)}</small></span><b>{labels[row.status] ?? row.status}</b></button>)}</div> : <div className="panel-body"><p className="muted">該当する紹介記録はありません。</p></div>}</section></>}
    {detail && <section className="panel referral-detail"><div className="panel-heading"><div><span className="eyebrow">DETAIL</span><h2>紹介詳細</h2></div><button className="text-link" onClick={() => setDetail(null)}>閉じる</button></div><dl><div><dt>紹介者</dt><dd>{detail.referrer.displayName}<small>{detail.referrer.referralCode}</small></dd></div><div><dt>被紹介者</dt><dd>{detail.referred.displayName}<small>{detail.referred.registrationMethod}登録</small></dd></div><div><dt>登録日時</dt><dd>{format(detail.referred.createdAt)}</dd></div><div><dt>紹介成立日時</dt><dd>{format(detail.qualifiedAt)}</dd></div><div><dt>状態</dt><dd>{labels[detail.status] ?? detail.status}</dd></div>{detail.invalidatedReason && <div><dt>無効化理由</dt><dd>{detail.invalidatedReason}</dd></div>}</dl>{detail.status === 'QUALIFIED' && <form className="referral-invalidate" onSubmit={event => void invalidate(event)}><ShieldAlert size={22} /><div><strong>不正登録として無効化</strong><p>未使用の紹介特典だけを無効化します。使用済みの権限は巻き戻しません。</p><label>理由<textarea value={reason} onChange={event => setReason(event.target.value)} maxLength={500} required /></label></div><button className="button danger" disabled={busy}>{busy ? '処理中…' : '無効化する'}</button></form>}</section>}
  </>;
}
