'use client';
import { useCallback, useEffect, useState } from 'react';
import { RefreshCw, RotateCcw } from 'lucide-react';

type Attempt = { id: string; attemptNumber: number; outcome: string; errorCode: string | null; finishedAt: string };
type Race = { raceDate: string; venue: string; number: number; name: string };
type Delivery = { id: string; status: string; attemptCount: number; manualRetryCount: number; nextAttemptAt: string; lastErrorCode: string | null; sentAt: string | null; user: { displayName: string; email: string | null }; event: { eventType: string; version: { version: number; visibility: string; prediction: { race: Race } } | null; announcement: { version: number; race: Race } | null; freeReportVersion: { version: number; kind: string; race: Race } | null }; attempts: Attempt[] };
type Response = { items: Delivery[]; total: number; page: number; limit: number; counts: Record<string, number>; webhook: { lastReceivedAt: string | null; lastEventType: string | null; lastOutcome: string | null; received24h: number; unmatched24h: number; blockedAccounts: number } };
const labels: Record<string, string> = { QUEUED: '送信待ち', SENDING: '送信中', SENT: '送信済み', FAILED: '失敗', SKIPPED: '対象外', TRANSIENT_FAILURE: '一時失敗', PERMANENT_FAILURE: '恒久失敗' };
const formatDate = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date(value));
async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> { const response = await fetch(`/api/v1/${path}`, { method, headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '処理に失敗しました。'); return result as T; }

export function AdminNotifications() {
  const [data, setData] = useState<Response>({ items: [], total: 0, page: 1, limit: 20, counts: {}, webhook: { lastReceivedAt: null, lastEventType: null, lastOutcome: null, received24h: 0, unmatched24h: 0, blockedAccounts: 0 } });
  const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const [reasons, setReasons] = useState<Record<string, string>>({}); const [busy, setBusy] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await api<Response>(`admin/notifications?page=${page}${status ? `&status=${status}` : ''}`)); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, [page, status]);
  useEffect(() => { void load(); }, [load]);
  async function retry(id: string) { setBusy(id); setError(''); setMessage(''); try { await api(`admin/notifications/${id}/retry`, 'POST', { reason: reasons[id] ?? '' }); setMessage('再送を受け付けました。次回のワーカー実行で処理します。'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  return <><div className="page-heading"><span className="eyebrow">NOTIFICATION OPERATIONS</span><h1>通知運用</h1><p>公開通知の配送状況と試行履歴を確認し、失敗した通知を再送できます。</p></div>
    {error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <section className="panel webhook-health"><div><span>Webhook最終受信</span><strong>{data.webhook.lastReceivedAt ? formatDate(data.webhook.lastReceivedAt) : '未受信'}</strong><small>{data.webhook.lastEventType ? `${data.webhook.lastEventType} · ${data.webhook.lastOutcome}` : 'LINE Developers側との疎通確認前です。'}</small></div><div><span>24時間の受信</span><strong>{data.webhook.received24h}件</strong><small>未照合 {data.webhook.unmatched24h}件</small></div><div><span>通知不可アカウント</span><strong>{data.webhook.blockedAccounts}件</strong><small>unfollow／ブロックを反映</small></div></section>
    <div className="notification-counts">{['QUEUED', 'SENDING', 'SENT', 'FAILED', 'SKIPPED'].map(key => <button key={key} className={status === key ? 'selected' : ''} onClick={() => { setStatus(status === key ? '' : key); setPage(1); }}><span>{labels[key]}</span><strong>{data.counts[key] ?? 0}</strong></button>)}</div>
    <section className="panel"><div className="panel-heading"><div><h2>配送一覧</h2><span className="muted">受信者単位 · 全{data.total}件</span></div><button className="button secondary small" onClick={() => void load()} disabled={loading}><RefreshCw size={16} />更新</button></div>
      {loading ? <p className="loading panel-body" role="status">読み込み中…</p> : data.items.length === 0 ? <div className="empty"><h3>対象の通知はありません</h3><p>レース告知または予想公開後にワーカーが宛先を確定すると表示されます。</p></div> : <div className="notification-list">{data.items.map(item => { const target = item.event.version ?? item.event.announcement ?? item.event.freeReportVersion!; const race = item.event.version?.prediction.race ?? item.event.announcement?.race ?? item.event.freeReportVersion!.race; const detail = item.event.eventType === 'RACE_ANNOUNCED' ? `対象レース告知 第${target.version}版` : item.event.freeReportVersion ? `${item.event.freeReportVersion.kind === 'PRE_RACE' ? '無料速報' : 'レース後検証'} 第${target.version}版` : `予想 第${target.version}版 · ${item.event.version!.visibility}`; return <article className="notification-item" key={item.id}><div className="notification-main"><div><span className={`status-tag ${item.status === 'FAILED' ? 'warning' : ''}`}>{labels[item.status] ?? item.status}</span><strong>{race.venue} {race.number}R {race.name}</strong><small>{race.raceDate} · {detail}</small></div><div><strong>{item.user.displayName}</strong><small>{item.user.email ?? 'LINE登録'}</small></div><div><strong>{item.attemptCount}回</strong><small>{item.sentAt ? `${formatDate(item.sentAt)} 送信` : item.lastErrorCode ?? `次回 ${formatDate(item.nextAttemptAt)}`}</small></div></div>
        {item.attempts.length > 0 && <details><summary>試行履歴を表示</summary><ul>{item.attempts.map(attempt => <li key={attempt.id}>#{attempt.attemptNumber} {labels[attempt.outcome] ?? attempt.outcome} · {formatDate(attempt.finishedAt)}{attempt.errorCode ? ` · ${attempt.errorCode}` : ''}</li>)}</ul></details>}
        {item.status === 'FAILED' && <div className="retry-row"><label className="field">再送理由<input value={reasons[item.id] ?? ''} maxLength={500} onChange={event => setReasons({ ...reasons, [item.id]: event.target.value })} placeholder="障害復旧を確認したため" /></label><button className="button small" disabled={busy === item.id || !(reasons[item.id] ?? '').trim()} onClick={() => void retry(item.id)}><RotateCcw size={16} />{busy === item.id ? '受付中…' : '再送する'}</button></div>}
      </article>; })}</div>}
      <div className="pagination"><span>{page}ページ</span><button className="button secondary small" disabled={page <= 1} onClick={() => setPage(page - 1)}>前へ</button><button className="button secondary small" disabled={page * data.limit >= data.total} onClick={() => setPage(page + 1)}>次へ</button></div>
    </section></>;
}
