'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Gift, ShieldAlert, Users } from 'lucide-react';

type Item = { user: { id: string; displayName: string; referralCode: string }; referralCount: number; achievedMilestones: number[]; rewardsGranted: number };
type Recent = { id: string; status: string; createdAt: string; qualifiedAt: string | null; invalidatedAt: string | null; referrer: { displayName: string }; referred: { displayName: string; registrationMethod: string } };
type ListData = { summary: { qualifiedReferrals: number; referrers: number; milestoneAchievements: { requiredReferralCount: number; users: number }[]; rewardsGranted: number; rewardsUsed: number }; items: Item[]; recentReferrals: Recent[]; page: number; total: number };
type Detail = Recent & { invalidatedReason: string | null; referrer: { id: string; displayName: string; referralCode: string }; referred: { id: string; displayName: string; registrationMethod: string; createdAt: string }; invalidatedBy: { id: string; displayName: string } | null };
async function request<T>(path: string, method = 'GET', body?: unknown): Promise<T> { const response = await fetch(`/api/v1/${path}`, { method, headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '処理に失敗しました。'); return result as T; }
const format = (value: string | null) => value ? new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const labels: Record<string, string> = { PENDING: '本人確認待ち', QUALIFIED: '成立', INVALIDATED: '無効' };

export function AdminReferrals() {
  const [data, setData] = useState<ListData | null>(null); const [status, setStatus] = useState('ALL'); const [page, setPage] = useState(1); const [detail, setDetail] = useState<Detail | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(''); try { setData(await request<ListData>(`admin/referrals?page=${page}&status=${status}`)); } catch (e) { setError((e as Error).message); } }, [page, status]);
  useEffect(() => { void load(); }, [load]);
  async function open(id: string) { setError(''); try { setDetail(await request<Detail>(`admin/referrals/${id}`)); setReason(''); } catch (e) { setError((e as Error).message); } }
  async function invalidate(event: FormEvent) { event.preventDefault(); if (!detail) return; setBusy(true); setError(''); setMessage(''); try { await request(`admin/referrals/${detail.id}/invalidate`, 'POST', { reason }); setMessage('紹介を無効化し、未使用特典を安全に再計算しました。'); setDetail(await request<Detail>(`admin/referrals/${detail.id}`)); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><div className="page-heading"><span className="eyebrow">REFERRAL OPERATIONS</span><h1>紹介管理</h1><p>紹介成立、特典付与、利用状況を確認します。不正登録の無効化は理由と監査履歴を残します。</p></div>{error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    {!data ? <p role="status">紹介状況を読み込み中…</p> : <>
      <div className="stats-grid referral-admin-stats">{[['紹介経由登録', data.summary.qualifiedReferrals, '人'], ['紹介者', data.summary.referrers, '人'], ...data.summary.milestoneAchievements.map(item => [`${item.requiredReferralCount}人達成`, item.users, '人']), ['特典付与', data.summary.rewardsGranted, '枚'], ['特典使用', data.summary.rewardsUsed, '枚']].map(([label, count, unit]) => <section className="stat" key={String(label)}><span>{label}</span><strong>{count}<small>{unit}</small></strong></section>)}</div>
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">REFERRERS</span><h2>紹介者別</h2></div><Gift size={21} /></div>{data.items.length ? <div className="table-scroll"><table><thead><tr><th>User</th><th>紹介コード</th><th>成立人数</th><th>達成</th><th>付与特典</th></tr></thead><tbody>{data.items.map(item => <tr key={item.user.id}><td>{item.user.displayName}</td><td className="mono">{item.user.referralCode}</td><td>{item.referralCount}人</td><td>{item.achievedMilestones.length ? item.achievedMilestones.sort((a,b) => a-b).map(value => `${value}人`).join('・') : '—'}</td><td>{item.rewardsGranted}枚</td></tr>)}</tbody></table></div> : <div className="panel-body"><p className="muted">紹介者はまだいません。</p></div>}<div className="pagination"><span>全{data.total}人 · {page}ページ</span><button className="button secondary small" disabled={page <= 1} onClick={() => setPage(page - 1)}>前へ</button><button className="button secondary small" disabled={page * 20 >= data.total} onClick={() => setPage(page + 1)}>次へ</button></div></section>
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">REFERRALS</span><h2>紹介記録</h2></div><label className="compact-filter">状態<select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="ALL">すべて</option><option value="PENDING">本人確認待ち</option><option value="QUALIFIED">成立</option><option value="INVALIDATED">無効</option></select></label></div>{data.recentReferrals.length ? <div className="referral-admin-list">{data.recentReferrals.map(row => <button type="button" key={row.id} onClick={() => void open(row.id)}><Users size={19} /><span><strong>{row.referrer.displayName} → {row.referred.displayName}</strong><small>{row.referred.registrationMethod}登録 · {format(row.qualifiedAt ?? row.createdAt)}</small></span><b>{labels[row.status] ?? row.status}</b></button>)}</div> : <div className="panel-body"><p className="muted">該当する紹介記録はありません。</p></div>}</section>
    </>}
    {detail && <section className="panel referral-detail"><div className="panel-heading"><div><span className="eyebrow">DETAIL</span><h2>紹介詳細</h2></div><button className="text-link" onClick={() => setDetail(null)}>閉じる</button></div><dl><div><dt>紹介者</dt><dd>{detail.referrer.displayName}<small>{detail.referrer.referralCode}</small></dd></div><div><dt>被紹介者</dt><dd>{detail.referred.displayName}<small>{detail.referred.registrationMethod}登録</small></dd></div><div><dt>登録日時</dt><dd>{format(detail.referred.createdAt)}</dd></div><div><dt>紹介成立日時</dt><dd>{format(detail.qualifiedAt)}</dd></div><div><dt>状態</dt><dd>{labels[detail.status] ?? detail.status}</dd></div>{detail.invalidatedReason && <div><dt>無効化理由</dt><dd>{detail.invalidatedReason}</dd></div>}</dl>{detail.status === 'QUALIFIED' && <form className="referral-invalidate" onSubmit={event => void invalidate(event)}><ShieldAlert size={22} /><div><strong>不正登録として無効化</strong><p>未使用の紹介特典だけを無効化します。使用済みの一日利用権は巻き戻しません。</p><label>理由<textarea value={reason} onChange={event => setReason(event.target.value)} maxLength={500} required /></label></div><button className="button danger" disabled={busy}>{busy ? '処理中…' : '無効化する'}</button></form>}</section>}
  </>;
}
