'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { RefreshCw, RotateCcw } from 'lucide-react';

type Attempt = { id: string; attemptNumber: number; outcome: string; errorCode: string | null; finishedAt: string };
type Race = { raceDate: string; venue: string; number: number; name: string };
type Delivery = { id: string; channel: 'LINE' | 'EMAIL'; status: string; attemptCount: number; manualRetryCount: number; nextAttemptAt: string; lastErrorCode: string | null; sentAt: string | null; user: { displayName: string; email: string | null }; event: { eventType: string; version: { version: number; visibility: string; prediction: { race: Race } } | null; announcement: { version: number; race: Race } | null; freeReportVersion: { version: number; kind: string; race: Race } | null; productVersion: { version: number; accessScope: string; product: { id: string; targetDate: string; title: string } } | null; raceResultVersion: { version: number; race: Race } | null; win5EvaluationVersion: { version: number; product: { id: string; targetDate: string; title: string } } | null }; attempts: Attempt[] };
type EmailWebhook = { id: string; eventType: string; occurredAt: string; receivedAt: string; recipientCount: number; matchedCount: number; disabledCount: number; outcome: string };
type BlockedEmailMember = { id: string; displayName: string; email: string | null; emailDeliveryDisabledAt: string; emailDeliveryDisabledReason: string };
type Response = { items: Delivery[]; total: number; page: number; limit: number; raceId: string | null; counts: Record<string, number>; webhook: { lastReceivedAt: string | null; lastEventType: string | null; lastOutcome: string | null; received24h: number; unmatched24h: number; blockedAccounts: number }; emailWebhook: { lastReceivedAt: string | null; lastEventType: string | null; lastOutcome: string | null; received24h: number; actionRequired24h: number; blockedAccounts: number; recent: EmailWebhook[]; blockedMembers: BlockedEmailMember[] } };
type TestContentType = 'RACE_PREDICTION' | 'WIN5_PREDICTION' | 'BILLING_PAYMENT_SUCCEEDED' | 'BILLING_PAYMENT_FAILED' | 'BILLING_PAYMENT_RECOVERED' | 'BILLING_CANCELLATION_SCHEDULED' | 'BILLING_SUBSCRIPTION_ENDED';
type TestOptions = {
  channels: { email: boolean; line: boolean };
  races: { id: string; raceDate: string; venue: string; number: number; name: string }[];
  products: { id: string; targetDate: string; title: string; status: string }[];
  subscriptions: { id: string; planCode: string; status: string; currentPeriodEndsAt: string; user: { displayName: string } }[];
};
const labels: Record<string, string> = { QUEUED: '送信待ち', SENDING: '送信中', SENT: '送信済み', FAILED: '失敗', SKIPPED: '対象外', TRANSIENT_FAILURE: '一時失敗', PERMANENT_FAILURE: '恒久失敗' };
const formatDate = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date(value));
async function api<T>(path: string, method = 'GET', body?: unknown, idempotent = false): Promise<T> { const response = await fetch(`/api/v1/${path}`, { method, headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), ...(idempotent ? { 'Idempotency-Key': crypto.randomUUID() } : {}) }, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '処理に失敗しました。'); return result as T; }

export function AdminNotifications({ canTest }: { canTest: boolean }) {
  const search = useSearchParams(); const raceId = search.get('raceId') ?? '';
  const [data, setData] = useState<Response>({ items: [], total: 0, page: 1, limit: 20, raceId: null, counts: {}, webhook: { lastReceivedAt: null, lastEventType: null, lastOutcome: null, received24h: 0, unmatched24h: 0, blockedAccounts: 0 }, emailWebhook: { lastReceivedAt: null, lastEventType: null, lastOutcome: null, received24h: 0, actionRequired24h: 0, blockedAccounts: 0, recent: [], blockedMembers: [] } });
  const [status, setStatus] = useState(''); const [channel, setChannel] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const [reasons, setReasons] = useState<Record<string, string>>({}); const [busy, setBusy] = useState('');
  const [testOptions, setTestOptions] = useState<TestOptions | null>(null); const [testType, setTestType] = useState<TestContentType>('RACE_PREDICTION'); const [testTarget, setTestTarget] = useState(''); const [testReason, setTestReason] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await api<Response>(`admin/notifications?page=${page}${status ? `&status=${status}` : ''}${channel ? `&channel=${channel}` : ''}${raceId ? `&raceId=${raceId}` : ''}`)); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, [page, status, channel, raceId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (canTest) void api<TestOptions>('admin/notifications/test-options').then(setTestOptions).catch(e => setError((e as Error).message)); }, [canTest]);
  async function retry(id: string) { setBusy(id); setError(''); setMessage(''); try { await api(`admin/notifications/${id}/retry`, 'POST', { reason: reasons[id] ?? '' }); setMessage('再送を受け付けました。次回のワーカー実行で処理します。'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function releaseEmailBlock(id: string) { setBusy(id); setError(''); setMessage(''); try { await api(`admin/notifications/email-blocks/${id}/release`, 'POST', { reason: reasons[id] ?? '' }); setMessage('配信停止を解除しました。会員本人がメール通知を再度有効にするまで送信されません。'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function sendOperationalTest(channel: 'EMAIL' | 'LINE') {
    setBusy(`test-${channel}`); setError(''); setMessage('');
    try {
      if (!testTarget) throw new Error('テスト対象を選択してください。');
      if (!testReason.trim()) throw new Error('テスト理由を入力してください。');
      const target = testType === 'RACE_PREDICTION' ? { raceId: testTarget } : testType === 'WIN5_PREDICTION' ? { productId: testTarget } : { subscriptionId: testTarget };
      const result = await api<{ status: 'SIMULATED' | 'SENT'; contentLabel: string }>('admin/notifications/test-send', 'POST', { contentType: testType, ...target, channel, reason: testReason }, true);
      setMessage(`${result.contentLabel}の${channel === 'EMAIL' ? 'メール' : 'LINE'}${result.status === 'SIMULATED' ? '模擬' : ''}テスト送信が完了しました。`);
    } catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  const testTargets = testType === 'RACE_PREDICTION' ? testOptions?.races.map(item => ({ id: item.id, label: `${item.raceDate} ${item.venue} ${item.number}R ${item.name}` })) ?? []
    : testType === 'WIN5_PREDICTION' ? testOptions?.products.map(item => ({ id: item.id, label: `${item.targetDate} ${item.title} · ${item.status}` })) ?? []
      : testOptions?.subscriptions.map(item => ({ id: item.id, label: `${item.user.displayName} · ${item.planCode} · ${item.status}` })) ?? [];
  return <><div className="page-heading"><span className="eyebrow">NOTIFICATION OPERATIONS</span><h1>通知運用</h1><p>予想公開・評価結果通知の配送状況と試行履歴を確認し、失敗した通知を再送できます。</p></div>
    {error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    {canTest && <section className="panel"><div className="panel-heading"><div><h2>管理者本人へ通知テスト</h2><span className="muted">会員への公開・一斉配信・契約変更は行いません。</span></div></div><div className="panel-body"><div className="race-form-grid"><label className="field">通知種別<select value={testType} onChange={event => { setTestType(event.target.value as TestContentType); setTestTarget(''); }}><option value="RACE_PREDICTION">パドック直前予想の公開</option><option value="WIN5_PREDICTION">WIN5紙面予想の公開</option><option value="BILLING_PAYMENT_SUCCEEDED">支払成功</option><option value="BILLING_PAYMENT_FAILED">支払失敗</option><option value="BILLING_PAYMENT_RECOVERED">支払回復</option><option value="BILLING_CANCELLATION_SCHEDULED">解約予約</option><option value="BILLING_SUBSCRIPTION_ENDED">契約終了</option></select></label><label className="field">テスト対象<select value={testTarget} onChange={event => setTestTarget(event.target.value)}><option value="">選択してください</option>{testTargets.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label></div><label className="field">テスト理由<input value={testReason} maxLength={500} onChange={event => setTestReason(event.target.value)} placeholder="公開前に通知文面を確認するため" /></label><div className="panel-actions"><button className="button secondary" disabled={!testOptions?.channels.line || !!busy || !testTarget || !testReason.trim()} onClick={() => void sendOperationalTest('LINE')}>LINEへテスト送信</button><button className="button" disabled={!testOptions?.channels.email || !!busy || !testTarget || !testReason.trim()} onClick={() => void sendOperationalTest('EMAIL')}>メールへテスト送信</button></div>{testOptions && !testOptions.channels.line && !testOptions.channels.email && <div className="notice error">管理者本人の確認済みメールまたはLINE連携と、通知設定を確認してください。</div>}</div></section>}
    {raceId && <div className="notice notification-race-filter" role="status"><span>配信結果で選択したレースだけを表示しています。</span><Link className="text-link" href="/admin/notifications">絞り込みを解除</Link></div>}
    <section className="panel webhook-health"><div><span>LINE Webhook最終受信</span><strong>{data.webhook.lastReceivedAt ? formatDate(data.webhook.lastReceivedAt) : '未受信'}</strong><small>{data.webhook.lastEventType ? `${data.webhook.lastEventType} · ${data.webhook.lastOutcome}` : 'LINE Developers側との疎通確認前です。'}</small></div><div><span>24時間のLINE受信</span><strong>{data.webhook.received24h}件</strong><small>未照合 {data.webhook.unmatched24h}件</small></div><div><span>LINE通知不可</span><strong>{data.webhook.blockedAccounts}件</strong><small>unfollow／ブロックを反映</small></div></section>
    <section className="panel webhook-health"><div><span>メールWebhook最終受信</span><strong>{data.emailWebhook.lastReceivedAt ? formatDate(data.emailWebhook.lastReceivedAt) : '未受信'}</strong><small>{data.emailWebhook.lastEventType ? `${data.emailWebhook.lastEventType} · ${data.emailWebhook.lastOutcome}` : 'Resend側との疎通確認前です。'}</small></div><div><span>24時間の要確認</span><strong>{data.emailWebhook.actionRequired24h}件</strong><small>全受信 {data.emailWebhook.received24h}件</small></div><div><span>メール通知停止</span><strong>{data.emailWebhook.blockedAccounts}件</strong><small>バウンス／苦情／抑止を反映</small></div></section>
    {(data.emailWebhook.recent.length > 0 || data.emailWebhook.blockedMembers.length > 0) && <section className="panel"><div className="panel-heading"><div><h2>メール配信異常</h2><span className="muted">宛先本文やResend資格情報は保存しません。</span></div></div><div className="panel-body"><h3>停止中の会員</h3>{data.emailWebhook.blockedMembers.length ? <div className="notification-list">{data.emailWebhook.blockedMembers.map(member => <article className="notification-item" key={member.id}><div className="notification-main"><div><strong>{member.displayName}</strong><small>{member.email ?? 'メール未設定'}</small></div><div><strong>{member.emailDeliveryDisabledReason}</strong><small>{formatDate(member.emailDeliveryDisabledAt)}</small></div></div><div className="retry-row"><label className="field">解除理由<input value={reasons[member.id] ?? ''} maxLength={500} onChange={event => setReasons({ ...reasons, [member.id]: event.target.value })} placeholder="本人が受信可能な状態を確認したため" /></label><button className="button small" disabled={busy === member.id || !(reasons[member.id] ?? '').trim()} onClick={() => void releaseEmailBlock(member.id)}><RotateCcw size={16} />{busy === member.id ? '解除中…' : '停止を解除'}</button></div></article>)}</div> : <p className="muted">停止中の会員はいません。</p>}<h3>最近のWebhook</h3>{data.emailWebhook.recent.length ? <ul>{data.emailWebhook.recent.map(event => <li key={event.id}>{formatDate(event.receivedAt)} · {event.eventType} · {event.outcome} · 対象{event.recipientCount}／照合{event.matchedCount}／停止{event.disabledCount}</li>)}</ul> : <p className="muted">受信履歴はありません。</p>}</div></section>}
    <div className="notification-counts">{['QUEUED', 'SENDING', 'SENT', 'FAILED', 'SKIPPED'].map(key => <button key={key} className={status === key ? 'selected' : ''} onClick={() => { setStatus(status === key ? '' : key); setPage(1); }}><span>{labels[key]}</span><strong>{data.counts[key] ?? 0}</strong></button>)}</div>
    <div className="filter-row" aria-label="通知チャネル"><button className={`button secondary small ${channel === '' ? 'selected' : ''}`} onClick={() => { setChannel(''); setPage(1); }}>すべて</button><button className={`button secondary small ${channel === 'EMAIL' ? 'selected' : ''}`} onClick={() => { setChannel('EMAIL'); setPage(1); }}>メール</button><button className={`button secondary small ${channel === 'LINE' ? 'selected' : ''}`} onClick={() => { setChannel('LINE'); setPage(1); }}>LINE</button></div>
    <section className="panel"><div className="panel-heading"><div><h2>配送一覧</h2><span className="muted">受信者単位 · 全{data.total}件</span></div><button className="button secondary small" onClick={() => void load()} disabled={loading}><RefreshCw size={16} />更新</button></div>
      {loading ? <p className="loading panel-body" role="status">読み込み中…</p> : data.items.length === 0 ? <div className="empty"><h3>対象の通知はありません</h3><p>レース告知、予想公開、評価結果確定後にワーカーが宛先を確定すると表示されます。</p></div> : <div className="notification-list">{data.items.map(item => { const target = item.event.version ?? item.event.announcement ?? item.event.freeReportVersion ?? item.event.productVersion ?? item.event.raceResultVersion ?? item.event.win5EvaluationVersion!; const race = item.event.version?.prediction.race ?? item.event.announcement?.race ?? item.event.freeReportVersion?.race ?? item.event.raceResultVersion?.race; const product = item.event.productVersion?.product ?? item.event.win5EvaluationVersion?.product; const detail = item.event.win5EvaluationVersion ? `WIN5評価結果 第${target.version}版` : item.event.raceResultVersion ? `パドック評価結果 第${target.version}版` : item.event.productVersion ? `WIN5紙面 第${target.version}版 · ${item.event.productVersion.accessScope}` : item.event.eventType === 'RACE_ANNOUNCED' ? `対象レース告知 第${target.version}版` : item.event.freeReportVersion ? `${item.event.freeReportVersion.kind === 'PRE_RACE' ? '無料速報' : 'レース後検証'} 第${target.version}版` : `予想 第${target.version}版 · ${item.event.version!.visibility}`; return <article className="notification-item" key={item.id}><div className="notification-main"><div><span className={`status-tag ${item.status === 'FAILED' ? 'warning' : ''}`}>{labels[item.status] ?? item.status}</span> <span className="status-tag">{item.channel === 'EMAIL' ? 'メール' : 'LINE'}</span><strong>{product ? product.title : `${race!.venue} ${race!.number}R ${race!.name}`}</strong><small>{product?.targetDate ?? race!.raceDate} · {detail}</small></div><div><strong>{item.user.displayName}</strong><small>{item.user.email ?? 'LINE登録'}</small></div><div><strong>{item.attemptCount}回</strong><small>{item.sentAt ? `${formatDate(item.sentAt)} 送信` : item.lastErrorCode ?? `次回 ${formatDate(item.nextAttemptAt)}`}</small></div></div>
        {item.attempts.length > 0 && <details><summary>試行履歴を表示</summary><ul>{item.attempts.map(attempt => <li key={attempt.id}>#{attempt.attemptNumber} {labels[attempt.outcome] ?? attempt.outcome} · {formatDate(attempt.finishedAt)}{attempt.errorCode ? ` · ${attempt.errorCode}` : ''}</li>)}</ul></details>}
        {item.status === 'FAILED' && <div className="retry-row"><label className="field">再送理由<input value={reasons[item.id] ?? ''} maxLength={500} onChange={event => setReasons({ ...reasons, [item.id]: event.target.value })} placeholder="障害復旧を確認したため" /></label><button className="button small" disabled={busy === item.id || !(reasons[item.id] ?? '').trim()} onClick={() => void retry(item.id)}><RotateCcw size={16} />{busy === item.id ? '受付中…' : '再送する'}</button></div>}
      </article>; })}</div>}
      <div className="pagination"><span>{page}ページ</span><button className="button secondary small" disabled={page <= 1} onClick={() => setPage(page - 1)}>前へ</button><button className="button secondary small" disabled={page * data.limit >= data.total} onClick={() => setPage(page + 1)}>次へ</button></div>
    </section></>;
}
