'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, CreditCard, ShieldCheck } from 'lucide-react';

type Plan = { code: 'FOUNDER' | 'STANDARD' | 'DAY_PASS'; name: string; priceYen: number; interval: string; available: boolean; remaining?: number };
type BillingData = {
  billingTransport?: 'test' | 'stripe';
  subscriptions: { id: string; planCode: string; status: string; priceYen: number; currentPeriodEndsAt: string; graceEndsAt: string | null; cancelAtPeriodEnd: boolean; user?: { email: string; displayName: string } }[];
  dayPasses: { id: string; raceDate: string; status: string; priceYen: number; user?: { email: string; displayName: string } }[];
  payments: { id: string; kind: string; status: string; amountYen: number; occurredAt: string; user?: { email: string; displayName: string } }[];
  checkouts?: { id: string; kind: string; planCode: string; raceDate: string | null; amountYen: number; status: string; createdAt: string; expiresAt: string; completedAt: string | null; user: { email: string; displayName: string } }[];
  stripeWebhooks?: { id: string; providerEventId: string; eventType: string; livemode: boolean; outcome: string; receivedAt: string }[];
  supportRequests: { id: string; paymentTransactionId?: string | null; category: 'REFUND' | 'RECEIPT' | 'PAYMENT_FAILURE' | 'CANCELLATION' | 'OTHER'; message: string; status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED'; createdAt: string; updatedAt: string; user?: { email: string | null; displayName: string }; paymentTransaction?: { id: string; kind: string; status: string; amountYen: number; occurredAt: string } | null; events: { id?: string; eventType: string; actorRole?: string; reason?: string; occurredAt: string }[] }[];
};
const supportCategoryLabels = { REFUND: '返金について', RECEIPT: '領収書について', PAYMENT_FAILURE: '支払い失敗について', CANCELLATION: '解約について', OTHER: 'その他の請求問い合わせ' } as const;
const supportStatusLabels = { OPEN: '受付済み', IN_PROGRESS: '対応中', RESOLVED: '解決済み' } as const;
const money = (value: number) => new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(value);
const date = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
async function request<T>(path: string, method = 'GET', body?: unknown, idempotent = false): Promise<T> {
  const response = await fetch(`/api/v1/${path}`, { method, cache: 'no-store', headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), ...(idempotent ? { 'Idempotency-Key': crypto.randomUUID() } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '処理に失敗しました。'); return result;
}
function Notice({ value, error = false }: { value: string; error?: boolean }) { return value ? <div className={`notice ${error ? 'error' : ''}`} role={error ? 'alert' : 'status'}>{value}</div> : null; }

export function PlansPage({ loggedIn, purchaseReady, refresh }: { loggedIn: boolean; purchaseReady: boolean; refresh: () => Promise<void> }) {
  const search = useSearchParams();
  const [plans, setPlans] = useState<Plan[]>([]); const [enabled, setEnabled] = useState(false); const [raceDate, setRaceDate] = useState(() => search.get('date') ?? '');
  const [transport, setTransport] = useState<'test' | 'stripe'>('test');
  const [stripeMode, setStripeMode] = useState<'TEST' | 'LIVE' | null>(null);
  const [selected, setSelected] = useState<Plan | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { request<{ plans: Plan[]; newPurchasesEnabled: boolean; billingTransport: 'test' | 'stripe'; stripeMode: 'TEST' | 'LIVE' | null }>('billing/plans').then(v => { setPlans(v.plans); setEnabled(v.newPurchasesEnabled); setTransport(v.billingTransport); setStripeMode(v.stripeMode); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (loggedIn) void request('me/journey', 'POST', { eventType: 'PLAN_VIEWED' }).catch(() => undefined); }, [loggedIn]);
  useEffect(() => { if (selected) document.getElementById('plan-review')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, [selected]);
  async function buy(plan: Plan) { setBusy(true); setError(''); setMessage(''); try {
    const result = plan.code === 'DAY_PASS'
      ? (raceDate ? await request<{ checkoutUrl?: string }>('billing/day-pass', 'POST', { raceDate }, true) : (() => { throw new Error('利用する開催日を選択してください。'); })())
      : await request<{ checkoutUrl?: string }>('billing/checkout', 'POST', { planCode: plan.code }, true);
    if (result.checkoutUrl) { window.location.assign(result.checkoutUrl); return; }
    await refresh(); setSelected(null); setMessage(`${plan.name}のテスト申込を登録しました。実際の請求はありません。`);
  } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const stripeTest = transport === 'stripe' && stripeMode === 'TEST';
  return <><div className="page-heading"><span className="eyebrow">MEMBERSHIP</span><h1>料金プラン</h1><p>{stripeTest ? 'Stripeのテストカードで申込から閲覧までを確認するサンドボックスです。' : transport === 'stripe' ? '公開された有料予想を閲覧するための料金プランです。' : '有料会員の申込から閲覧までを、請求なしで確認するテストプランです。'}</p></div><Notice value={error} error /><Notice value={message} />
    {stripeTest && <div className="notice error" role="alert"><strong>Stripeテスト環境です。</strong> 実在するカード情報は入力せず、Stripe公式のテストカードだけを使用してください。実際の請求は発生しません。</div>}
    <div className="notice">表示価格は税込の開発初期値です。{transport === 'stripe' ? `申込時はStripeの${stripeTest ? 'テスト' : '本番'}決済画面へ移動し、署名済みWebhookの確認後に閲覧権限を反映します。` : 'この画面では外部決済やカード情報の入力を行いません。'}</div>
    {loggedIn && !purchaseReady && <div className="notice error">申込前にマイページでメールアドレスの確認を完了してください。 <Link className="text-link" href="/account">確認する</Link></div>}
    <div className="plan-grid">{plans.map(plan => <section className="panel plan-card" key={plan.code}><div className="panel-body"><span className="eyebrow">{plan.interval === 'MONTH' ? 'MONTHLY' : 'ONE DAY'}</span><h2>{plan.name}</h2><strong className="plan-price">{money(plan.priceYen)}<small>{plan.interval === 'MONTH' ? '／月' : '／開催日'}</small></strong><p>{plan.code === 'DAY_PASS' ? 'WIN5商品がある日は初版公開時から翌日0:00まで閲覧できます。商品がない日は指定日の0:00開始です。' : transport === 'stripe' ? 'Stripeの請求期間で月次更新します。解約予約後も支払済み期間の終了まで閲覧できます。' : '申込日時から1か月間。解約予約後も支払済み期間の終了まで閲覧できます。'}</p>{plan.code === 'FOUNDER' && <small>残り枠：{plan.remaining ?? 0}</small>}
      {plan.code === 'DAY_PASS' && <label className="field">利用する開催日<input type="date" value={raceDate} min={new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' })} onChange={e => setRaceDate(e.target.value)} /></label>}
      {loggedIn ? <button className="button full" disabled={busy || !purchaseReady || (plan.code === 'DAY_PASS' && !raceDate)} onClick={() => { setError(''); setMessage(''); setSelected(plan); void request('me/journey', 'POST', { eventType: 'CHECKOUT_REVIEWED' }).catch(() => undefined); }}>{!purchaseReady ? 'メール確認後に確認可能' : plan.code === 'DAY_PASS' && !raceDate ? '開催日を選択' : '申込内容を確認'}<ArrowRight size={17} /></button> : <Link className="button full" href="/login">ログインして申し込む<ArrowRight size={17} /></Link>}</div></section>)}</div>
    {selected && <section className="panel plan-review" id="plan-review" aria-live="polite"><div className="panel-heading"><div><span className="eyebrow">APPLICATION REVIEW</span><h2>申込内容の確認</h2></div><ShieldCheck size={20} /></div><div className="panel-body"><dl className="review-details"><div><dt>プラン</dt><dd>{selected.name}</dd></div><div><dt>料金</dt><dd>{money(selected.priceYen)}{selected.interval === 'MONTH' ? '／月' : '／開催日'}</dd></div>{selected.code === 'DAY_PASS' && <div><dt>利用日</dt><dd>{raceDate}</dd></div>}<div><dt>利用期間</dt><dd>{selected.interval === 'MONTH' ? transport === 'stripe' ? 'Stripeの請求期間に従って月次更新' : '申込日時から1か月間' : 'WIN5商品がある日は初版公開時から翌日0:00まで。商品がない日は指定日0:00から開始'}</dd></div></dl>{(!enabled || !selected.available) && <div className="notice error">このプランは現在、新規申込を受け付けていません。内容は確認できます。</div>}<div className="notice">{stripeTest ? 'Stripeのテスト決済画面へ移動します。Stripe公式のテストカードだけを使用してください。' : transport === 'stripe' ? 'Stripeの決済画面へ移動します。カード情報は本サービスのDBへ保存しません。' : 'クラウド試験・開発環境のテスト申込です。外部への請求やカード情報の送信はありません。'}</div><div className="review-actions"><button className="button secondary" disabled={busy} onClick={() => setSelected(null)}>プラン選択へ戻る</button><button className="button" disabled={busy || !enabled || !selected.available} onClick={() => void buy(selected)}>{busy ? '処理中…' : !enabled ? '新規購入を停止中' : !selected.available ? '現在は申込できません' : stripeTest ? 'Stripeテスト決済へ進む' : transport === 'stripe' ? '内容を確認して申し込む' : '請求なしでテスト申込する'}<ArrowRight size={17} /></button></div></div></section>}
    <section className="panel billing-terms"><div className="panel-heading"><h2>申込前の確認</h2><ShieldCheck size={20} /></div><div className="panel-body"><p>自動更新、正式な解約期限、返金条件、事業者情報は未確定です。本番提供前に正式な条件と同意画面へ置き換えます。</p></div></section></>;
}

export function BillingAccount() {
  const [data, setData] = useState<BillingData | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [supportCategory, setSupportCategory] = useState<keyof typeof supportCategoryLabels>('PAYMENT_FAILURE'); const [supportPaymentId, setSupportPaymentId] = useState(''); const [supportMessage, setSupportMessage] = useState(''); const [supportBusy, setSupportBusy] = useState(false);
  const load = () => request<BillingData>('billing/me').then(setData).catch(e => setError(e.message));
  useEffect(() => { void load(); }, []);
  async function cancel(id: string) { setError(''); try { await request(`billing/subscriptions/${id}/cancel`, 'POST'); setMessage('次回更新を停止しました。支払済み期間の終了まで閲覧できます。'); await load(); } catch (e) { setError((e as Error).message); } }
  async function createSupportRequest() { setError(''); setMessage(''); setSupportBusy(true); try {
    const needsPayment = supportCategory === 'REFUND' || supportCategory === 'RECEIPT';
    if (needsPayment && !supportPaymentId) throw new Error('対象の支払いを選択してください。');
    await request('billing/support-requests', 'POST', { category: supportCategory, paymentTransactionId: supportPaymentId || null, message: supportMessage }, true);
    setSupportMessage(''); setSupportPaymentId(''); setMessage('請求に関する問い合わせを受け付けました。'); await load();
  } catch (e) { setError((e as Error).message); } finally { setSupportBusy(false); } }
  return <section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">BILLING</span><h2>契約・お支払い履歴</h2></div><CreditCard size={20} /></div><div className="panel-body"><Notice value={error} error /><Notice value={message} />{!data ? <p>読み込み中…</p> : <>
    {!data.subscriptions.length && !data.dayPasses.length ? <p className="muted">契約はありません。 <Link className="text-link" href="/plans">料金プランを見る</Link></p> : <div className="billing-contracts">{data.subscriptions.map(s => <div className="billing-contract" key={s.id}><div><strong>{s.planCode} 月額契約</strong><small>{money(s.priceYen)} · {s.status} · 閲覧期限 {date(s.currentPeriodEndsAt)}{s.status === 'PAST_DUE' && s.graceEndsAt ? ` · 支払猶予 ${date(s.graceEndsAt)}まで` : ''}</small></div>{!s.cancelAtPeriodEnd && ['ACTIVE','PAST_DUE','TRIALING'].includes(s.status) && <button className="button secondary small" onClick={() => void cancel(s.id)}>次回更新を停止</button>}{s.cancelAtPeriodEnd && <span className="status-tag warning">解約予約済み</span>}</div>)}{data.dayPasses.map(p => <div className="billing-contract" key={p.id}><div><strong>{p.raceDate} 1日利用</strong><small>{money(p.priceYen)} · {p.status === 'PENDING' ? 'WIN5初版公開待ち' : p.status}</small></div></div>)}</div>}
    {!!data.payments.length && <div className="table-scroll"><table><thead><tr><th>日時</th><th>種別</th><th>状態</th><th>金額</th></tr></thead><tbody>{data.payments.map(p => <tr key={p.id}><td>{date(p.occurredAt)}</td><td>{p.kind}</td><td>{p.status}</td><td>{money(p.amountYen)}</td></tr>)}</tbody></table></div>}
    <div className="billing-support-form"><h3>請求について問い合わせる</h3><p className="muted">返金の可否や領収書の発行を確約するものではありません。運営が対象の支払いと内容を確認します。</p><label className="field">問い合わせ種別<select value={supportCategory} onChange={e => setSupportCategory(e.target.value as keyof typeof supportCategoryLabels)}>{Object.entries(supportCategoryLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{(supportCategory === 'REFUND' || supportCategory === 'RECEIPT') && <label className="field">対象の支払い<select value={supportPaymentId} onChange={e => setSupportPaymentId(e.target.value)}><option value="">選択してください</option>{data.payments.map(payment => <option value={payment.id} key={payment.id}>{date(payment.occurredAt)}・{money(payment.amountYen)}・{payment.status}</option>)}</select></label>}<label className="field">問い合わせ内容<textarea value={supportMessage} minLength={10} maxLength={2000} rows={4} placeholder="確認してほしい内容を10文字以上で入力してください。" onChange={e => setSupportMessage(e.target.value)} /></label><button className="button" disabled={supportBusy || supportMessage.trim().length < 10} onClick={() => void createSupportRequest()}>{supportBusy ? '送信中…' : '問い合わせを送信'}</button></div>
    {!!data.supportRequests.length && <div className="billing-support-history"><h3>問い合わせ履歴</h3>{data.supportRequests.map(item => <article className="billing-contract" key={item.id}><div><strong>{supportCategoryLabels[item.category]}</strong><small>{date(item.createdAt)} · {item.message}</small></div><span className={`status-tag ${item.status === 'RESOLVED' ? '' : 'warning'}`}>{supportStatusLabels[item.status]}</span></article>)}</div>}</>}</div></section>;
}

export function AdminBilling() {
  const [data, setData] = useState<BillingData | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = () => request<BillingData>('admin/billing').then(setData).catch(e => setError(e.message)); useEffect(() => { void load(); }, []);
  async function action(id: string, name: 'simulate-failure' | 'recover') { setError(''); setMessage(''); try { if (!reason.trim()) throw new Error('試験操作の理由を入力してください。'); await request(`admin/billing/subscriptions/${id}/${name}`, 'POST', { reason }); setMessage(name === 'recover' ? '支払回復を記録しました。' : '支払失敗を記録しました。'); setReason(''); await load(); } catch (e) { setError((e as Error).message); } }
  async function supportAction(id: string, status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED') { setError(''); setMessage(''); try { if (!reason.trim()) throw new Error('対応理由を入力してください。'); await request(`admin/billing/support-requests/${id}/status`, 'POST', { status, reason }); setMessage('問い合わせの対応状態を更新しました。'); setReason(''); await load(); } catch (e) { setError((e as Error).message); } }
  const localSimulation = data?.billingTransport !== 'stripe';
  return <><div className="page-heading"><span className="eyebrow">ADMINISTRATION</span><h1>契約・請求管理</h1><p>会員の契約、請求問い合わせ、追記専用の支払履歴を確認します。</p></div><Notice value={error} error /><Notice value={message} /><section className="panel"><div className="panel-body"><div className="notice">{localSimulation ? '請求なしのテスト決済です。申込、支払失敗、回復、解約と閲覧権限の動きを確認できます。外部への請求や返金は行いません。' : '外部決済の契約状態は署名済みStripe Webhookから同期します。管理画面から状態を変更できません。'}</div><label className="field">管理操作・対応理由<input value={reason} maxLength={2000} onChange={e => setReason(e.target.value)} /></label></div><div className="table-scroll"><table><thead><tr><th>会員</th><th>プラン</th><th>状態</th><th>金額</th><th>期間終了</th><th>試験操作</th></tr></thead><tbody>{data?.subscriptions.map(s => <tr key={s.id}><td>{s.user?.displayName}<small className="cell-note">{s.user?.email}</small></td><td>{s.planCode}</td><td>{s.status}{s.cancelAtPeriodEnd ? '・解約予約' : ''}{s.status === 'PAST_DUE' && s.graceEndsAt ? <small className="cell-note">猶予 {date(s.graceEndsAt)}まで</small> : null}</td><td>{money(s.priceYen)}</td><td>{date(s.currentPeriodEndsAt)}</td><td>{!localSimulation ? 'Webhook同期' : s.status === 'PAST_DUE' ? <button className="button secondary small" onClick={() => void action(s.id, 'recover')}>回復</button> : s.status === 'ACTIVE' ? <button className="button secondary small" onClick={() => void action(s.id, 'simulate-failure')}>失敗を試験</button> : '—'}</td></tr>)}</tbody></table></div></section>
    <section className="panel"><div className="panel-heading"><h2>請求問い合わせ</h2><span className="count-tag">未解決 {data?.supportRequests.filter(item => item.status !== 'RESOLVED').length ?? 0}件</span></div>{!data?.supportRequests.length ? <div className="panel-body"><p className="muted">請求問い合わせはありません。</p></div> : <div className="billing-support-admin">{data.supportRequests.map(item => <article className="billing-support-item" key={item.id}><div><span className={`status-tag ${item.status === 'RESOLVED' ? '' : 'warning'}`}>{supportStatusLabels[item.status]}</span><h3>{supportCategoryLabels[item.category]}</h3><p>{item.message}</p><small>{item.user?.displayName} · {item.user?.email ?? 'メール未設定'} · {date(item.createdAt)}</small>{item.paymentTransaction && <small>対象支払：{date(item.paymentTransaction.occurredAt)} · {money(item.paymentTransaction.amountYen)} · {item.paymentTransaction.status}</small>}{item.events.length > 1 && <details><summary>対応履歴 {item.events.length}件</summary><ol>{item.events.map(event => <li key={event.id ?? `${event.eventType}:${event.occurredAt}`}><strong>{event.eventType}</strong> · {date(event.occurredAt)}{event.reason ? ` · ${event.reason}` : ''}</li>)}</ol></details>}</div><div className="review-actions">{item.status === 'OPEN' && <button className="button secondary small" onClick={() => void supportAction(item.id, 'IN_PROGRESS')}>対応を開始</button>}{item.status !== 'RESOLVED' && <button className="button small" onClick={() => void supportAction(item.id, 'RESOLVED')}>解決済みにする</button>}{item.status === 'RESOLVED' && <button className="button secondary small" onClick={() => void supportAction(item.id, 'OPEN')}>再開する</button>}</div></article>)}</div>}</section>
    <section className="panel"><div className="panel-heading"><h2>支払試行履歴</h2></div><div className="table-scroll"><table><thead><tr><th>日時</th><th>会員</th><th>種別</th><th>状態</th><th>金額</th></tr></thead><tbody>{data?.payments.map(p => <tr key={p.id}><td>{date(p.occurredAt)}</td><td>{p.user?.displayName}</td><td>{p.kind}</td><td>{p.status}</td><td>{money(p.amountYen)}</td></tr>)}</tbody></table></div></section>
    {!!data?.checkouts?.length && <section className="panel"><div className="panel-heading"><h2>外部決済申込</h2></div><div className="table-scroll"><table><thead><tr><th>開始日時</th><th>会員</th><th>プラン</th><th>状態</th><th>金額</th></tr></thead><tbody>{data.checkouts.map(item => <tr key={item.id}><td>{date(item.createdAt)}</td><td>{item.user.displayName}<small className="cell-note">{item.user.email}</small></td><td>{item.planCode}{item.raceDate ? ` · ${item.raceDate}` : ''}</td><td>{item.status}</td><td>{money(item.amountYen)}</td></tr>)}</tbody></table></div></section>}
    {!!data?.stripeWebhooks?.length && <section className="panel"><div className="panel-heading"><h2>Stripe Webhook受信</h2></div><div className="table-scroll"><table><thead><tr><th>受信日時</th><th>イベント</th><th>結果</th><th>モード</th></tr></thead><tbody>{data.stripeWebhooks.map(item => <tr key={item.id}><td>{date(item.receivedAt)}</td><td>{item.eventType}<small className="cell-note mono">{item.providerEventId}</small></td><td>{item.outcome}</td><td>{item.livemode ? 'LIVE' : 'TEST'}</td></tr>)}</tbody></table></div></section>}</>;
}
