'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, CreditCard, ShieldCheck } from 'lucide-react';
import type { AdminBillingCheckoutResolutionResponse, AdminBillingDayPassRefundResponse, AdminBillingFailureSimulationResponse, AdminBillingRecoverySimulationResponse, AdminBillingResponse, AdminBillingSupportStatusResponse, BankTransferRequest, BankTransferSettingsResponse, BillingCouponPreviewResponse, BillingDayPassCheckoutResponse, BillingPlansResponse, BillingPortalResponse, BillingReceiptResponse, BillingSubscriptionCheckoutResponse, BillingSubscriptionLifecycleResponse, BillingSupportRequestCreatedResponse, MemberBillingResponse, MemberJourneyResponse } from '@keiba/domain';
import { AdminBillingCoupons } from './billing-coupons';

type Plan = BillingPlansResponse['plans'][number];
const supportCategoryLabels = { REFUND: '返金について', RECEIPT: '領収書について', PAYMENT_FAILURE: '支払い失敗について', CANCELLATION: '解約について', OTHER: 'その他の請求問い合わせ' } as const;
const supportStatusLabels = { OPEN: '受付済み', IN_PROGRESS: '対応中', RESOLVED: '解決済み' } as const;
const dayPassStatusLabels: Record<string, string> = { PENDING: 'WIN5初版公開待ち', REFUNDING: '返金処理中', ACTIVE: '利用中', USED: '使用済み', EXPIRED: '期限切れ', REFUNDED: '返金済み' };
const bankTransferStatusLabels: Record<string, string> = { AWAITING_TRANSFER: '振込待ち', TRANSFER_REPORTED: '着金確認待ち', CONFIRMED: '入金確認済み', REJECTED: '受付不可', CANCELLED: '取消済み', EXPIRED: '振込期限切れ' };
const money = (value: number) => new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(value);
const date = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
async function request<T>(path: string, method = 'GET', body?: unknown, idempotent = false): Promise<T> {
  const response = await fetch(`/api/v1/${path}`, { method, cache: 'no-store', headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), ...(idempotent ? { 'Idempotency-Key': crypto.randomUUID() } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '処理に失敗しました。'); return result;
}
function Notice({ value, error = false }: { value: string; error?: boolean }) { return value ? <div className={`notice ${error ? 'error' : ''}`} role={error ? 'alert' : 'status'}>{value}</div> : null; }

export function PlansPage({ loggedIn, purchaseReady, refresh }: { loggedIn: boolean; purchaseReady: boolean; refresh: () => Promise<void> }) {
  const search = useSearchParams();
  const [plans, setPlans] = useState<Plan[]>([]); const [enabled, setEnabled] = useState(false); const [raceDate, setRaceDate] = useState(() => search.get('date') ?? '');
  const [transport, setTransport] = useState<BillingPlansResponse['billingTransport']>('test');
  const [stripeMode, setStripeMode] = useState<'TEST' | 'LIVE' | null>(null);
  const [bankRequest, setBankRequest] = useState<BankTransferRequest | null>(null);
  const [couponCode, setCouponCode] = useState(''); const [coupon, setCoupon] = useState<BillingCouponPreviewResponse | null>(null);
  const [selected, setSelected] = useState<Plan | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { request<BillingPlansResponse>('billing/plans').then(v => { setPlans(v.plans); setEnabled(v.newPurchasesEnabled); setTransport(v.billingTransport); setStripeMode(v.stripeMode); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (loggedIn) void request<MemberJourneyResponse>('me/journey', 'POST', { eventType: 'PLAN_VIEWED' }).catch(() => undefined); }, [loggedIn]);
  useEffect(() => { if (selected) document.getElementById('plan-review')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, [selected]);
  async function buy(plan: Plan) { setBusy(true); setError(''); setMessage(''); try {
    if (transport === 'bank_transfer') {
      const created = await request<BankTransferRequest>('billing/bank-transfers', 'POST', { planCode: plan.code, ...(plan.code === 'DAY_PASS' ? { raceDate } : {}) }, true);
      setBankRequest(created); setSelected(null); setMessage('銀行振込の申込を受け付けました。振込先と識別番号をご確認ください。'); await refresh(); return;
    }
    const couponInput = coupon?.planCode === plan.code ? { couponCode: coupon.code } : {};
    const result: BillingSubscriptionCheckoutResponse | BillingDayPassCheckoutResponse = plan.code === 'DAY_PASS'
      ? (raceDate ? await request<BillingDayPassCheckoutResponse>('billing/day-pass', 'POST', { raceDate, ...couponInput }, true) : (() => { throw new Error('利用する開催日を選択してください。'); })())
      : await request<BillingSubscriptionCheckoutResponse>('billing/checkout', 'POST', { planCode: plan.code, ...couponInput }, true);
    if ('checkoutUrl' in result) { window.location.assign(result.checkoutUrl); return; }
    await refresh(); setSelected(null); setMessage(`${plan.name}のテスト申込を登録しました。実際の請求はありません。`);
  } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function applyCoupon(plan: Plan) { setBusy(true); setError(''); setMessage(''); try {
    const value = await request<BillingCouponPreviewResponse>('billing/coupons/preview', 'POST', { planCode: plan.code, couponCode });
    setCoupon(value); setCouponCode(value.code); setMessage('クーポンを適用しました。割引後の金額を確認してください。');
  } catch (e) { setCoupon(null); setError((e as Error).message); } finally { setBusy(false); } }
  const stripeTest = transport === 'stripe' && stripeMode === 'TEST';
  const bank = transport === 'bank_transfer';
  return <><div className="page-heading"><span className="eyebrow">MEMBERSHIP</span><h1>料金プラン</h1><p>{bank ? '銀行振込でお申し込みいただけます。運営の着金確認後に閲覧を開始します。' : stripeTest ? 'Stripeのテストカードで申込から閲覧までを確認するサンドボックスです。' : transport === 'stripe' ? '公開された有料予想を閲覧するための料金プランです。' : '有料会員の申込から閲覧までを、請求なしで確認するテストプランです。'}</p></div><Notice value={error} error /><Notice value={message} />
    {stripeTest && <div className="notice error" role="alert"><strong>Stripeテスト環境です。</strong> 実在するカード情報は入力せず、Stripe公式のテストカードだけを使用してください。実際の請求は発生しません。</div>}
    <div className="notice">表示価格は税込です。{bank ? '申込だけでは閲覧権限は付きません。指定口座への着金を管理者が確認した後に反映します。振込手数料はご利用の金融機関でご確認ください。' : transport === 'stripe' ? `申込時はStripeの${stripeTest ? 'テスト' : '本番'}決済画面へ移動し、署名済みWebhookの確認後に閲覧権限を反映します。` : 'この画面では外部決済やカード情報の入力を行いません。'}</div>
    {bankRequest && <BankTransferInstructions value={bankRequest} />}
    {loggedIn && !purchaseReady && <div className="notice error">申込前にマイページでメールアドレスの確認を完了してください。 <Link className="text-link" href="/account">確認する</Link></div>}
    <div className="plan-grid">{plans.map(plan => <section className="panel plan-card" key={plan.code}><div className="panel-body"><span className="eyebrow">{plan.interval === 'MONTH' ? 'MONTHLY' : 'ONE DAY'}</span><h2>{plan.name}</h2><strong className="plan-price">{money(plan.priceYen)}<small>{plan.interval === 'MONTH' ? '／月' : '／開催日'}</small></strong><p>{plan.code === 'DAY_PASS' ? 'WIN5商品がある日は初版公開時から翌日0:00まで閲覧できます。商品がない日は指定日の0:00開始です。' : transport === 'stripe' ? 'Stripeの請求期間で月次更新します。解約予約後も支払済み期間の終了まで閲覧できます。' : '申込日時から1か月間。解約予約後も支払済み期間の終了まで閲覧できます。'}</p>{plan.code === 'FOUNDER' && <small>残り枠：{plan.remaining ?? 0}</small>}
      {plan.code === 'DAY_PASS' && <label className="field">利用する開催日<input type="date" value={raceDate} min={new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' })} onChange={e => setRaceDate(e.target.value)} /></label>}
      {loggedIn ? <button className="button full" disabled={busy || !purchaseReady || !plan.available || (plan.code === 'DAY_PASS' && !raceDate)} onClick={() => { setError(''); setMessage(''); setSelected(plan); setCoupon(null); setCouponCode(''); void request<MemberJourneyResponse>('me/journey', 'POST', { eventType: 'CHECKOUT_REVIEWED' }).catch(() => undefined); }}>{!purchaseReady ? 'メール確認後に確認可能' : !plan.available ? '現在は申込できません' : plan.code === 'DAY_PASS' && !raceDate ? '開催日を選択' : '申込内容を確認'}<ArrowRight size={17} /></button> : <Link className="button full" href="/login">ログインして申し込む<ArrowRight size={17} /></Link>}</div></section>)}</div>
    {selected && <section className="panel plan-review" id="plan-review" aria-live="polite"><div className="panel-heading"><div><span className="eyebrow">APPLICATION REVIEW</span><h2>申込内容の確認</h2></div><ShieldCheck size={20} /></div><div className="panel-body"><dl className="review-details"><div><dt>プラン</dt><dd>{selected.name}</dd></div><div><dt>通常料金</dt><dd>{money(selected.priceYen)}{selected.interval === 'MONTH' ? bank ? '／期間利用' : '／月' : '／開催日'}</dd></div>{coupon && <><div><dt>クーポン</dt><dd>{coupon.code}・{coupon.name}</dd></div><div><dt>割引</dt><dd>−{money(coupon.discountAmountYen)}</dd></div><div><dt>今回の支払額</dt><dd><strong>{money(coupon.amountYen)}</strong></dd></div></>}{selected.code === 'DAY_PASS' && <div><dt>利用日</dt><dd>{raceDate}</dd></div>}<div><dt>利用期間</dt><dd>{selected.interval === 'MONTH' ? bank ? '着金確認後から管理画面で設定した期間（自動更新・自動課金なし）' : transport === 'stripe' ? 'Stripeの請求期間に従って月次更新' : '申込日時から1か月間' : 'WIN5商品がある日は初版公開時から翌日0:00まで。商品がない日は指定日0:00から開始'}</dd></div></dl>{!bank && <div className="billing-coupon-entry"><label className="field">クーポンコード<input value={couponCode} onChange={event => { setCouponCode(event.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g, '').slice(0, 32)); setCoupon(null); }} minLength={4} maxLength={32} placeholder="お持ちの場合のみ入力" /></label><button className="button secondary" disabled={busy || couponCode.length < 4} onClick={() => void applyCoupon(selected)}>クーポンを適用</button>{coupon && <small>{coupon.duration === 'FOREVER' && selected.interval === 'MONTH' ? 'この割引は契約中の月額料金へ継続適用されます。' : 'この割引は今回の支払いだけに適用されます。'} 有効期限：{date(coupon.endsAt)}</small>}</div>}{(!enabled || !selected.available) && <div className="notice error">このプランは現在、新規申込を受け付けていません。内容は確認できます。</div>}<div className="notice">{bank ? '申込後に振込先と識別番号を表示します。振込名義と識別番号を確認し、振込後にマイページから報告してください。' : stripeTest ? 'Stripeのテスト決済画面へ移動します。Stripe公式のテストカードだけを使用してください。' : transport === 'stripe' ? 'Stripeの決済画面へ移動します。カード情報は本サービスのDBへ保存しません。' : 'クラウド試験・開発環境のテスト申込です。外部への請求やカード情報の送信はありません。'}</div><div className="review-actions"><button className="button secondary" disabled={busy} onClick={() => setSelected(null)}>プラン選択へ戻る</button><button className="button" disabled={busy || !enabled || !selected.available || (!bank && !!couponCode && !coupon)} onClick={() => void buy(selected)}>{busy ? '処理中…' : !enabled ? '新規購入を停止中' : !selected.available ? '現在は申込できません' : !bank && couponCode && !coupon ? 'クーポンを適用してください' : bank ? '銀行振込を申し込む' : stripeTest ? 'Stripeテスト決済へ進む' : transport === 'stripe' ? '内容を確認して申し込む' : '請求なしでテスト申込する'}<ArrowRight size={17} /></button></div></div></section>}
    <section className="panel billing-terms"><div className="panel-heading"><h2>申込前の確認</h2><ShieldCheck size={20} /></div><div className="panel-body"><p>{bank ? '銀行振込の月額相当利用は自動更新されません。継続する場合は期間終了後に改めてお申し込みください。' : '月額利用は次回更新日時までに解約予約しない限り自動更新されます。'} 購入確定後または利用開始後の利用者都合による返金は原則として行いません。申込前に<Link className="text-link" href="/terms">利用規約</Link>と<Link className="text-link" href="/privacy">プライバシーポリシー</Link>をご確認ください。</p></div></section></>;
}

function BankTransferInstructions({ value }: { value: BankTransferRequest }) {
  return <section className="panel"><div className="panel-heading"><div><span className="eyebrow">BANK TRANSFER</span><h2>お振込先</h2></div><span className="status-tag warning">{bankTransferStatusLabels[value.status] ?? value.status}</span></div><div className="panel-body"><dl className="review-details"><div><dt>振込金額</dt><dd><strong>{money(value.amountYen)}</strong></dd></div><div><dt>振込識別番号</dt><dd><strong className="mono">{value.referenceCode}</strong></dd></div><div><dt>金融機関</dt><dd>{value.bankAccount.bankName} {value.bankAccount.branchName}</dd></div><div><dt>口座</dt><dd>{value.bankAccount.accountType} {value.bankAccount.accountNumber}</dd></div><div><dt>口座名義</dt><dd>{value.bankAccount.accountHolder}</dd></div><div><dt>振込期限</dt><dd>{date(value.expiresAt)}</dd></div></dl>{value.bankAccount.instructions && <p>{value.bankAccount.instructions}</p>}<div className="notice">振込名義または振込時の備考に識別番号を入力してください。入力できない場合も、マイページから振込名義を報告できます。着金確認までは閲覧権限は付与されません。</div></div></section>;
}

export function BillingAccount() {
  const [data, setData] = useState<MemberBillingResponse | null>(null); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [payerName, setPayerName] = useState(''); const [bankBusy, setBankBusy] = useState(false);
  const [supportCategory, setSupportCategory] = useState<keyof typeof supportCategoryLabels>('PAYMENT_FAILURE'); const [supportPaymentId, setSupportPaymentId] = useState(''); const [supportMessage, setSupportMessage] = useState(''); const [supportBusy, setSupportBusy] = useState(false);
  const load = () => request<MemberBillingResponse>('billing/me').then(setData).catch(e => setError(e.message));
  useEffect(() => { void load(); }, []);
  async function cancel(id: string) { setError(''); try { await request<BillingSubscriptionLifecycleResponse>(`billing/subscriptions/${id}/cancel`, 'POST'); setMessage('次回更新を停止しました。支払済み期間の終了まで閲覧できます。'); await load(); } catch (e) { setError((e as Error).message); } }
  async function resume(id: string) { setError(''); try { await request<BillingSubscriptionLifecycleResponse>(`billing/subscriptions/${id}/resume`, 'POST'); setMessage('月額契約の継続を再開しました。'); await load(); } catch (e) { setError((e as Error).message); } }
  async function openPortal() { setError(''); try { const result = await request<BillingPortalResponse>('billing/portal', 'POST'); window.location.assign(result.portalUrl); } catch (e) { setError((e as Error).message); } }
  async function createSupportRequest() { setError(''); setMessage(''); setSupportBusy(true); try {
    const needsPayment = supportCategory === 'REFUND' || supportCategory === 'RECEIPT';
    if (needsPayment && !supportPaymentId) throw new Error('対象の支払いを選択してください。');
    await request<BillingSupportRequestCreatedResponse>('billing/support-requests', 'POST', { category: supportCategory, paymentTransactionId: supportPaymentId || null, message: supportMessage }, true);
    setSupportMessage(''); setSupportPaymentId(''); setMessage('請求に関する問い合わせを受け付けました。'); await load();
  } catch (e) { setError((e as Error).message); } finally { setSupportBusy(false); } }
  async function openReceipt(id: string) { setError(''); try { const result = await request<BillingReceiptResponse>(`billing/payments/${id}/receipt`); window.location.assign(result.receiptUrl); } catch (e) { setError((e as Error).message); } }
  async function reportTransfer(item: BankTransferRequest) { setError(''); setMessage(''); setBankBusy(true); try { if (!payerName.trim()) throw new Error('振込名義を入力してください。'); await request<BankTransferRequest>(`billing/bank-transfers/${item.id}/report`, 'POST', { payerName, revision: item.revision }, true); setPayerName(''); setMessage('振込報告を受け付けました。着金確認後に閲覧権限を反映します。'); await load(); } catch (e) { setError((e as Error).message); } finally { setBankBusy(false); } }
  return <section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">BILLING</span><h2>契約・お支払い履歴</h2></div><CreditCard size={20} /></div><div className="panel-body"><Notice value={error} error /><Notice value={message} />{!data ? <p>読み込み中…</p> : <>
    {!data.subscriptions.length && !data.dayPasses.length && !data.bankTransfers.length ? <p className="muted">契約はありません。 <Link className="text-link" href="/plans">料金プランを見る</Link></p> : <div className="billing-contracts">{data.subscriptions.map(s => <div className="billing-contract" key={s.id}><div><strong>{s.planCode} 月額契約</strong><small>{money(s.priceYen)} · {s.status} · 閲覧期限 {date(s.currentPeriodEndsAt)}{s.status === 'PAST_DUE' && s.graceEndsAt ? ` · 支払猶予 ${date(s.graceEndsAt)}まで` : ''}</small></div><div className="review-actions">{!s.cancelAtPeriodEnd && ['ACTIVE','PAST_DUE','TRIALING'].includes(s.status) && <button className="button secondary small" onClick={() => void cancel(s.id)}>次回更新を停止</button>}{s.cancelAtPeriodEnd && <><span className="status-tag warning">解約予約済み</span><button className="button secondary small" onClick={() => void resume(s.id)}>継続する</button></>}</div></div>)}{data.dayPasses.map(p => <div className="billing-contract" key={p.id}><div><strong>{p.raceDate} 1日利用</strong><small>{money(p.priceYen)} · {dayPassStatusLabels[p.status] ?? p.status}</small></div></div>)}</div>}
    {!!data.bankTransfers.length && <div className="billing-support-history"><h3>銀行振込の申込</h3>{data.bankTransfers.map(item => <article className="billing-support-item" key={item.id}><div><span className={`status-tag ${item.status === 'CONFIRMED' ? '' : 'warning'}`}>{bankTransferStatusLabels[item.status] ?? item.status}</span><h3>{item.planCode}{item.raceDate ? `・${item.raceDate}` : ''}</h3><small>{money(item.amountYen)} · 識別番号 {item.referenceCode} · 期限 {date(item.expiresAt)}</small>{['AWAITING_TRANSFER','TRANSFER_REPORTED'].includes(item.status) && <BankTransferInstructions value={item} />}{item.reviewReason && <p>運営確認：{item.reviewReason}</p>}</div>{item.status === 'AWAITING_TRANSFER' && <div className="billing-coupon-entry"><label className="field">振込名義<input value={payerName} maxLength={100} onChange={event => setPayerName(event.target.value)} placeholder="口座から振り込んだ名義" /></label><button className="button" disabled={bankBusy || !payerName.trim()} onClick={() => void reportTransfer(item)}>{bankBusy ? '報告中…' : '振込済みを報告'}</button></div>}</article>)}</div>}
    {data.customerPortalAvailable && <div className="billing-portal-action"><button className="button secondary" onClick={() => void openPortal()}>支払い方法・請求情報を管理</button><p className="muted">Stripeの安全な画面でカード情報を変更できます。</p></div>}
    {!!data.payments.length && <div className="table-scroll"><table><thead><tr><th>日時</th><th>種別</th><th>状態</th><th>金額</th><th>領収書</th></tr></thead><tbody>{data.payments.map(p => <tr key={p.id}><td>{date(p.occurredAt)}</td><td>{p.kind}</td><td>{p.status}</td><td>{money(p.amountYen)}</td><td>{p.provider === 'STRIPE' && p.status === 'SUCCEEDED' ? <button className="text-link" onClick={() => void openReceipt(p.id)}>表示</button> : '—'}</td></tr>)}</tbody></table></div>}
    <div className="billing-support-form"><h3>請求について問い合わせる</h3><p className="muted">返金の可否や領収書の発行を確約するものではありません。運営が対象の支払いと内容を確認します。</p><label className="field">問い合わせ種別<select value={supportCategory} onChange={e => setSupportCategory(e.target.value as keyof typeof supportCategoryLabels)}>{Object.entries(supportCategoryLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{(supportCategory === 'REFUND' || supportCategory === 'RECEIPT') && <label className="field">対象の支払い<select value={supportPaymentId} onChange={e => setSupportPaymentId(e.target.value)}><option value="">選択してください</option>{data.payments.map(payment => <option value={payment.id} key={payment.id}>{date(payment.occurredAt)}・{money(payment.amountYen)}・{payment.status}</option>)}</select></label>}<label className="field">問い合わせ内容<textarea value={supportMessage} minLength={10} maxLength={2000} rows={4} placeholder="確認してほしい内容を10文字以上で入力してください。" onChange={e => setSupportMessage(e.target.value)} /></label><button className="button" disabled={supportBusy || supportMessage.trim().length < 10} onClick={() => void createSupportRequest()}>{supportBusy ? '送信中…' : '問い合わせを送信'}</button></div>
    {!!data.supportRequests.length && <div className="billing-support-history"><h3>問い合わせ履歴</h3>{data.supportRequests.map(item => <article className="billing-contract" key={item.id}><div><strong>{supportCategoryLabels[item.category]}</strong><small>{date(item.createdAt)} · {item.message}</small></div><span className={`status-tag ${item.status === 'RESOLVED' ? '' : 'warning'}`}>{supportStatusLabels[item.status]}</span></article>)}</div>}</>}</div></section>;
}

export function AdminBilling() {
  const [data, setData] = useState<AdminBillingResponse | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [bankSettings, setBankSettings] = useState<BankTransferSettingsResponse | null>(null); const [receivedAmount, setReceivedAmount] = useState(''); const [receivedAt, setReceivedAt] = useState('');
  const load = () => request<AdminBillingResponse>('admin/billing').then(value => { setData(value); setBankSettings(value.bankTransferSettings); }).catch(e => setError(e.message)); useEffect(() => { void load(); }, []);
  async function action(id: string, name: 'simulate-failure' | 'recover') { setError(''); setMessage(''); try { if (!reason.trim()) throw new Error('試験操作の理由を入力してください。'); if (name === 'recover') await request<AdminBillingRecoverySimulationResponse>(`admin/billing/subscriptions/${id}/${name}`, 'POST', { reason }); else await request<AdminBillingFailureSimulationResponse>(`admin/billing/subscriptions/${id}/${name}`, 'POST', { reason }); setMessage(name === 'recover' ? '支払回復を記録しました。' : '支払失敗を記録しました。'); setReason(''); await load(); } catch (e) { setError((e as Error).message); } }
  async function supportAction(id: string, status: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED') { setError(''); setMessage(''); try { if (!reason.trim()) throw new Error('対応理由を入力してください。'); await request<AdminBillingSupportStatusResponse>(`admin/billing/support-requests/${id}/status`, 'POST', { status, reason }); setMessage('問い合わせの対応状態を更新しました。'); setReason(''); await load(); } catch (e) { setError((e as Error).message); } }
  async function refundDayPass(id: string) { setError(''); setMessage(''); try { if (!reason.trim()) throw new Error('返金理由を入力してください。'); await request<AdminBillingDayPassRefundResponse>(`admin/billing/day-passes/${id}/refund`, 'POST', { reason }); setMessage('期限切れの公開待ち一日券を返金済みにしました。'); setReason(''); await load(); } catch (e) { setError((e as Error).message); } }
  async function resolveReview(id: string, action: 'GRANT_ACCESS' | 'REFUND') { setError(''); setMessage(''); try { if (!reason.trim()) throw new Error('対応理由を入力してください。'); await request<AdminBillingCheckoutResolutionResponse>(`admin/billing/checkouts/${id}/resolve`, 'POST', { action, reason }); setMessage(action === 'GRANT_ACCESS' ? '決済内容を再検証し、閲覧権限を付与しました。' : 'Stripe返金を完了しました。'); setReason(''); await load(); } catch (e) { setError((e as Error).message); } }
  async function saveBankSettings() { setError(''); setMessage(''); try { if (!bankSettings || !reason.trim()) throw new Error('設定と変更理由を入力してください。'); const updated = await request<BankTransferSettingsResponse>('admin/billing/bank-transfer-settings', 'POST', { ...bankSettings, reason }); setBankSettings(updated); setReason(''); setMessage('銀行振込の設定を保存しました。'); await load(); } catch (e) { setError((e as Error).message); } }
  async function reviewBankTransfer(item: AdminBillingResponse['bankTransfers'][number], action: 'CONFIRM' | 'REJECT') { setError(''); setMessage(''); try { if (!reason.trim()) throw new Error('確認理由を入力してください。'); const body = action === 'CONFIRM' ? { action, revision: item.revision, reason, receivedAmountYen: Number(receivedAmount), receivedAt: new Date(receivedAt).toISOString() } : { action, revision: item.revision, reason }; await request<BankTransferRequest>(`admin/billing/bank-transfers/${item.id}/review`, 'POST', body, true); setReason(''); setReceivedAmount(''); setReceivedAt(''); setMessage(action === 'CONFIRM' ? '着金を確認し、閲覧権限を付与しました。' : '銀行振込の申込を却下しました。'); await load(); } catch (e) { setError((e as Error).message); } }
  const localSimulation = data?.billingTransport === 'test';
  return <><div className="page-heading"><span className="eyebrow">ADMINISTRATION</span><h1>契約・請求管理</h1><p>会員の契約、銀行振込、料金・クーポン、請求問い合わせ、追記専用の支払履歴を確認します。</p></div><Notice value={error} error /><Notice value={message} /><AdminBillingCoupons /><section className="panel"><div className="panel-body"><div className="notice">{data?.billingTransport === 'bank_transfer' ? '銀行振込運用です。会員の振込報告と実際の入金を照合し、着金額・着金日時を確認した場合だけ権限を付与してください。' : localSimulation ? '請求なしのテスト決済です。申込、支払失敗、回復、解約と閲覧権限の動きを確認できます。外部への請求や返金は行いません。' : '通常の契約状態は署名済みStripe Webhookから同期します。支払済みなのに権限を付与できなかった決済だけ、下の専用操作で再検証または全額返金できます。'}</div><label className="field">管理操作・対応理由<input value={reason} maxLength={500} onChange={e => setReason(e.target.value)} /></label></div><div className="table-scroll"><table><thead><tr><th>会員</th><th>プラン</th><th>状態</th><th>金額</th><th>期間終了</th><th>試験操作</th></tr></thead><tbody>{data?.subscriptions.map(s => <tr key={s.id}><td>{s.user?.displayName}<small className="cell-note">{s.user?.email}</small></td><td>{s.planCode}</td><td>{s.status}{s.cancelAtPeriodEnd ? '・解約予約' : ''}{s.status === 'PAST_DUE' && s.graceEndsAt ? <small className="cell-note">猶予 {date(s.graceEndsAt)}まで</small> : null}</td><td>{money(s.priceYen)}</td><td>{date(s.currentPeriodEndsAt)}</td><td>{data?.billingTransport === 'stripe' ? 'Webhook同期' : !localSimulation ? '—' : s.status === 'PAST_DUE' ? <button className="button secondary small" onClick={() => void action(s.id, 'recover')}>回復</button> : s.status === 'ACTIVE' ? <button className="button secondary small" onClick={() => void action(s.id, 'simulate-failure')}>失敗を試験</button> : '—'}</td></tr>)}</tbody></table></div></section>
    {bankSettings && <section className="panel"><div className="panel-heading"><div><h2>銀行振込設定</h2><small className="muted">口座情報を保存しても、配備環境の決済方式がbank_transferでなければ有効化できません。</small></div><span className={`status-tag ${bankSettings.enabled ? '' : 'warning'}`}>{bankSettings.enabled ? '受付中' : '停止中'}</span></div><div className="panel-body"><label className="setting-row"><span><strong>銀行振込を受け付ける</strong><small>停止しても既存の確認待ち申込と付与済み権限は保持します。</small></span><input type="checkbox" checked={bankSettings.enabled} onChange={event => setBankSettings({ ...bankSettings, enabled: event.target.checked })} /></label><div className="race-form-grid"><label className="field">金融機関<input value={bankSettings.bankName} maxLength={100} onChange={event => setBankSettings({ ...bankSettings, bankName: event.target.value })} /></label><label className="field">支店<input value={bankSettings.branchName} maxLength={100} onChange={event => setBankSettings({ ...bankSettings, branchName: event.target.value })} /></label><label className="field">口座種別<select value={bankSettings.accountType} onChange={event => setBankSettings({ ...bankSettings, accountType: event.target.value as '' | '普通' | '当座' })}><option value="">選択</option><option value="普通">普通</option><option value="当座">当座</option></select></label><label className="field">口座番号<input inputMode="numeric" value={bankSettings.accountNumber} maxLength={12} onChange={event => setBankSettings({ ...bankSettings, accountNumber: event.target.value.replace(/\D/g, '') })} /></label><label className="field">口座名義<input value={bankSettings.accountHolder} maxLength={100} onChange={event => setBankSettings({ ...bankSettings, accountHolder: event.target.value })} /></label><label className="field">申込期限（日）<input type="number" min={1} max={30} value={bankSettings.requestValidityDays} onChange={event => setBankSettings({ ...bankSettings, requestValidityDays: Number(event.target.value) })} /></label><label className="field">月額相当の利用日数<input type="number" min={1} max={366} value={bankSettings.monthlyAccessDays} onChange={event => setBankSettings({ ...bankSettings, monthlyAccessDays: Number(event.target.value) })} /></label></div><label className="field">会員向け振込案内<textarea rows={3} maxLength={1000} value={bankSettings.instructions} onChange={event => setBankSettings({ ...bankSettings, instructions: event.target.value })} /></label><button className="button" disabled={!reason.trim()} onClick={() => void saveBankSettings()}>銀行振込設定を保存</button></div></section>}
    <section className="panel"><div className="panel-heading"><div><h2>銀行振込の確認</h2><small className="muted">会員の報告だけで承認せず、入出金明細と識別番号・名義・金額を照合してください。</small></div><span className="count-tag">確認待ち {data?.bankTransfers.filter(item => item.status === 'TRANSFER_REPORTED').length ?? 0}件</span></div><div className="panel-body"><div className="race-form-grid"><label className="field">着金額<input type="number" min={1} value={receivedAmount} onChange={event => setReceivedAmount(event.target.value)} /></label><label className="field">着金日時<input type="datetime-local" value={receivedAt} onChange={event => setReceivedAt(event.target.value)} /></label></div></div>{!data?.bankTransfers.length ? <div className="panel-body"><p className="muted">銀行振込の申込はありません。</p></div> : <div className="billing-support-admin">{data.bankTransfers.map(item => <article className="billing-support-item" key={item.id}><div><span className={`status-tag ${item.status === 'CONFIRMED' ? '' : 'warning'}`}>{bankTransferStatusLabels[item.status] ?? item.status}</span><h3>{item.planCode}{item.raceDate ? `・${item.raceDate}` : ''}</h3><p>{item.user.displayName} · {item.user.email ?? 'メール未設定'} · {money(item.amountYen)}</p><small>識別番号 {item.referenceCode} · 振込名義 {item.payerName ?? '未報告'} · 期限 {date(item.expiresAt)}</small>{item.reviewReason && <small>対応理由：{item.reviewReason}</small>}</div>{item.status === 'TRANSFER_REPORTED' && <div className="review-actions"><button className="button" disabled={!reason.trim() || !receivedAmount || !receivedAt} onClick={() => void reviewBankTransfer(item, 'CONFIRM')}>着金確認・権限付与</button><button className="button danger secondary" disabled={!reason.trim()} onClick={() => void reviewBankTransfer(item, 'REJECT')}>却下</button></div>}</article>)}</div>}</section>
    <section className="panel"><div className="panel-heading"><div><h2>支払済み・要確認の決済</h2><small className="muted">権限を付与できなかった支払いです。会員状態と重複契約を確認して対応してください。</small></div><span className="count-tag">要確認 {data?.reviewCheckouts?.length ?? 0}件</span></div>{!data?.reviewCheckouts?.length ? <div className="panel-body"><p className="muted">対応が必要な支払いはありません。</p></div> : <div className="billing-support-admin">{data.reviewCheckouts.map(item => <article className="billing-support-item" key={item.id}><div><span className="status-tag warning">{item.status === 'REVIEW_REFUNDING' ? '返金確認中' : '要確認'}</span><h3>{item.planCode}{item.raceDate ? `・${item.raceDate}` : ''}</h3><p>{item.status === 'REJECTED_ACCOUNT_STATE' ? '会員状態が変わったため権限を付与できませんでした。' : item.status === 'REJECTED_FOUNDER_LIMIT' ? '創設会員枠が上限に達したため権限を付与できませんでした。' : item.status === 'REJECTED_EXISTING_ACCESS' ? '既存の契約・一日券と競合したため権限を付与できませんでした。' : 'Stripeの返金状態を再確認してください。'}</p><small>{item.user.displayName} · {item.user.email ?? 'メール未設定'} · {money(item.amountYen)} · {item.completedAt ? date(item.completedAt) : '時刻未確定'}</small></div><div className="review-actions"><button className="button secondary small" disabled={!reason.trim() || item.status === 'REVIEW_REFUNDING'} onClick={() => void resolveReview(item.id, 'GRANT_ACCESS')}>再検証して権限付与</button><button className="button danger small" disabled={!reason.trim()} onClick={() => void resolveReview(item.id, 'REFUND')}>{item.status === 'REVIEW_REFUNDING' ? '返金を再確認' : '全額返金'}</button></div></article>)}</div>}</section>
    <section className="panel"><div className="panel-heading"><h2>公開待ち期限切れの一日券</h2><span className="count-tag">要確認 {data?.pendingDayPassReviews?.length ?? 0}件</span></div>{!data?.pendingDayPassReviews?.length ? <div className="panel-body"><p className="muted">返金確認が必要な一日券はありません。</p></div> : <div className="table-scroll"><table><thead><tr><th>会員</th><th>対象日</th><th>金額</th><th>期限</th><th>対応</th></tr></thead><tbody>{data.pendingDayPassReviews.map(pass => <tr key={pass.id}><td>{pass.user.displayName}<small className="cell-note">{pass.user.email}</small></td><td>{pass.raceDate}</td><td>{money(pass.priceYen)}</td><td>{date(pass.endsAt)}</td><td><button className="button small" disabled={!reason.trim()} onClick={() => void refundDayPass(pass.id)}>{pass.status === 'REFUNDING' ? '返金を再確認' : '返金する'}</button></td></tr>)}</tbody></table></div>}</section>
    <section className="panel"><div className="panel-heading"><h2>請求問い合わせ</h2><span className="count-tag">未解決 {data?.supportRequests.filter(item => item.status !== 'RESOLVED').length ?? 0}件</span></div>{!data?.supportRequests.length ? <div className="panel-body"><p className="muted">請求問い合わせはありません。</p></div> : <div className="billing-support-admin">{data.supportRequests.map(item => <article className="billing-support-item" key={item.id}><div><span className={`status-tag ${item.status === 'RESOLVED' ? '' : 'warning'}`}>{supportStatusLabels[item.status]}</span><h3>{supportCategoryLabels[item.category]}</h3><p>{item.message}</p><small>{item.user?.displayName} · {item.user?.email ?? 'メール未設定'} · {date(item.createdAt)}</small>{item.paymentTransaction && <small>対象支払：{date(item.paymentTransaction.occurredAt)} · {money(item.paymentTransaction.amountYen)} · {item.paymentTransaction.status}</small>}{item.events.length > 1 && <details><summary>対応履歴 {item.events.length}件</summary><ol>{item.events.map(event => <li key={event.id ?? `${event.eventType}:${event.occurredAt}`}><strong>{event.eventType}</strong> · {date(event.occurredAt)}{event.reason ? ` · ${event.reason}` : ''}</li>)}</ol></details>}</div><div className="review-actions">{item.status === 'OPEN' && <button className="button secondary small" onClick={() => void supportAction(item.id, 'IN_PROGRESS')}>対応を開始</button>}{item.status !== 'RESOLVED' && <button className="button small" onClick={() => void supportAction(item.id, 'RESOLVED')}>解決済みにする</button>}{item.status === 'RESOLVED' && <button className="button secondary small" onClick={() => void supportAction(item.id, 'OPEN')}>再開する</button>}</div></article>)}</div>}</section>
    <section className="panel"><div className="panel-heading"><h2>支払試行履歴</h2></div><div className="table-scroll"><table><thead><tr><th>日時</th><th>会員</th><th>種別</th><th>状態</th><th>金額</th></tr></thead><tbody>{data?.payments.map(p => <tr key={p.id}><td>{date(p.occurredAt)}</td><td>{p.user?.displayName}</td><td>{p.kind}</td><td>{p.status}</td><td>{money(p.amountYen)}</td></tr>)}</tbody></table></div></section>
    {!!data?.checkouts?.length && <section className="panel"><div className="panel-heading"><h2>外部決済申込</h2></div><div className="table-scroll"><table><thead><tr><th>開始日時</th><th>会員</th><th>プラン</th><th>状態</th><th>金額</th></tr></thead><tbody>{data.checkouts.map(item => <tr key={item.id}><td>{date(item.createdAt)}</td><td>{item.user.displayName}<small className="cell-note">{item.user.email}</small></td><td>{item.planCode}{item.raceDate ? ` · ${item.raceDate}` : ''}</td><td>{item.status}</td><td>{money(item.amountYen)}</td></tr>)}</tbody></table></div></section>}
    {!!data?.stripeWebhooks?.length && <section className="panel"><div className="panel-heading"><h2>Stripe Webhook受信</h2></div><div className="table-scroll"><table><thead><tr><th>受信日時</th><th>イベント</th><th>結果</th><th>モード</th></tr></thead><tbody>{data.stripeWebhooks.map(item => <tr key={item.id}><td>{date(item.receivedAt)}</td><td>{item.eventType}<small className="cell-note mono">{item.providerEventId}</small></td><td>{item.outcome}</td><td>{item.livemode ? 'LIVE' : 'TEST'}</td></tr>)}</tbody></table></div></section>}</>;
}
