'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { Archive, ArrowRight, CalendarClock, FileText, Headphones, LockKeyhole, Plus, RotateCcw, Video } from 'lucide-react';
import type { AdminContentItemResponse, AdminContentListResponse, AdminContentMutationResponse, AdminContentRaceOptionsResponse, ContentDraft, PublicContentDetailResponse, PublicContentListResponse, PublicRaceRelatedContentResponse } from '@keiba/domain';
import { PaidContentWatermark, type PaidContentViewer } from './paid-content-watermark';

const emptyDraft: ContentDraft = { kind: 'ARTICLE', title: '', summary: '', body: '', thumbnailUrl: null, mediaUrl: null, category: '読みもの', tags: [], relatedRaceIds: [], visibility: 'PUBLIC' };
const kindLabel = { ARTICLE: '記事', VIDEO: '動画', AUDIO: '音声' } as const;
const visibilityLabel = { PUBLIC: '一般公開', MEMBERS: '会員限定', PAID: '有料会員限定' } as const;
const statusLabel = { DRAFT: '下書き', SCHEDULED: '予約中', PUBLISHED: '公開中', ARCHIVED: '公開終了' } as const;
const adminStateLabel = (item: AdminContentItemResponse) => item.scheduleError ? '予約公開失敗・要確認' : item.status === 'SCHEDULED'
  ? item.isVisible ? '公開中・新版予約' : '初回公開予約'
  : item.status === 'DRAFT' && item.isVisible ? '公開中・未公開の変更あり' : statusLabel[item.status];
const icon = (kind: ContentDraft['kind']) => kind === 'VIDEO' ? <Video /> : kind === 'AUDIO' ? <Headphones /> : <FileText />;
const jst = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const today = () => new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });

async function api<T>(path: string, method = 'GET', body?: unknown) {
  const response = await fetch(`/api/v1/${path}`, { method, cache: 'no-store', headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const value = await response.json(); if (!response.ok) throw new Error(value.message ?? '処理できませんでした。'); return value as T;
}

export function ContentManager() {
  const [items, setItems] = useState<AdminContentListResponse['items']>([]); const [selected, setSelected] = useState<AdminContentItemResponse | null>(null);
  const [draft, setDraft] = useState<ContentDraft>(emptyDraft); const [reason, setReason] = useState(''); const [scheduledAt, setScheduledAt] = useState('');
  const [raceDate, setRaceDate] = useState(today); const [raceOptions, setRaceOptions] = useState<AdminContentRaceOptionsResponse['items']>([]);
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const value = await api<AdminContentListResponse>('admin/content'); setItems(value.items); setSelected(current => current ? value.items.find(item => item.id === current.id) ?? null : null); }, []);
  useEffect(() => { load().catch(e => setError(e.message)); }, [load]);
  useEffect(() => { const params = new URLSearchParams({ date: raceDate }); if (draft.relatedRaceIds.length) params.set('ids', draft.relatedRaceIds.join(',')); api<AdminContentRaceOptionsResponse>(`admin/content/races?${params}`).then(value => setRaceOptions(value.items)).catch(e => setError(e.message)); }, [raceDate, draft.relatedRaceIds]);
  function open(item: AdminContentItemResponse) { setSelected(item); setDraft(item.draft); setReason(''); setScheduledAt(item.scheduledAt ? new Date(item.scheduledAt).toISOString().slice(0, 16) : ''); setMessage(''); }
  function create() { setSelected(null); setDraft(emptyDraft); setReason(''); setScheduledAt(''); setMessage(''); }
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); setError(''); setMessage(''); try { await action(); await load(); setMessage(success); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); const id = selected?.id ?? crypto.randomUUID(); await run(async () => { const item = await api<AdminContentItemResponse>('admin/content/draft', 'POST', { id, revision: selected?.revision ?? 0, draft, reason }); setSelected(item); setDraft(item.draft); setReason(''); }, selected ? '下書きを更新しました。' : '下書きを作成しました。'); }
  async function mutate(action: 'publish' | 'schedule' | 'schedule/cancel' | 'archive' | 'restore', success: string) { if (!selected) return; await run(async () => { const body = action === 'schedule' ? { revision: selected.revision, reason, scheduledAt: new Date(scheduledAt).toISOString() } : { revision: selected.revision, reason }; await api<AdminContentMutationResponse>(`admin/content/${selected.id}/${action}`, 'POST', body); setReason(''); }, success); }
  function toggleRace(id: string, checked: boolean) { setDraft(current => ({ ...current, relatedRaceIds: checked ? [...current.relatedRaceIds, id].slice(0, 10) : current.relatedRaceIds.filter(value => value !== id) })); }
  const changed = !!selected && JSON.stringify(selected.draft) !== JSON.stringify(draft);
  return <><div className="page-heading"><span className="eyebrow">CONTENT CMS</span><h1>記事・動画・音声</h1><p>会員向けコンテンツを下書きし、即時または予約で公開します。</p></div>
    {error && <div className="notice error" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <div className="content-manager-layout"><section className="panel content-admin-list"><div className="panel-heading"><div><h2>コンテンツ一覧</h2><span className="muted">{items.length}件</span></div><button className="button small" onClick={create}><Plus size={16} />新規作成</button></div>{items.length ? items.map(item => <button type="button" className={`content-admin-row ${selected?.id === item.id ? 'active' : ''}`} onClick={() => open(item)} key={item.id}><span className="content-kind-icon">{icon(item.draft.kind)}</span><span><strong>{item.draft.title}</strong><small>{kindLabel[item.draft.kind]} · {visibilityLabel[item.draft.visibility]} · {adminStateLabel(item)}</small></span></button>) : <div className="empty"><FileText /><p>下書きはまだありません。</p></div>}</section>
      <section className="panel content-editor"><div className="panel-heading"><div><span className="eyebrow">{selected ? `REVISION ${selected.revision}` : 'NEW CONTENT'}</span><h2>{selected ? selected.draft.title : '新しいコンテンツ'}</h2></div>{selected && <span className={`status-tag ${selected.status === 'ARCHIVED' ? 'warning' : ''}`}>{adminStateLabel(selected)}</span>}</div>
        <form className="panel-body" onSubmit={save}><div className="content-editor-grid"><label className="field">種類<select value={draft.kind} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, kind: e.target.value as ContentDraft['kind'], mediaUrl: e.target.value === 'ARTICLE' ? null : draft.mediaUrl })}><option value="ARTICLE">記事</option><option value="VIDEO">動画</option><option value="AUDIO">音声</option></select></label><label className="field">公開範囲<select value={draft.visibility} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, visibility: e.target.value as ContentDraft['visibility'] })}><option value="PUBLIC">一般公開</option><option value="MEMBERS">無料会員を含む会員限定</option><option value="PAID">有料会員限定</option></select></label></div>
          <label className="field">タイトル<input maxLength={160} required value={draft.title} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label className="field">概要<textarea rows={3} maxLength={500} required value={draft.summary} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, summary: e.target.value })} /></label><label className="field">本文<textarea rows={12} maxLength={20000} required value={draft.body} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, body: e.target.value })} /></label>
          <div className="content-editor-grid"><label className="field">カテゴリ<input maxLength={80} required value={draft.category} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, category: e.target.value })} /></label><label className="field">タグ（カンマ区切り・10件まで）<input value={draft.tags.join(', ')} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, tags: e.target.value.split(',').map(value => value.trim()).filter(Boolean).slice(0, 10) })} /></label></div>
          <fieldset className="field content-race-links" disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'}><legend>関連レース（任意・10件まで）</legend><label className="field">開催日<input type="date" value={raceDate} onChange={e => setRaceDate(e.target.value)} /></label><div className="content-race-options">{raceOptions.length ? raceOptions.map(race => <label key={race.id}><input type="checkbox" checked={draft.relatedRaceIds.includes(race.id)} disabled={!draft.relatedRaceIds.includes(race.id) && draft.relatedRaceIds.length >= 10} onChange={e => toggleRace(race.id, e.target.checked)} /><span>{race.raceDate} {race.venue} {race.number}R<br /><small>{race.name} ・ {jst(race.startsAt)} JST</small></span></label>) : <p className="muted">この日の登録済みレースはありません。</p>}</div><small>公開後はレース詳細に関連コンテンツとして表示されます。</small></fieldset>
          <label className="field">サムネイルURL（任意・HTTPS）<input type="url" value={draft.thumbnailUrl ?? ''} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, thumbnailUrl: e.target.value || null })} /></label>{draft.kind !== 'ARTICLE' && <label className="field">{draft.kind === 'VIDEO' ? '動画' : '音声'}URL（HTTPS）<input type="url" required value={draft.mediaUrl ?? ''} disabled={selected?.status === 'SCHEDULED' || selected?.status === 'ARCHIVED'} onChange={e => setDraft({ ...draft, mediaUrl: e.target.value || null })} /><small>安全のためサイト内へ埋め込まず、配信元を別画面で開きます。</small></label>}
          <label className="field">操作理由<input maxLength={500} required value={reason} onChange={e => setReason(e.target.value)} placeholder="例：初回公開用の原稿を作成" /></label>
          {selected?.scheduleError && <div className="notice error">予約公開に失敗しました：{selected.scheduleError}</div>}
          <div className="panel-actions content-editor-actions">{selected?.status !== 'SCHEDULED' && selected?.status !== 'ARCHIVED' && <button className="button secondary" disabled={busy}>下書きを保存</button>}{selected?.status === 'ARCHIVED' ? <button type="button" className="button secondary" disabled={busy || !reason.trim()} onClick={() => void mutate('restore', '公開終了を解除し、下書きに戻しました。')}><RotateCcw size={16} />下書きに戻す</button> : selected?.status === 'SCHEDULED' ? <button type="button" className="button secondary" disabled={busy || !reason.trim()} onClick={() => void mutate('schedule/cancel', '公開予約を取り消しました。')}>予約を取り消す</button> : selected && !changed && <><button type="button" className="button" disabled={busy || !reason.trim()} onClick={() => void mutate('publish', '新しい公開版を公開しました。')}>今すぐ公開</button><label className="field inline-schedule">公開予約時刻<input type="datetime-local" value={scheduledAt} onChange={e => setScheduledAt(e.target.value)} /></label><button type="button" className="button secondary" disabled={busy || !reason.trim() || !scheduledAt} onClick={() => void mutate('schedule', '公開を予約しました。')}><CalendarClock size={16} />予約する</button>{selected.versions.length > 0 && <button type="button" className="button danger" disabled={busy || !reason.trim()} onClick={() => void mutate('archive', '公開を終了しました。履歴は保持されています。')}><Archive size={16} />公開終了</button>}</>}</div>{changed && <p className="muted">変更を保存してから公開してください。</p>}
        </form>
        {!!selected?.versions.length && <div className="panel-body"><h3>公開履歴</h3>{selected.versions.map(version => <p key={version.id}>第{version.version}版 · {jst(version.publishedAt)} JST · {visibilityLabel[version.visibility]}</p>)}</div>}
      </section></div></>;
}

export function ContentLibrary() {
  const [kind, setKind] = useState<'ALL' | ContentDraft['kind']>('ALL'); const [category, setCategory] = useState(''); const [data, setData] = useState<PublicContentListResponse | null>(null); const [error, setError] = useState('');
  useEffect(() => { const params = new URLSearchParams({ kind }); if (category) params.set('category', category); api<PublicContentListResponse>(`content?${params}`).then(setData).catch(e => setError(e.message)); }, [kind, category]);
  return <><div className="page-heading"><span className="eyebrow">CONTENT LIBRARY</span><h1>記事・動画・音声</h1><p>競馬をより深く楽しむための読みものと解説です。</p></div>{error && <div className="notice error">{error}</div>}<section className="panel content-filters"><label className="field">種類<select value={kind} onChange={e => setKind(e.target.value as typeof kind)}><option value="ALL">すべて</option><option value="ARTICLE">記事</option><option value="VIDEO">動画</option><option value="AUDIO">音声</option></select></label><label className="field">カテゴリ<select value={category} onChange={e => setCategory(e.target.value)}><option value="">すべて</option>{data?.filters.categories.map(value => <option value={value} key={value}>{value}</option>)}</select></label></section><section className="content-library-grid">{data?.items.map(item => <article className="panel content-card" key={item.id}>{item.thumbnailUrl && <img src={item.thumbnailUrl} alt="" loading="lazy" referrerPolicy="no-referrer" />}<div className="content-card-body"><div><span className="status-tag">{kindLabel[item.kind]}</span><span className="status-tag neutral">{visibilityLabel[item.visibility]}</span></div><h2>{item.title}</h2><p>{item.summary}</p><small>{item.category} · {jst(item.publishedAt)} JST</small><Link className="button secondary small" href={`/content/${item.id}`}>{item.locked && <LockKeyhole size={15} />}読む <ArrowRight size={15} /></Link></div></article>)}</section>{data && !data.items.length && <section className="panel"><div className="empty"><FileText /><h3>公開中のコンテンツはありません</h3></div></section>}</>;
}

export function ContentPage({ id, loggedIn, viewer }: { id: string; loggedIn: boolean; viewer: PaidContentViewer | null }) {
  const [item, setItem] = useState<PublicContentDetailResponse | null>(null); const [error, setError] = useState('');
  useEffect(() => { api<PublicContentDetailResponse>(`content/${id}`).then(setItem).catch(e => setError(e.message)); }, [id]);
  if (error) return <div className="notice error">{error}</div>; if (!item) return <div className="loading">コンテンツを読み込み中…</div>;
  const article = <article className="panel content-detail">{item.thumbnailUrl && <img src={item.thumbnailUrl} alt="" referrerPolicy="no-referrer" />}<div className="panel-body"><div><span className="status-tag">{kindLabel[item.kind]}</span><span className="status-tag neutral">{visibilityLabel[item.visibility]}</span></div><h1>{item.title}</h1><p className="content-lead">{item.summary}</p><small>{item.category} · {jst(item.publishedAt)} JST</small>{item.relatedRaces.length > 0 && <div className="content-related-races"><strong>関連レース</strong>{item.relatedRaces.map(race => <Link key={race.id} href={`/races/${race.id}`}>{race.raceDate} {race.venue} {race.number}R {race.name}</Link>)}</div>}{item.locked ? <div className="content-lock"><LockKeyhole size={30} /><h2>{item.visibility === 'PAID' ? '有料会員限定です' : '会員限定です'}</h2><p>{item.visibility === 'PAID' ? '対象の月額プランまたは閲覧権限で本文を確認できます。' : '無料会員登録またはログイン後に本文を確認できます。'}</p><Link className="button" href={loggedIn ? '/plans' : '/login?returnTo=%2Fcontent'}>{loggedIn ? '料金プランを確認' : 'ログイン'}</Link></div> : <><div className="content-body">{item.body}</div>{item.mediaUrl && <a className="button content-media-link" href={item.mediaUrl} target="_blank" rel="noopener noreferrer">{item.kind === 'VIDEO' ? '動画を開く' : '音声を開く'} <ArrowRight size={16} /></a>}</>}</div></article>;
  return <>{item.visibility === 'PAID' && !item.locked && viewer ? <PaidContentWatermark viewer={viewer}>{article}</PaidContentWatermark> : article}</>;
}

export function RaceRelatedContent({ raceId }: { raceId: string }) {
  const [data, setData] = useState<PublicRaceRelatedContentResponse | null>(null);
  useEffect(() => { api<PublicRaceRelatedContentResponse>(`races/${raceId}/content`).then(setData).catch(() => setData({ items: [] })); }, [raceId]);
  if (!data?.items.length) return null;
  return <section className="panel"><div className="panel-heading"><div><span className="eyebrow">RELATED CONTENT</span><h2>このレースの記事・動画・音声</h2></div></div><div className="panel-body content-related-list">{data.items.map(item => <article key={item.id}><div><span className="status-tag">{kindLabel[item.kind]}</span>{item.locked && <LockKeyhole size={15} />}</div><h3>{item.title}</h3><p>{item.summary}</p><Link className="button secondary small" href={`/content/${item.id}`}>{item.locked ? '公開情報を確認' : '内容を見る'} <ArrowRight size={15} /></Link></article>)}</div></section>;
}
