'use client';
import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Eye, RefreshCw, X } from 'lucide-react';
import { NotificationPreview, type NotificationPreviewData } from './notification-preview';

type Schedule = { id: string; kind: 'RACE_ANNOUNCEMENT' | 'FREE_REPORT_PRE_RACE'; draftRevision: number | null; scheduledAt: string; status: string; reason: string; errorCode: string | null; processedAt: string | null };
type Race = { id: string; venue: string; number: number; name: string; startsAt: string; status: string; announcements: { version: number }[]; freeReportDraft: { revision: number } | null; freeReportVersions: { version: number }[]; publicationSchedules: Schedule[]; warnings: string[] };
type Response = { generatedAt: string; items: Race[]; alerts: number; failedDeliveries: number };
const kindLabels = { RACE_ANNOUNCEMENT: '対象レース告知', FREE_REPORT_PRE_RACE: '無料パドック速報' } as const;
const statusLabels: Record<string, string> = { PENDING: '予約中', PROCESSING: '実行中', PUBLISHED: '公開済み', FAILED: '失敗', CANCELLED: '取消済み' };
const errorLabels: Record<string, string> = { SCHEDULE_CREATOR_INVALID: '予約者の権限が無効です', SCHEDULE_DEADLINE_PASSED: '発走時刻を過ぎました', SCHEDULE_DRAFT_CHANGED: '予約後に下書きが変更されました', SCHEDULE_ENTRIES_INVALID: '選択馬の状態が変更されました', SCHEDULE_EXECUTION_FAILED: '実行時にエラーが発生しました' };
const today = () => new Date(Date.now() + 9 * 3600000).toISOString().slice(0, 10);
const localTime = (date: Date) => new Date(date.getTime() + 9 * 3600000).toISOString().slice(0, 16);
const format = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> { const response = await fetch(`/api/v1/${path}`, { method, cache: 'no-store', headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), ...(method === 'POST' ? { 'Idempotency-Key': crypto.randomUUID() } : {}) }, body: body ? JSON.stringify(body) : undefined }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? '処理できませんでした。'); return result as T; }

function ScheduleForm({ race, reload }: { race: Race; reload: () => Promise<void> }) {
  const [kind, setKind] = useState<'RACE_ANNOUNCEMENT' | 'FREE_REPORT_PRE_RACE'>('RACE_ANNOUNCEMENT'); const [scheduledAt, setScheduledAt] = useState(localTime(new Date(Math.min(Date.now() + 10 * 60_000, new Date(race.startsAt).getTime() - 60_000)))); const [reason, setReason] = useState(''); const [cancelReasons, setCancelReasons] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [preview, setPreview] = useState<NotificationPreviewData | null>(null);
  async function create() { setBusy('create'); setError(''); try { await api('admin/publication-schedules', 'POST', { raceId: race.id, kind, draftRevision: kind === 'FREE_REPORT_PRE_RACE' ? race.freeReportDraft?.revision ?? null : null, scheduledAt: new Date(`${scheduledAt}:00+09:00`).toISOString(), reason }); setReason(''); setPreview(null); await reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function loadPreview() { setBusy('preview'); setError(''); try { const plannedAt = new Date(`${scheduledAt}:00+09:00`).toISOString(); const endpoint = kind === 'RACE_ANNOUNCEMENT' ? `admin/notifications/previews/race-announcement?raceId=${race.id}&scheduledAt=${encodeURIComponent(plannedAt)}` : `admin/notifications/previews/free-report?raceId=${race.id}&kind=PRE_RACE&revision=${race.freeReportDraft?.revision ?? 0}&scheduledAt=${encodeURIComponent(plannedAt)}`; setPreview(await api<NotificationPreviewData>(endpoint)); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  async function cancel(schedule: Schedule) { setBusy(schedule.id); setError(''); try { await api(`admin/publication-schedules/${schedule.id}/cancel`, 'POST', { reason: cancelReasons[schedule.id] ?? '' }); await reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  const pendingKind = race.publicationSchedules.some(schedule => ['PENDING', 'PROCESSING'].includes(schedule.status) && schedule.kind === kind);
  return <article className={`schedule-race ${race.warnings.length ? 'needs-attention' : ''}`}><div className="schedule-race-heading"><div><span>{race.venue} {race.number}R</span><h3>{race.name}</h3><small>発走 {format(race.startsAt)} JST</small></div>{race.warnings.length > 0 && <AlertTriangle size={21} />}</div>{race.warnings.length > 0 && <div className="operation-warnings" role="status">{race.warnings.map(warning => <span key={warning}>{warning}</span>)}</div>}
    <div className="schedule-create"><label className="field">配信<select value={kind} onChange={e => { setKind(e.target.value as typeof kind); setPreview(null); }}><option value="RACE_ANNOUNCEMENT">対象レース告知</option><option value="FREE_REPORT_PRE_RACE" disabled={!race.freeReportDraft}>無料パドック速報{race.freeReportDraft ? `（下書きv${race.freeReportDraft.revision}）` : '（下書きなし）'}</option></select></label><label className="field">公開日時（JST）<input type="datetime-local" value={scheduledAt} max={localTime(new Date(new Date(race.startsAt).getTime() - 1000))} onChange={e => { setScheduledAt(e.target.value); setPreview(null); }} /></label><label className="field">予約理由<input value={reason} maxLength={500} placeholder="配信予定を確定" onChange={e => setReason(e.target.value)} /></label><button className="button secondary" disabled={busy === 'preview' || !reason.trim() || !scheduledAt || pendingKind} onClick={() => void loadPreview()}><Eye size={16} />{pendingKind ? '同種の予約あり' : busy === 'preview' ? '確認中…' : '配信内容を確認'}</button></div>{error && <div className="notice error" role="alert">{error}</div>}
    {preview && <NotificationPreview preview={preview} busy={busy === 'create'} action={{ label: 'この内容で予約する', onClick: () => void create() }} />}
    {race.publicationSchedules.length > 0 && <div className="schedule-history">{race.publicationSchedules.map(schedule => <div className="schedule-row" key={schedule.id}><div><span className={`status-tag ${schedule.status === 'FAILED' ? 'warning' : ''}`}>{statusLabels[schedule.status] ?? schedule.status}</span><strong>{kindLabels[schedule.kind]}</strong><small>{format(schedule.scheduledAt)} JST · {schedule.reason}{schedule.errorCode ? ` · ${errorLabels[schedule.errorCode] ?? schedule.errorCode}` : ''}</small></div>{schedule.status === 'PENDING' && <div className="schedule-cancel"><input aria-label={`${kindLabels[schedule.kind]}の取消理由`} value={cancelReasons[schedule.id] ?? ''} maxLength={500} placeholder="取消理由" onChange={e => setCancelReasons({ ...cancelReasons, [schedule.id]: e.target.value })} /><button className="button secondary small" disabled={busy === schedule.id || !(cancelReasons[schedule.id] ?? '').trim()} onClick={() => void cancel(schedule)}><X size={15} />取消</button></div>}</div>)}</div>}
  </article>;
}

export function PublicationSchedules() {
  const [date, setDate] = useState(today()); const [data, setData] = useState<Response | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { setData(await api<Response>(`admin/publication-schedules?date=${date}`)); setError(''); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, [date]);
  useEffect(() => { void load(); const timer = window.setInterval(() => { if (document.visibilityState === 'visible') void load(); }, 30000); return () => window.clearInterval(timer); }, [load]);
  return <><div className="page-heading"><span className="eyebrow">SCHEDULED DELIVERY</span><h1>配信予約・アラート</h1><p>対象レース告知と無料速報を予約し、公開遅延と通知失敗を確認します。</p></div>{error && <div className="notice error" role="alert">{error}</div>}{data && <section className={`schedule-alert-summary ${data.alerts ? 'has-alerts' : ''}`}><AlertTriangle size={22} /><div><strong>{data.alerts ? `${data.alerts}件の確認事項があります` : '配信上の確認事項はありません'}</strong><small>通知失敗 {data.failedDeliveries}件 · 30秒ごとに自動更新</small></div><button className="button secondary small" disabled={loading} onClick={() => void load()}><RefreshCw size={15} className={loading ? 'spin' : ''} />更新</button></section>}<section className="panel"><div className="panel-heading"><h2>開催日別の配信予定</h2><label className="date-filter">開催日<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label></div>{loading && !data ? <div className="panel-body" role="status">配信予定を読み込み中…</div> : data?.items.length ? <div className="schedule-races">{data.items.map(race => <ScheduleForm key={race.id} race={race} reload={load} />)}</div> : <div className="empty"><h3>この日のレースはありません</h3><p>レース管理で開催データを登録してください。</p></div>}</section></>;
}
