'use client';
import { useCallback, useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import Link from 'next/link';
import { CalendarDays, ChevronLeft, ChevronRight, LockKeyhole, Search } from 'lucide-react';
import type { PublicRaceListResponse } from '@keiba/domain';

type Entitlement = { startsAt: string; endsAt: string; raceDate?: string | null };
const today = () => new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
const formatTime = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
function shiftDate(value: string, days: number) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function hasAccess(entitlements: Entitlement[], raceDate: string) { const now = new Date(); return entitlements.some(item => new Date(item.startsAt) <= now && now < new Date(item.endsAt) && (!item.raceDate || item.raceDate === raceDate)); }

export function RaceArchive({ entitlements = [] }: { entitlements?: Entitlement[] }) {
  const [mode, setMode] = useState<'DATE' | 'RANGE'>('DATE'); const [date, setDate] = useState(today); const [dateFrom, setDateFrom] = useState(shiftDate(today(), -30)); const [dateTo, setDateTo] = useState(today);
  const [publication, setPublication] = useState('ALL'); const [result, setResult] = useState('ALL'); const [venue, setVenue] = useState(''); const [keyword, setKeyword] = useState(''); const [appliedKeyword, setAppliedKeyword] = useState(''); const [page, setPage] = useState(1);
  const [data, setData] = useState<PublicRaceListResponse | null>(null); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); setData(null); try { const params = new URLSearchParams({ publication, result, page: String(page), limit: '20' }); if (mode === 'DATE') params.set('date', date); else { params.set('dateFrom', dateFrom); params.set('dateTo', dateTo); } if (venue) params.set('venue', venue); if (appliedKeyword) params.set('keyword', appliedKeyword); const response = await fetch(`/api/v1/races?${params}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? 'レースを取得できませんでした。'); setData(body as PublicRaceListResponse); } catch (e) { setError((e as Error).message); } }, [mode, date, dateFrom, dateTo, publication, result, venue, appliedKeyword, page]);
  useEffect(() => { void load(); }, [load]);
  function changeDate(next: string) { setDate(next); setVenue(''); setPage(1); }
  function switchMode(next: 'DATE' | 'RANGE') { setMode(next); setVenue(''); setPage(1); }
  function submitSearch(event: FormEvent) { event.preventDefault(); setAppliedKeyword(keyword.trim()); setPage(1); }
  return <><div className="page-heading"><span className="eyebrow">RACE ARCHIVE</span><h1>レース・過去予想</h1><p>開催日、期間、競馬場、レース名・馬名から公開済み予想と確定結果を探せます。</p></div>
    <section className="panel race-filters"><div className="archive-mode" role="group" aria-label="検索期間"><button className={`button small ${mode === 'DATE' ? '' : 'secondary'}`} onClick={() => switchMode('DATE')}>1日から探す</button><button className={`button small ${mode === 'RANGE' ? '' : 'secondary'}`} onClick={() => switchMode('RANGE')}>期間から探す</button></div>{mode === 'DATE' ? <div className="date-navigator"><button className="icon-button" aria-label="前日" onClick={() => changeDate(shiftDate(date, -1))}><ChevronLeft /></button><label className="field">開催日<input aria-label="開催日" type="date" value={date} onChange={event => changeDate(event.target.value)} /></label><button className="icon-button" aria-label="翌日" onClick={() => changeDate(shiftDate(date, 1))}><ChevronRight /></button><button className="text-link" onClick={() => changeDate(today())}>今日</button></div> : <div className="archive-range"><label className="field">開始日<input aria-label="開始日" type="date" value={dateFrom} onChange={event => { setDateFrom(event.target.value); setPage(1); }} /></label><label className="field">終了日<input aria-label="終了日" type="date" value={dateTo} onChange={event => { setDateTo(event.target.value); setPage(1); }} /></label><small>一度に検索できる期間は93日以内です。</small></div>}<form className="archive-keyword" onSubmit={submitSearch}><label className="field">レース名・馬名<input aria-label="レース名・馬名" value={keyword} maxLength={80} placeholder="例：秋華賞、馬名" onChange={event => setKeyword(event.target.value)} /></label><button className="button secondary small"><Search size={16} />検索</button></form><div className="race-filter-grid"><label className="field">公開状態<select aria-label="公開状態" value={publication} onChange={event => { setPublication(event.target.value); setPage(1); }}><option value="ALL">すべて</option><option value="ANNOUNCED">対象レース告知済み</option><option value="PUBLISHED">最終予想公開済み</option><option value="UNPUBLISHED">最終予想未公開</option></select></label><label className="field">結果状態<select aria-label="結果状態" value={result} onChange={event => { setResult(event.target.value); setPage(1); }}><option value="ALL">すべて</option><option value="CONFIRMED">結果確定済み</option><option value="PENDING">結果未確定</option></select></label><label className="field">競馬場<select aria-label="競馬場" value={venue} onChange={event => { setVenue(event.target.value); setPage(1); }}><option value="">すべて</option>{data?.filters.venues.map(item => <option key={item} value={item}>{item}</option>)}</select></label></div></section>
    {error && <div className="notice error" role="alert">{error}</div>}
    <section className="panel race-archive-panel">{!data ? <div className="empty" role="status">レースを読み込み中…</div> : data.items.length === 0 ? <div className="empty"><CalendarDays size={32} strokeWidth={1.3} /><h3>該当するレースはありません</h3><p>期間、キーワード、公開状態を変更して確認してください。</p></div> : <div className="race-archive-list">{data.items.map(race => { const prediction = race.latestPrediction; const entitled = hasAccess(entitlements, race.raceDate); const locked = prediction?.visibility === 'PAID' && !entitled; const state = race.status === 'CANCELLED' ? '中止' : prediction ? prediction.visibility === 'FREE' ? '無料予想公開' : locked ? '有料予想公開' : '閲覧可能' : race.latestAnnouncement ? '告知済み・予想準備中' : '最終予想未公開'; return <article className="race-archive-row" key={race.id}><div className="race-number">{race.number}<small>R</small></div><div className="race-archive-copy"><div><span className={`status-tag ${race.status === 'CANCELLED' ? 'warning' : ''}`}>{state}</span>{prediction?.status === 'CORRECTED' && <span className="status-tag warning">訂正版</span>}{race.latestResult && <span className="status-tag">{race.latestResult.raceCanceled ? 'レース中止' : '結果確定'}</span>}</div><h2>{race.name}</h2><p>{mode === 'RANGE' ? `${race.raceDate} · ` : ''}{race.venue} · 発走 {formatTime(race.startsAt)} JST{race.raceClass ? ` · ${race.raceClass}` : ''}{race.distance ? ` · ${race.distance}m` : ''}</p>{prediction && <small>最終予想 第{prediction.version}版 · 公開 {formatTime(prediction.publishedAt)} JST{race.latestResult ? ` · 結果版${race.latestResult.version}` : ''}</small>}</div><Link className="button secondary small" href={`/races/${race.id}`}>{locked && <LockKeyhole size={15} />}詳細を見る</Link></article>; })}</div>}
      {data && data.total > data.limit && <div className="pagination"><span>{data.total}件中 {(page - 1) * data.limit + 1}〜{Math.min(page * data.limit, data.total)}件</span><button className="icon-button" aria-label="前のページ" disabled={page === 1} onClick={() => setPage(value => value - 1)}><ChevronLeft /></button><button className="icon-button" aria-label="次のページ" disabled={page * data.limit >= data.total} onClick={() => setPage(value => value + 1)}><ChevronRight /></button></div>}
    </section></>;
}
