'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { CalendarDays, ChevronLeft, ChevronRight, LockKeyhole } from 'lucide-react';

type Race = { id: string; raceDate: string; venue: string; number: number; name: string; startsAt: string; status: string; raceClass: string | null; distance: number | null; surface: string | null; latestAnnouncement: { version: number; publishedAt: string } | null; latestPrediction: { version: number; status: string; visibility: 'FREE' | 'PAID'; publishedAt: string } | null };
type Data = { items: Race[]; total: number; page: number; limit: number; filters: { date: string; publication: string; venue: string | null; venues: string[] } };
type Entitlement = { startsAt: string; endsAt: string; raceDate?: string | null };
const today = () => new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
const formatTime = (value: string) => new Intl.DateTimeFormat('ja-JP', { timeZone: 'Asia/Tokyo', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
function shiftDate(value: string, days: number) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function hasAccess(entitlements: Entitlement[], raceDate: string) { const now = new Date(); return entitlements.some(item => new Date(item.startsAt) <= now && now < new Date(item.endsAt) && (!item.raceDate || item.raceDate === raceDate)); }

export function RaceArchive({ entitlements = [] }: { entitlements?: Entitlement[] }) {
  const [date, setDate] = useState(today); const [publication, setPublication] = useState('ALL'); const [venue, setVenue] = useState(''); const [page, setPage] = useState(1);
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); setData(null); try { const params = new URLSearchParams({ date, publication, page: String(page), limit: '20' }); if (venue) params.set('venue', venue); const response = await fetch(`/api/v1/races?${params}`, { cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.message ?? 'レースを取得できませんでした。'); setData(result); } catch (e) { setError((e as Error).message); } }, [date, publication, venue, page]);
  useEffect(() => { void load(); }, [load]);
  function changeDate(next: string) { setDate(next); setVenue(''); setPage(1); }
  return <><div className="page-heading"><span className="eyebrow">RACE ARCHIVE</span><h1>レース一覧</h1><p>開催日と公開状態から、対象レースと公開済み予想を探せます。</p></div>
    <section className="panel race-filters"><div className="date-navigator"><button className="icon-button" aria-label="前日" onClick={() => changeDate(shiftDate(date, -1))}><ChevronLeft /></button><label className="field">開催日<input aria-label="開催日" type="date" value={date} onChange={event => changeDate(event.target.value)} /></label><button className="icon-button" aria-label="翌日" onClick={() => changeDate(shiftDate(date, 1))}><ChevronRight /></button><button className="text-link" onClick={() => changeDate(today())}>今日</button></div><div className="race-filter-grid"><label className="field">公開状態<select aria-label="公開状態" value={publication} onChange={event => { setPublication(event.target.value); setPage(1); }}><option value="ALL">すべて</option><option value="ANNOUNCED">対象レース告知済み</option><option value="PUBLISHED">最終予想公開済み</option><option value="UNPUBLISHED">最終予想未公開</option></select></label><label className="field">競馬場<select aria-label="競馬場" value={venue} onChange={event => { setVenue(event.target.value); setPage(1); }}><option value="">すべて</option>{data?.filters.venues.map(item => <option key={item} value={item}>{item}</option>)}</select></label></div></section>
    {error && <div className="notice error" role="alert">{error}</div>}
    <section className="panel race-archive-panel">{!data ? <div className="empty" role="status">レースを読み込み中…</div> : data.items.length === 0 ? <div className="empty"><CalendarDays size={32} strokeWidth={1.3} /><h3>該当するレースはありません</h3><p>開催日または公開状態を変更して確認してください。</p></div> : <div className="race-archive-list">{data.items.map(race => { const prediction = race.latestPrediction; const entitled = hasAccess(entitlements, race.raceDate); const locked = prediction?.visibility === 'PAID' && !entitled; const state = race.status === 'CANCELLED' ? '中止' : prediction ? prediction.visibility === 'FREE' ? '無料予想公開' : locked ? '有料予想公開' : '閲覧可能' : race.latestAnnouncement ? '告知済み・予想準備中' : '最終予想未公開'; return <article className="race-archive-row" key={race.id}><div className="race-number">{race.number}<small>R</small></div><div className="race-archive-copy"><div><span className={`status-tag ${race.status === 'CANCELLED' ? 'warning' : ''}`}>{state}</span>{prediction?.status === 'CORRECTED' && <span className="status-tag warning">訂正版</span>}</div><h2>{race.name}</h2><p>{race.venue} · 発走 {formatTime(race.startsAt)} JST{race.raceClass ? ` · ${race.raceClass}` : ''}{race.distance ? ` · ${race.distance}m` : ''}</p>{prediction && <small>最終予想 第{prediction.version}版 · 公開 {formatTime(prediction.publishedAt)} JST</small>}</div><Link className="button secondary small" href={`/races/${race.id}`}>{locked && <LockKeyhole size={15} />}詳細を見る</Link></article>; })}</div>}
      {data && data.total > data.limit && <div className="pagination"><span>{data.total}件中 {(page - 1) * data.limit + 1}〜{Math.min(page * data.limit, data.total)}件</span><button className="icon-button" aria-label="前のページ" disabled={page === 1} onClick={() => setPage(value => value - 1)}><ChevronLeft /></button><button className="icon-button" aria-label="次のページ" disabled={page * data.limit >= data.total} onClick={() => setPage(value => value + 1)}><ChevronRight /></button></div>}
    </section></>;
}
